### ISSUE TITLE
Fix a major security bug with bash

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol#100]
This is bad because for `bash` it's not enough to escape double quotes... The code is patched on the server with #101 until we find a way to make it right.

https://github.com/tournesol-app/tournesol/blob/214f2865629088950fa25ada7b58c3a0d8c1a9d1/backend/backend/youtube_search.py#L14

![image](https://user-images.githubusercontent.com/1012270/118131797-42949c00-b3ff-11eb-8fa1-ab9e4867c1b1.png)

**Comment by sergeivolodin** [comment]
Following a discussion on Discord, we need to:

-- Use `argv` array instead of `os.system`

![image](https://user-images.githubusercontent.com/1012270/118159454-518a4700-b41d-11eb-9f6f-4133c61ff37a.png)

**Comment by roipoussiere** [comment]
> Following a discussion on Discord, we need to use argv array instead of os.system

Since both Youtube-dl and Tournesol app are written in Python, it makes sense to use Youtube-dl as a Python dependency and avoid system calls.
