### ISSUE TITLE
[front] feat: multi-page lists navigation 

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1001]
The pagination component should allow to quickly access any page. 

Common usecases would be:
- access old comparisons
- watch page 5 of tournesol all time best two days after having watched page 1,2,3,4
- intentionally find videos with lower scores

**Comment by GresilleSiffle** [comment]
We talked also about having the pagination at the end and at the top of video lists to not force the users to scroll down to access the pages.

I could be a good addition, what do you think @lfaucon ?

**Comment by GresilleSiffle** [comment]
**(a)** For instance, the Django admin works as follow:

- you can always access the two first pages
- you can always access the two last pages
- you can always access the next three pages
- you can always access the previous three pages

![capture](https://user-images.githubusercontent.com/39056254/192972100-d2816d85-eef3-4cd4-87ac-acf9d2e4b522.png)

**(b)** There is also a more complex behaviour, when the user is less than 6 pages close to the first or the last page, all the remaining pages are displayed. 

![capture](https://user-images.githubusercontent.com/39056254/192972305-ed661f2a-4dd1-4053-824f-4a35ba89c3b8.png)

What about implementing the behaviour **(a)** to start? Then we could add -100 / -10 / +10 / +100 additional buttons to navigate more quickly, or maybe a text input allowing to type a page number.

If we don't add a text input, the - X / + X buttons can be useful especially when navigation big lists like the all time recommendations, the rate-later list, the comparisons list, etc.

**Comment by bbosson** [comment]
We agreed to implement behavior (a) and add additional -100 / -10 / +10 / +100 buttons to navigate faster, or perhaps a text input to type a page number.
