### ISSUE TITLE
Brainstorm: Finish EigenTrust algorithm and Vouching feature

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1012]

**Comment by GresilleSiffle** [comment]
It's related to this issue: https://github.com/tournesol-app/tournesol/issues/720

We could check the existing code to update the original issue and check the already implemented steps.

**Comment by lfaucon** [comment]
Questions to be answered by @lenhoanglnh  
- Should vouches be approved by the vouchee target?
- Should voting rights be public? Included in the public dataset?
- Should we limit the number of given vouches? 
- What does it mean exactly X vouches for Y? Does it mean that X believes that Y is a human and has an authentic behaviour on theplatform?
- Should vouches be bi-directional?
- Do we need both PRETRUST_BIAS and IMPLICIT_PRETRUST_VOUCH?
- After some time (months, years) should we request users to re-comfirm their list of vouches?
- How do we avoid the case of malicious accounts that received a few vouches from certified accounts and vouched eachothers en masse?
- Do we reach maximum voting rights with a few vouches? Does it change a lot to receive 5, or 1000 vouches? (I believe it should not)

**Comment by lenhoanglnh** [comment]
- Should vouches be approved by the vouchee target?
I lean towards no. The current algorithm (EigenTrust) is monotonic: the more one is vouched, the more voting right they have.

- Should voting rights be public? Included in the public dataset?
I think so.

- Should we limit the number of given vouches?
No. EigenTrust is resilient to over-vouching contributors.

- What does it mean exactly X vouches for Y? Does it mean that X believes that Y is a human and has an authentic behaviour on theplatform?
For now, I'd say yes, and this is the only thing one can be vouching for. Moreover X must believe that Y has a single active account on the platform. This should be clarified when proposing to vouch "I vouch that Y is a human, with an authentic behavior, and that Y does not actively use another account on Tournesol".

- Should vouches be bi-directional?
I'm not sure I understand the question. X may not vouch for Y, even if Y vouches for X. It is also possible that X and Y mutually vouch for one another.

- Should it be easy to vouch someone or require some sort of difficult to guess secret that the vouchee target can distribute?
I think it should be easy.

- Do we need both PRETRUST_BIAS and IMPLICIT_PRETRUST_VOUCH?
Yes. PRETRUST_BIAS guarantees security. IMPLICIT_PRETRUST_VOUCH avoids a definition problem (also, it incentivizes users to vouch for more people).

- After some time (months, years) should we request users to re-comfirm their list of vouches?
It's a good idea. I'd suggest renewing vouches every year :)

- How do we avoid the case of malicious accounts that received a few vouches from certified accounts and vouched each others en masse?
EigenTrust is robust to this.

- Do we reach maximum voting rights with a few vouches? Does it change a lot to receive 5, or 1000 vouches? (I believe it should not)
Yes. The maximum voting right is 1.

**Comment by GresilleSiffle** [comment]
> > Should it be easy to vouch someone or require some sort of difficult to guess secret that the vouchee target can distribute?
> 
> I think it should be easy.

We discussed about this yesterday and we conclude the following:

**(a)** if vouching for someone only requires the knowledge of the target username, a robot can quickly vouch for a lot of accounts, including robots

**(b)** if vouching for someone requires a secret, for instance the target user must give me a generated and temporary HTTP link, then it will be less easy for a robot to vouch for a lot of accounts, including robots

The scenario **(b)** is not a bulwark, it will fail as soon as a program is able to connect to several accounts and send all secrets to a voucher account. The scenario **(a)** can instantly fail. (fail might be a strong word)

I don't fully understand the algorithm yet, so I don't know if what we discussed yesterday is relevant, but I decided to answer so we can take an informed decision.

**Comment by aidanjungo** [comment]
For the following point:

>     * After some time (months, years) should we request users to re-comfirm their list of vouches?
>       It's a good idea. I'd suggest renewing vouches every year :)

If we want to have the trust score on the public database, how should we deal with this score changing overtime?

If 5 people vouch me now, and they did not renew there vouch next year, it will lead to two different version of the database...

**Comment by OscarVlld** [comment]
> If we want to have the trust score on the public database, how should we deal with this score changing overtime?
> 
> If 5 people vouch me now, and they did not renew there vouch next year, it will lead to two different version of the database...

The database is changing all the time, isn't it ? People will gain and lose trust, I don't see why the loss would be a particular case.
