### ISSUE TITLE
Feature request: Peertube

### ISSUE THREAD

**Issue by sachaz** [tournesol-app/tournesol#1027]
Hello,
thanks for this interesting tool !
Could it be compatible with Peertube, is a really good alternative to Youtube with a decentralized a architecture/censorship/libre software...

**Comment by tfardet** [comment]
That would be very interesting, indeed! PeerTube has a lot of potential for decentralizing the streaming ecosystem, but the average content you can find there is no better than on YouTube (well, in fact it can be much better or much worse, depending on the instance), so it would most probably benefit from collaborative content recommendation!
A simple way would be to include these recommendations in the [Discover/Overview tab](https://tilvids.com/videos/overview) and in the [Other videos](https://tilvids.com/w/scumPqR5qDENxkLAkCnWDu) div below the video

**Comment by GresilleSiffle** [comment]
To keep track of all suggestions made until now, both Dailymotion and PeerTube has been suggested.

Another feature could be to make the browser extension work on all platforms, recommending videos regardless of their original source: on YouTube the extension could suggest videos from YouTube and Dailymotion and PeerTube, etc.

**Comment by aidanjungo** [comment]
No bandwidth at the moment

**Comment by tfardet** [comment]
> No bandwidth at the moment

That's perfectly understandable, but why close the issue, then? Isn't it easier to leave it open until someone, someday can have a look at it?

**Comment by aidanjungo** [comment]
> > No bandwidth at the moment
> 
> That's perfectly understandable, but why close the issue, then? Isn't it easier to leave it open until someone, someday can have a look at it?

Sorry, as we use the issue as tracker for tasks we want to do, we try to keep the issue a reasonable number so it stay manageable with our lack of time and people to implement everything. But closed issues can still be found and we can reopen it them needed.
