### ISSUE TITLE
[front] full-text search: how to handle properly the filters?

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1042]
See the original PR: #1039

> 14 (to deliberate) - Shouldn't the frontend someway automatically remove the date filter "A month ago" to return more results? This is especially important because people (including the past me) may not realize that they get very few results because of this filter.

For instance, YouTube resets all filters after a textual search.

**ideas**

searching from the recommendations page, with unfolded filters should not alter filters

? searching from the recommendations page, with folded filters can reset all filters (except the languages?)   ?

searching from elsewhere should reset all filters (except the languages)

**Comment by glerzing** [comment]
What about the "unsafe" filter?

But I also understand that by default unsafe videos should be filtered.
But it could also be disturbing if you search for a specific video and don't find it because it's badly ranked, or not rated by enough contributors yet.

**Comment by glerzing** [comment]
I suggest that when no (or few) result is found, there should be a small sentence that suggests to try without date filter or without safety filter, with a button for both.

For example, if there are only 3 "safe" results but 5 "unsafe" results, then there could be, at the bottom of the page, a note that suggests to try without the date filter or without the safety filter, with one small button for both. Ideally, it would display how many videos were filtered this way (and if none, neither the note nor the button would be displayed), but that would also need some backend rework and could be detrimental for the backend performances.

This could be useful when using the search bar, but also when using the channel filter, so there are 2 use cases where it's important:

![image](https://user-images.githubusercontent.com/47578089/183268570-c242fd20-c597-4532-873d-d58c99e436c2.png)

**Comment by lfaucon** [comment]
TODO:

- [ ] Investigate possible problems with filters and search
- [ ] Describe them
- [ ] Correct them

**Comment by lfaucon** [comment]
Seems that the above ideas have been implemented
