### ISSUE TITLE
Don't rely on the Youtube API in backend tests

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1044]
The tests test_authenticated_can_create_with_new_video_id and test_authenticated_can_create_with_non_existing_entity are failing when the YOUTUBE_API_KEY is set. They should not be really using the Youtube API. 

A mock could be done on the API. 
Or, as a test-specific config, we could chose to set YOUTUBE_API_KEY to an invalid value.

**Comment by GresilleSiffle** [comment]
We could indeed either mock the setting, or mock the `tournesol.utils.api_youtube.get_video_metadata` to force it to always return `{}`.

**Comment by amatissart** [comment]
The simpler fix would probably be to decorate the affected test cases with `@override_settings(YOUTUBE_API_KEY=None)` to make sure no actual API key is used.

Mocking the API calls could also be a good idea if we'd like to check the API response is used correctly, but I think this is already covered by other test cases.

**Comment by glerzing** [comment]
Overriding YOUTUBE_API_KEY does not look sufficient, because it does not cause the "youtube" variable in api_youtube.py to be recreated.

**Comment by glerzing** [comment]
So I think I'll use `@patch('tournesol.utils.api_youtube.youtube', None)` instead, which seems to work.
