### ISSUE TITLE
"My Compared Items" is not sorted by rating date

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1045]
It feels weird when a video that was very recently compared for the 1st time does not appear at the top of "My Compared Items". 
Same the "Compared" suggestions.

![image](https://user-images.githubusercontent.com/47578089/178763373-edbb99e2-a9b6-4ca9-8226-e4eb51ad0893.png)

We could chose to sort them either:
- by the 1st comparison date, among all the comparisons including the given entity
or
- by the last comparison date

Sorting by the last comparison date is maybe better, because then every time an entity is compared, it will appear at the top of "My Compared Items".

It is possible, however, that it would take too long to make this sorting.

**Comment by GresilleSiffle** [comment]
When https://github.com/tournesol-app/tournesol/issues/1160 will be implemented we can discuss about what should be the default ordering.

**Comment by GresilleSiffle** [comment]
The feature has been developed!

The list My compared items is now sorted by `datetime_lastedit`, the recently compared elements appear at the top.
