### ISSUE TITLE
Round tournesol scores

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol#110]
Introduced by #106 

![image](https://user-images.githubusercontent.com/1012270/118519361-57439d80-b739-11eb-8051-4e2e8be93d2c.png)

@lfaucon :)

![image](https://user-images.githubusercontent.com/1012270/118519546-82c68800-b739-11eb-8893-3606fc8bfd0a.png)

**Comment by lfaucon** [comment]
Haha, Nice meme. Sorry for this, thanks for fixing my mess
