### ISSUE TITLE
[front] feat: Make the search available on mobile

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1103]
Because not enough space is available in the header, it could be achieved either with an IconButton Magifying glass or an option in the menu. Otherwise. It could also be an option to include a Search text input on the recommendation page above the filters.

**Comment by amatissart** [comment]
An inspiration could be the SBB mobile site: https://www.sbb.ch/en/ to make the search input appear after one click:

[Capture vidéo du 2023-02-07 20-10-21.webm](https://user-images.githubusercontent.com/4726554/217342278-1c740801-f926-44dd-a7c0-e317c2a5f709.webm)
