### ISSUE TITLE
[front] feat: round all scores

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#1157]
Score display on the graphs of scores and on criteria tooltip should be rounded to the unit. The extra digit is an heritage from past version, it did not bring any interesting information and it overloads the display.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/53896963/194036553-723849f6-deb6-48cc-afc7-71efd90c5e55.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/53896963/194036804-3c4c8495-7ba9-4b61-abcb-5af3efc909a3.png">

**Comment by GresilleSiffle** [comment]
We want to round the scores displayed in the graph and the ones displayed in the card tooltip right?

**Comment by aidanjungo** [comment]
yes, it's not what I wrote in the issue?

**Comment by GresilleSiffle** [comment]
Sure, I read too fast sorry : p

**Comment by riteshsoni123** [comment]
Hello @aidanjungo I would like to solve this issue. Can you please assign this to me?

**Comment by GresilleSiffle** [comment]
Hello @riteshsoni123 

I just assigned the issue to you. Thanks for helping us : ) In case of need, do not hesitate to open a draft PR with your questions or simply join our Discord to talk with developers: https://discord.gg/WvcSG55Bf3
