### ISSUE TITLE
[back] feat: add an `order_by` parameter to the route `GET /users/me/contributor_ratings/`

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1160]
### Context

The front end allows to see all my compared videos. We would like the users to be able to order their compared elements by:
- number of comparisons (by the user, not globally)
- last comparison date (by the user)

To do this, only the back end's API should be updated. The front end UI will be part of a second issue.

### Expected

The endpoint `/users/me/contributor_ratings/` now accept a URL parameter `order_by`, that can have the following values:
- `comparison_date`, the most recent one first
- `-comparison_date`, the oldest first
- `n_comparison`, the most compared first
- `-n_comparison`, the least compared first

If `order_by` receives an unknown value, a 400 Bad Request error should be returned.

This new behaviour must be tested, with at least:
- a test ensuring `order_by=comparison_date` works, both ascending and descending
- a test ensuring `order_by=n_comparison` works, both ascending and descending
- a test ensuring all other values returned a 400 Bad Request error

Do not hesitate to join our Discord to meet the team: https://discord.com/invite/WvcSG55Bf3

**Comment by lk067fn** [comment]
Hi, I would like to work on this. Can you assign that issue to me?

**Comment by GresilleSiffle** [comment]
Sure @lk067fn , welcome here :wave: 

If you need any help regarding the set-up, the developers will be available on Discord.
