### ISSUE TITLE
Move "all_video_ratings.csv" into the public database

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#118]
Right now, this file is in the user data when downloading them from "My profile" page, I propose to:

- rename this file "all_video_scores.csv" 
- add it in the public database instead of the user data
- add a column for the Tournesol score

**Comment by GresilleSiffle** [comment]
Hello @aidanjungo

The modifications are now online on https://tournesol.app : ]

Is the result satisfying?
