### ISSUE TITLE
[discussion] integration of tournesol on youtube app

### ISSUE THREAD

**Issue by jean-raphael** [tournesol-app/tournesol#1182]
do you know vanced ? and revanced ?

revanced - manager is an app on android. 
with this app you can patch youtube to add many feature like add blocks , sponsor bloks and many other.

it will be very cool if it is possible to integrate tournesol app into revanced 

https://github.com/revanced

**Comment by NicolasMICAUX** [comment]
You should probably ask the contributors of https://github.com/revanced, not Tournesol contributors.

**Comment by aidanjungo** [comment]
I added the label suggestion to be able to retrieve the issue in case of need.

Unfortunately we don't have enough fire-power to set up this, but we keep the idea in mind : )
