### ISSUE TITLE
Enable Paypal donations on our website

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#119]
If possible...

Record donators would be good as well.

**Comment by sergeivolodin** [comment]
@lenhoanglnh it's super easy: https://www.paypal.com/donate/buttons

we just need a paypal account to collect everything and maybe some legal notice (completely unsure of this one)

**Comment by lenhoanglnh** [comment]
Here's the Tournesol Paypal account: https://www.paypal.com/paypalme/tournesolapp
And here's the button: https://www.paypal.com/donate/buttons/manage/22T84YR7TZ762

**Comment by lenhoanglnh** [comment]
@sergeivolodin, I've added you to the Paypal account:
Username : sergeivolodin
Paypal integration: https://developer.paypal.com/docs/limited-release/paypal-commerce-platform/business/accept-payments/setup-payments/
