### ISSUE TITLE
Refresh video metadata with higher frequency close to the publication date

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1214]
# Context

In the first hours after publication the metadata of videos changes the most. A concequence is that the video metadata displayed on Tournesol is often obsolete with our curent refresh mechanism that refreshes the metadata of a video at most once every 48h.

We want to increase the refreshing rate while being careful about our YouTube API quota (I believe it is 10'000 requests/day)

# Proposed solution

Refresh if `time_since_last_refresh / publication_time > refresh_threshold`, with conditions at the limits `time_since_last_refresh < 1 minute` -> no refresh and `time_since_last_refresh > 30 days` -> refresh.

With a threshold of 1 that would make us refresh roughly after 1, 2, 4, 8, 16, 32 minutes, 1 hour, 2, 4, 8, 16 hours during the first day of the video publication. Roughly 11 times. Assuming the current rate of contribution of about 30 new videos per day, it would use about 3.3% of our current budget in the worst case. We could even start with a lower threshold to be increased when we need to.

**Comment by amatissart** [comment]
Note that it may be required to solve #818 first, to be able to implement a granularity smaller than 1 day based on the exact publication time.
