### ISSUE TITLE
Add banner about research project

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#1216]
- [x] Link to form, visible for logged in users, possibly with a ["proof of vote"](https://api.tournesol.app/docs/#/users/users_me_proof_of_votes_retrieve) about the poll "videos" to identify the user in the url params

- [x] Similar link on the Youtube homepage via the Tournesol extension, visible during a hardcoded date range.

- [x] Make an announcement on Discord when the experiment begins.

**Comment by lfaucon** [comment]
@lenhoanglnh Can you conact Manoel about this?
