### ISSUE TITLE
Include global aggregated scores of videos in the public dataset

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1217]
Although these scores are computed, they would be useful for anyone to do some data analysis without recomputing them (especially as we currently do not offer an extremely simple way to do this computation with our algorithms)

**Comment by GresilleSiffle** [comment]
Yes please!

I'be been asked for these data by data scientist friends several times.

Should we add more columns in this new file to give more context? In addition to the Tournesol UIDs, and criteria scores, we could display the videos' title, tags, and maybe more metadata like the channel and the publication date.

The channel name could be very useful to allow people to analyse data per channel without having to do a manual match between the video ids and the channel returned by the YT API.

**Comment by lfaucon** [comment]
I'd be happy to include as much info as possible. Let's check whether distributing this data complies with Youtube API policy

**Comment by GresilleSiffle** [comment]
Fixed by https://github.com/tournesol-app/tournesol/pull/1368
