### ISSUE TITLE
[back] feat: display the video duration in entity preview and comparison preview

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1229]
### context

The duration is an important metric that invites (or prevents) users to watch a video.

Thank to the dynamic preview, when we share a entity or a comparison link we are already able to see the thumbnails and the videos' title, but not the duration yet.

The same way we display the duration in the front end, we could display the duration in the dynamic previews.

![capture](https://user-images.githubusercontent.com/39056254/206126158-7b376563-7805-4320-aa86-3b8e399ecaf9.png)

(It could be nice to copy the front end's style, back ground color and transparency, polygon size, etc.)

**Comment by tbrnd** [comment]
hi, is someone working on this? if not I'd like to implement it!

**Comment by aidanjungo** [comment]
Hello, yes you can take care this issue, I assign you to it 🙂
