### ISSUE TITLE
Possibility to score additional criteria when editing a previous incomplete rating 

### ISSUE THREAD

**Issue by EtoiledeScauchy** [tournesol-app/tournesol#123]
On Chrome:
![image](https://user-images.githubusercontent.com/44090250/118720906-7837eb80-b82a-11eb-8d40-f666eb7e229f.png)

**Comment by sergeivolodin** [comment]
@EtoiledeScauchy you can enable the "skip" option and unskip these criteria. It is designed like this on purpose, so that you don't accidentally add a lot of ratings with the slider in the middle
