### ISSUE TITLE
[back] fix: some thumbnails are not available in `maxres` resolution

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1230]
### context

When requesting some comparison previews we saw several videos with a placeholder YT thumbnail instead of their actual thumbnail.

It seems that the requested `maxres` thumbnails in the views are not always available.

- [OK] https://img.youtube.com/vi/nffV2ZuEy_M/mqdefault.jpg
- [OK] https://img.youtube.com/vi/nffV2ZuEy_M/maxresdefault.jpg
- [OK] https://img.youtube.com/vi/vFQYE3aTPLI/mqdefault.jpg
- [placeholder] https://img.youtube.com/vi/vFQYE3aTPLI/maxresdefault.jpg

### proposition

Let's find a solution.

**Comment by sigmike** [comment]
Note that the "hq" and "standard" versions do not have the same aspect ratio, and seem to always have black top and bottom borders. So we must probably use the "mq" version when "maxres" is not available. Or maybe we can crop them to remove the black borders.

If a quick fix is needed you can just switch back to "mq" quality.
