### ISSUE TITLE
QrUnc : use LogSumExp instead of SoftMinMean ?

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1232]
It may be interesting to use the LogSumExp instead of the SoftMinMean as a smooth minimum for the calculation of QrUnc. One reason is that the SoftMinMean isn't really consistent, you can have x1 < x2 and yet SoftMinMean(x1, y) > SoftMinMean(x2, y). Moreover, (I didn't understand why, but) in the paper we say that both elements of SoftMeanMin "represent upper bounds on uncertainty". So we want SoftMeanMin(x, y) < x and SoftMeanMin(x, y) < y. But this is not true, as shown in the following figure, it's the contrary.

The magenta curve represents the min and the red curves the SoftMinMean.

![image](https://user-images.githubusercontent.com/47578089/206081514-05c7aca9-7a2a-498e-8392-76d9430d24ec.png)

The LogSumExp (https://en.wikipedia.org/wiki/Smooth_maximum) looks like it fits more what we are trying to do :

![image](https://user-images.githubusercontent.com/47578089/206081715-d2bfcd7b-aeda-4950-8e62-175a0af9b104.png)

Here is the code to generate and modify the images, and with the implementation of LogSumExp :
https://colab.research.google.com/drive/1QcNQXFxGcu9PnLPIhyGafCH6QyNx936t?usp=sharing

**Comment by glerzing** [comment]
LogSumExp may not be ideal too, because we may like QrUnc to be higher or equal to the "true" uncertainty, not strictly lower.  And because of the arbitrary choice of alpha.

But I think SoftMinMean is problematic because of its inconsistencies (e.g. SoftMinMean(0, 0) = 0, SoftMinMean(1, 0) = 0.26 and SoftMinMean(10, 0) ≈ 0).

Is using a regularized min necessary ? Should we consider using a simple minimum ? (which would simplify the formula)

**Comment by lfaucon** [comment]
@lenhoanglnh Can you look into @glerzing 's recommendations?

Maybe a session about how we handle uncertainty in our algorithms to teach the whole team would be a big help (same as we did for EigenTrust, Voting rights, Video Suggestions, ...).

**Comment by glerzing** [comment]
I wonder why when the uncertainty increases, QrUnc first increases and then decreases

![image](https://user-images.githubusercontent.com/47578089/216798448-51278448-2bb1-4666-bb48-b02de1833024.png)

**Comment by lenhoanglnh** [comment]
Yes this looks a lot better. (sorry for only replying now ^^)

**Comment by lenhoanglnh** [comment]
I think that Min and LogSumExp are both ok, but there's not much of a theory so far.

I liked the idea that when both sources of uncertainties are equally large, they kind of add up. But it's very heuristic at this point and far from well justified.

In any case, these are just rough estimates of uncertainties, which are currently not used on the platform, so I don't think that this should be over-optimized for now.

**Comment by amatissart** [comment]
If I understand correctly, the latest algorithm specifications use LogSumExp to compute `QrUnc`.

@glerzing Do you want to have a go to update the implementation? And maybe adapt/create test cases in [`test_mehestan_primitives.py`](https://github.com/tournesol-app/tournesol/blob/main/backend/ml/tests/test_mehestan_primitives.py) to describe the expected behavior?

**Comment by glerzing** [comment]
Yes, I was preparing a PR.
