### ISSUE TITLE
Determine how to sample mini-batches correctly

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol#125]
- Previously, the mini-batches were used, and that led to a lot of noise, and instability in results #25 
- Right now, full-batch training is used, but it's not scalable with the growth in contributors and videos

@lenhoanglnh we need to design a way to optimize the function with many contributors such that there's not too much noise/instability

**Comment by lenhoanglnh** [comment]
Don't sweat over this. I'll give it to my interns.
