### ISSUE TITLE
Use the new recommendations API /polls/videos/recommendations/ instead of /video/

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1263]
In the comparisons page (tournesol.app/comparison), when you click on the "auto" button to select a random entity, the obsolete API endpoint /video/ is called (which you can see with a `docker logs tournesol-dev-api`).

This endpoint is getting obsolete, and replaced by /polls/videos/recommendations/.

**Comment by lfaucon** [comment]
@abhiram11 Thank you again for your recent contributions. If you want to continue. This could be a nice on too. Feel free to reach out to me on our discord too if you want to discuss about the project 👍

**Comment by abhiram11** [comment]
Hi @lfaucon , I'll look more into this tomorrow and will check out discord as well 😄 will open a PR discussion soon afterwards
