### ISSUE TITLE
[back, infra] perf: downloading the public dataset takes more and more time

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1267]
### Context

The size of our public dataset constantly grows for two mains reasons:
- users add new comparisons every day
- we want to add more file to the dataset archive (vouchers, collective scores, etc.)
- (also we might add more public polls in the future)

We expect the dataset to grow and we want it to be as big as possible. It currently takes a bit more than 10 seconds to build and download the archive, and it will take even more time in the future. The build takes more than 95% of the total download time.

The last time I tried to download the public dataset with a sub-optimal SQL query, the front end "crashed".

### Proposition

**(1) pre-build the dataset one time, download many times**

We don't have to build the dataset on demand. We can build the dataset on a regular basis, let's say hourly, and simply display a download link in the front end. The users won't have to wait during the dataset build, and this will drastically reduce the "download" time.

It's rather simple, and we already have the tools to create and deploy this solution.

**(2) other ideas?**

**Comment by clemsau** [comment]
I am new to the project, are you referring to the `Download our database` functionality on the homepage ? I got ~15s response time by trying it.

If so, it is indeed wrong that the process of building the archive is part of the download process. What you suggested sounds like a good solution to me. 

The archive should be built periodically, cached on your storage and served directly to the frontend. You will save a lot on processing power by doing so.

**Comment by aidanjungo** [comment]
Maybe we could even pre-build the dataset once/twice a day, it reduces the possibility of getting the hour at which people make their comparions.

**Comment by clemsau** [comment]
I don't know the project nor the infrastructure on which everything is hosted. But with a 17s time to build the archive, doing it every hour or every 24h wouldn't be a huge gain. 
The freshness of the data shouldn't be the most important thing when downloading the archive, so building the archive every 24h should be ok too, yes.

There are multiple libraries to set up jobs working with Django like for instance [django_crontab](https://pypi.org/project/django-crontab/) or [celery-beats](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html)

I also recently did the trick of simply setting up a cronjob on my server's crontab to run periodically a Django command, and I set up a service to validate that the job ran correctly, the crontab job looked something like this:
`*/60 * * * * <python_path> <manage.py_path> <command>`

The commands can be defined by extending Django's `BaseCommand` class.

The command here would build the file and store it to an object storage, and the frontend would have to be updated to fetch this pre-built.

**Comment by GresilleSiffle** [comment]
Thank you for your support @clemsau and your detailed suggestions : )

In fact we already have several cron jobs running Django mgmt commands. Adding a new one won't be a challenge. We are just currently waiting for more feedback and propositions from the development team before fixing the issue.
