### ISSUE TITLE
feat: support pasting URL and uid in Search bar

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1268]
Modify the frontend so that, if we enter a uid in the search bar (or something that looks like a uid), if the uid corresponds to an existing video, it directly redirects to the video page (e.g. tournesol.app/entities/yt:dGJzpQwA090), even if the video doesn't have a positive score.

(the problem is that currently, if the video doesn't have a positive score, it will not be displayed unless you check "include all videos" in the advanced filter options)

Feel free to reject this issue if it's not relevant.

**Comment by lfaucon** [comment]
I like the idea! We have wip for something similar: Showing the search in the video selector https://github.com/tournesol-app/tournesol/pull/1706

**Comment by yuyujijin** [comment]
Hi, just pushed to the linked branch (commit https://github.com/tournesol-app/tournesol/commit/70b644c861dd3f5faa23b43c81049cac3f1385b0) :)) Hope it work as intended !
