### ISSUE TITLE
Show video score change over time

### ISSUE THREAD

**Issue by sergia-ch** [tournesol-app/tournesol#127]
Right now, we only display the most recent computed score. We can also display a chart with the historical data of how this score changed over time. Since science and life in general change, it's likely that some concepts become more important, and some become less important. It would be something like [Google Trends](https://trends.google.com/trends/)

Examples:
- Some new event/crisis happens, and videos about it become very popular for a while, and then they gradually go down. The chart would spike and then decay
- Some new covid vaccine is developed, therefore, videos about it become scored higher, while the videos for masks become less important. The chart for the new ones would spike, and the chart for the old ones would go down
- Google and other tech companies take up ethics seriously, and it's no longer our second best video :)

TODO:
- [ ] Add history log for VideoRating and Video tables
- [ ] Add API to get the history
- [ ] Add the chart in front-end in video details page

@lenhoanglnh @lfaucon @tchaumeny @TheDuckWhisperer what do you think?

**Comment by lenhoanglnh** [comment]
Sounds good Definitely not a priority though.
Also, note that this can be re-computed from the public database :)

**Comment by TheDuckWhisperer** [comment]
We could show something like this deeper in the interface, under something like score details. Most people won't be interested or in need of the data but people who are should be able to find it still. Maybe we could have an in-depth data page per video or something.

**Comment by sergeivolodin** [comment]
> Sounds good Definitely not a priority though.
> Also, note that this can be re-computed from the public database :)

The computation takes time and it makes sense to store the values rather than recompute them...
