### ISSUE TITLE
Filtres onglets recommandations

### ISSUE THREAD

**Issue by Lecassecouilles** [tournesol-app/tournesol#1295]
Bonjour,
Pensez vous qu'il serrait possible, dans les recommandations, d'ajouter une fonction pour masquer toutes les vidéos de certaines chaînes (inutile de voir des chaînes auxquelles on est déjà abonné).
Ça permettrait d'en faire découvrir de nouvelles plus modestes au lieu de rester dans son petit confort (bulle de filtre, tout ça, tout ça...)

Merci
Des bisous ;)

**Comment by aidanjungo** [comment]
Thank you for the idea, it's something we have in the pipe. I close the issue because it is already discuss in #368 and probably also in our "suggestion" channel on discord.

**Comment by GresilleSiffle** [comment]
Hello @Lecassecouilles 

Are you talking about the recommendations in the extension or on the Tournesol website? 

@aidanjungo if it's related to the website I think this issue is different enough from the #368 to keep it open.
