### ISSUE TITLE
[New Feature] Compare software

### ISSUE THREAD

**Issue by pierreozoux** [tournesol-app/tournesol#1298]
Hi!

Thanks a lot for this application!
As a hoster of free software, we end up comparing a lot of different softwares to use the best for our users needs.
I was wondering if we could use your app to do so.
And do you think we could add a feature, like Election? Or should we host it somewhere else with this new option?

Thanks for this creation, your time and feedback on this "side" question.

**Comment by GresilleSiffle** [comment]
I added the label suggestion to be able to retrieve the issue in case of need.

Unfortunately we don't have enough fire-power to quickly set up a Software poll, but we keep the idea in mind : )
