### ISSUE TITLE
[back] Comparison export should include week-timestamp

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1299]
We want to include timestamp at the granularity of weeks such that it reveals no sensitive user data into the comparison export.

- [x] make sure our privacy policy is ok with this
- [x] The dataset should not contain data from the current week
- [x] The dataset should be sorted by username>timestamp

**Comment by tbrnd** [comment]
hi @lfaucon couple of questions:

- for the privacy policy, I do not see any conflict with https://tournesol.app/about/privacy_policy but feedback is welcome
- there are two timestamps recorded: datetime_add and datetime_lastedit, which one do you expect?
- can you clarify the last item? what's the difference between week and timestamp?

**Comment by lfaucon** [comment]
> * for the privacy policy, I do not see any conflict with https://tournesol.app/about/privacy_policy but feedback is welcome

All good ☺️ thanks 

> * there are two timestamps recorded: datetime_add and datetime_lastedit, which one do you expect?

Let's use the `datetime_add`, maybe also mention it in the document attached with the dataset.

> * can you clarify the last item? what's the difference between week and timestamp?

`week` is the Monday at 00:00 before the comparison was done, but we still want to be sorting by the true timestamp even if it is not included in the export.

**Comment by tbrnd** [comment]
@lfaucon I think we can close this one!

**Comment by lfaucon** [comment]
Yes! Thanks for your work
