### ISSUE TITLE
Registration on other browers than Chrome

### ISSUE THREAD

**Issue by F-Marchal-Bornert** [tournesol-app/tournesol#13]
I began my registration on Firefox and, after all the process and all the fields completed, it warned me about the necessecity to use Chrome without letting me do anything else. The result was that my profile was nearly empty. 

Suggestion : A warning as soon as possible or completely forbidding to fill the profile when the user is on another browser will better than this situation.

**Comment by sergeivolodin** [comment]
@F-Marchal-Bornert can you give the OS and Firefox versions?

**Comment by F-Marchal-Bornert** [comment]
@sergeivolodin Of course ! Windows 10, Mozilla Firefox 88.0.1
