### ISSUE TITLE
Feature request: Improve web browser extension

### ISSUE THREAD

**Issue by ksallee** [tournesol-app/tournesol#1313]
Right now, in the browser extension:

- It recommends videos already recommended and watched (isn't there a way to know they've been watched?)
- It doesn't show the date of the video

But most of all, I feel that contributing right now is "hard": If you want to offer new content, you have to go to tournesol, paste two URLs and compare two videos.

It would be awesome and game changing if the browser extension added a collapsible card under the video with the same criteria as "compare", but only for one video.

I kind of don't understand why we can only compare videos, and not set the same sliders for a single video.

And if it was under your video in youtube, it would make contributing way, way, way easier so you would have suddenly way more relevant content.

I watch interesting videos all the time but it's hard to choose 2 to compare...

**Comment by aidanjungo** [comment]
For the the first point, we already planned to work on that but not so simple to implement.
The second point is a good suggestion, I will create a separate issue about it.

For the rest, we know it could be difficult to compare video, but we think it also why it brings more information and all our algorithms are based on comparisons, it would be complicated to change that now. We discuss that in the [FAQ](https://tournesol.app/faq#why_compare_two_by_two) and get a lot of comments about that on our [Discord server](https://discord.com/invite/TvsFB8RNBV)
