### ISSUE TITLE
Tournesol extension prevents from using `mousemove` events on chrome

### ISSUE THREAD

**Issue by nterol** [tournesol-app/tournesol#1326]
# Issue
I installed the extension two weeks ago on Chrome, but I did not realize until now the extensions prevents me from registering a callback on the `mousemove` event.
I have uninstalled the extension and callbacks from `mousemove` works just fine. 

# How to test
On Chrome, install the extension. Open the console on any page and try to set callback on `mousemove`event. 
```js
const callback = (e) => { 
    console.log("mouse move", e);
}

window.addEventListener("mousemove", callback);
```

Nothing is printed.

**Comment by GresilleSiffle** [comment]
Hello @nterol 

Thanks for creating an issue. 

Do you reproduce the issue on any other browser?

The code snippet works for me on:
- Firefox 102.7
- Chromium 109

I still need to test on Chrome.

**Comment by GresilleSiffle** [comment]
By the way, which version of Chrome do you use?

**Comment by amatissart** [comment]
I can't reproduce the problem either, be it on Firefox or Chromium.
@nterol Could you give more details about your configuration: which OS, browser version, other extensions installed?  

It sounds unlikely to be related to the implementation of the Tournesol extension specifically, as it's supposed to be active only on youtube.com and tournesol.app, and doesn't interfere with mouse events.  
Could it be a temporary issue with your browser? Have you tried to reinstall the extension afterwards?

**Comment by nterol** [comment]
My bad, I don't think I targeted the right extension. I've tried several times installing and reinstalling the extension, it has no effect on `mousemove`event. I'm closing this, sorry for the disagreement.
