### ISSUE TITLE
Update the Mehestan implementation of scaling contributors

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1351]
Mehestan does not use "supertrusted users" anymore, which used to be members of the core team. 

Now it is called "scaling contributors". There are up to 100 scaling contributors which are, among the contributors who have a trust score higher than 0.1, those who have the highest number of comparisons.

There are 3 problems in the implementation :
- the term "supertrusted" is still used to refer to scaling contributors, which leads to confusions
- `ratings_properties` still only picks the 6 contributors that have the highest count of comparisons. It should pick the 100 contributors with a trust score higher than 0.1 and the highest count of comparisons.
- `get_supertrusted_users` is filtering on pretrusted users instead of users with a trust score higher than 0.1. And it does not look up-to-date anyway.

**Comment by amatissart** [comment]
Yes, I worked on updating this implementation this week. A PR will be opened shortly.
