### ISSUE TITLE
Design a donation page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#138]
We are looking into having two kinds of means of donations: Paypal (#119) and PostFinance's "Checkout Flex" (https://github.com/tournesol-app/tournesol-meta/issues/14).

It would be great if contributors were given the option to donate anonymously or under their name.
Then, we can have a list of top donators, a list of recent donators and a random list of donators.

Maybe some donation statistics as well. Maybe this should appear in the contributor's profile?

**Comment by aidanjungo** [comment]
Something simple and easy to use like that could be nice.

![Capture d’écran 2021-05-21 à 21 33 01](https://user-images.githubusercontent.com/53896963/119189354-40c07d80-ba7c-11eb-9fc8-5d8c9b8ee284.png)
