### ISSUE TITLE
Where editing the profile data was not clear

### ISSUE THREAD

**Issue by F-Marchal-Bornert** [tournesol-app/tournesol#14]
When I reached my profile page the first time, I struggled to understand where I could add data on my profile : the profile was empty so I didn't understand that the green button with the pen was about editing my date, I thought it was for editing something else. 

Suggestion : A simple frame surronding the profile and the two buttons to interact with will do the job I think.

**Comment by sergeivolodin** [comment]
@TheDuckWhisperer @lenhoanglnh what do we do?

**Comment by TheDuckWhisperer** [comment]
I can offer a quick solution to the direct problem, won't be much work, mainly some button alterations I think. 
The alternative is that we put it in the backlog until I get to redesigning the profile page 😅
