### ISSUE TITLE
[front] Add `preferences` in the settings menu

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#1409]
It could look like that, we could start with just the implementation of the existing setting to change the number of comparison before a video is removed from the rate later list, then we could have other category when we add other settings.

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/53896963/222921464-92f84b14-29e6-4f20-b4c4-5fc0ce0077c4.png">

**Comment by GresilleSiffle** [comment]
Before implementing this task I think we have a decision to take.

Some settings are poll specific like the rate-later auto remove, and others are global. What is the target UX?

I see several options:

**(a)** Display all settings of all poll in the same preferences page. For a more user friendly experience, the page could display several forms (one per poll for now).

**(b)** Display only the global settings and the settings related to the current poll in the preferences page. If the users want to change the settings of several poll they will have to use the poll selector to access the different forms.

I have a preference for the option **(b)** as it makes the UI more simple:
- no duplicated field in the same page (auto-remove will be displayed for each poll)
- less forms in the same page

**Comment by GresilleSiffle** [comment]
Here is a draft of the UI:

Global settings, like the the configuration of the UI or the tutorial could be on the same page, just before the poll specific form.

![capture](https://user-images.githubusercontent.com/39056254/231127819-0c33d6c9-b959-468b-9b26-f61d93e00d67.png)
