### ISSUE TITLE
front: Add page with General terms and conditions

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1452]

**Comment by GresilleSiffle** [comment]
### Context

We want to clearly inform the users of what actions they can and can't do on https://tournesol.app and what response they should expect from the Tournesol Association. For this we want to create a Terms of Service page (Conditions Générales d’Utilisation in French).

With this first version of our Terms of Service we want to specifically address the user accounts removal and the videos removal. 

### Specification 

**(a)** Create a a Terms of Service page. See the structure below.

**(b)** In the Join us page replace 

```
I have read and agree with the privacy policy.
```

By

```
I have read and I agree with the Terms of Service and the Privacy Policy.
```

Both Terms of Service and Privacy Policy should be links.

**(c)** Add a Terms of Service link in the footer, in the More section, above the Privacy Policy.

### Terms of Service structure

Let's start with a very short version.

Target structure:

```
1. Definitions
2. Account Terms
3. Acceptable Use
4. Moderations
5. Cancellation and Termination
6. Changes to These Terms
```

#### Definitions

The first section should be a Definition section that will briefly define the formal vocabulary we will use to remove all ambiguities.

Expected definitions are:
- Account 
- Agreement
- Association, Association Tournesol
- User, You, Your
- Web Site, Platform, The Service 
- Entity, Video, Content
- Polls

#### Account Terms

The second section could be Account Terms explaining:

- we expect users not robots
- users must provide a valid email address
- users must provide a public username that doesn't promote violence etc. etc. ()
- age limit to participate?

#### Acceptable Use

The third section could be Acceptable Use:
- Users can add Videos from YouTube
- Users can compare Entities in different Polls
  - Comparison are expected to be made at a human pace 
    - no more than 40 per minutes
    - no more than X per day

#### Moderation

The fourth section could be Moderation:

- The Association may make user accounts inactive
  - explain under which conditions 
- The Association may delete user accounts 
   - explain under which conditions 
- The Association may delete videos
  - explain under which conditions 

#### Cancellation and Termination

Users can delete their account.

#### Changes to These Terms

Changes are documented in the repository of the source code. Users will be notified by [...] 

Example: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#b-account-terms

**Comment by lfaucon** [comment]
Let's get this done.

I agree with (a), (b), and (c). 

> explain under which conditions

Can it be something such as "goes against the the Terms and Condittions or the spirit of the Tournesol project" ?
