### ISSUE TITLE
[back][infra] feat: send an alert on Discord when the nbr of account using a trusted domain passes a threshold 10, 100, 1000...

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1454]

**Comment by GresilleSiffle** [comment]
### proposition

The thresholds could be:
- 10
- 50
- 100
- 200
- 400
- 800
- 1000
- 2000

**Comment by GresilleSiffle** [comment]
To complete the proposition above:

We can create a new Django mgmt command:

```sh
python manage.py watch_account_number --since 2023-01-01 
```

It will count the number of account created and grouped by trusted domain name since `2023-01-01` and `timezone.now()`. If omitted it will count between today 00:00 am and `timezone.now()`.

**Comment by GresilleSiffle** [comment]
The command is merged, now we need to configure Ansible.
