### ISSUE TITLE
Adding comunidadunir.net to the list of trusted domains. 

### ISSUE THREAD

**Issue by samuelnihoul** [tournesol-app/tournesol#1455]
I think my university is not in the list of trusted domains. The domain is comuninadunir.net. Uni name is Universidad Internacional de la Rioja.

**Comment by lfaucon** [comment]
The domain does not seem to be in our database, there is probably no account which uses such email domain. If you change it on your account we will be able to approve it.

**Comment by aidanjungo** [comment]
You can use Discord for this kind of question it is easier for discussion and generally we use Github issues more for our planned tasks and future developments
