### ISSUE TITLE
[front-end] misleading trust system explanation

### ISSUE THREAD

**Issue by samuelnihoul** [tournesol-app/tournesol#1461]
In the account page, the part about trust is misleading and is not informative at best. I think we should explain better what are the trust mechanics so people know better what is best for them to do relatively to seeking pretrust, vouchers or giving vouches.

**Comment by aidanjungo** [comment]
Hello @samuelnihoul, could you start this kind of discussion on Discord, it is more appropriate and easier to talk about it. If we decide the issue must be tackle we will take care of creating the issue.
