### ISSUE TITLE
Account validation by nil-cost credit card transaction

### ISSUE THREAD

**Issue by AlbericC** [tournesol-app/tournesol#147]
As an alternative method for proof of personhood, a credit card payment of zero amount 

Limitations: 
- people may have several credit cards, 
- people may use "disposable" card identification (available from some banks, ironically, as a security feature)
- it may induce an extra cost for running the service. 

Advantages: 
- Tournesol may retain some bank ident as a hash to prevent multiple uses of the same account 
- proves the user is of age (used by some adult sites already)

**Comment by lenhoanglnh** [comment]
We're brainstorming it here: https://discord.com/channels/760540475139817472/835565851046182922/846664719905194014
(we use Discord for brainstorming, github for more established issues/solutions 😊)

**Comment by AlbericC** [comment]
my bad. you mat close and ditch this issue then
