### ISSUE TITLE
Analyze how the Tournesol scores evolve over time

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#1474]
It would be interesting to see how the rating pattern of videos evolves over time. For example, there might be phenomenons of regression to the mean, positive feedbacks (bias to give a better rating to videos already well rated). It may vary with the topics, and the contributors. This could also give some insights on the real uncertainty : does the score converge steadily, or is it rather chaotic ?

To do this, we need to filter the comparisons based on the date, and re-execute Mehestan each time. This may benefit from solving #1370 first.

**Comment by aidanjungo** [comment]
I think this issue could be merge with #1421

**Comment by glerzing** [comment]
Yes indeed. I close this one.
