### ISSUE TITLE
Shift the zero

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#1490]
Right now, a non-scored video is set to be a median video (as its score is 0, and 0 is roughly the median score).
A safer approach would be to consider that a non-scored video is, say, in the bottom 5%.
This would correspond to saying that the score 0 corresponds to the score of the 5 percentile.

It seems that this can be approximately fixed by a few lines, when computing the global scores:
https://github.com/tournesol-app/tournesol/blob/main/backend/ml/mehestan/global_scores.py#L311

Namely, we first estimate the bottom 5-percentile of scaled individual scores. Denote ```tau_hat``` this  estimate.
Then before aggregation by QrMed of scaled individual scores, we subtract ```tau_hat``` to all scaled individual scores.

I think that this does not conflict (too much) with the rest of the algorithm (but please test it!).

This corresponds to fixing Equation (14), page 14: https://arxiv.org/pdf/2211.01179.pdf

**Comment by amatissart** [comment]
I run a few experiments on the branch [`shift-zero-experiments`](https://github.com/tournesol-app/tournesol/tree/shift_zero_experiment), with variations on 4 parameters:

![runs](https://github.com/tournesol-app/tournesol/assets/4726554/469f1cf3-f680-4ff9-8d10-d684bcd6e2db)

**Comment by amatissart** [comment]
For reference, with the current algorithm as existing on `master`:

* individual scores:
![indiv_scores_](https://github.com/tournesol-app/tournesol/assets/4726554/7d9b2284-6786-4e23-8952-789048806199)

* global scores:
![global_scores](https://github.com/tournesol-app/tournesol/assets/4726554/7c0d6318-1294-4ef1-8d9f-98cd7a0ecac3)
