### ISSUE TITLE
Fill all the data in the editing form from the "My profile" page : a nightmare

### ISSUE THREAD

**Issue by F-Marchal-Bornert** [tournesol-app/tournesol#15]
I filed all my data **four times** before a clear success. 
Every time I unfortunately clicked outside the form it desapeared and removed what I did. 
I did a bit of research (to be sure if I'm agnostic or atheist for exemple), I mindlessly scrolled with the scroller of the window, I clicked by mistake outside the form... 
And have to start all over again. It was very frustrating, especially because it's a pretty exhaustive form and there is no way to validate it without scrolling its bottom. 

Suggestion : Unfortunately I do not know how to solve this issue.

**Comment by lfaucon** [comment]
@sergeivolodin Sounds like we could save the state of the form as the state of the outer component so that it is not reinitialized when closing/re-opening the form

**Comment by sergeivolodin** [comment]
@F-Marchal-Bornert sorry for the inconvenience. One solution would be to only allow exiting the form with the button below, and another one would be to save the form data even when it's closed.

@lenhoanglnh @lfaucon which one do you think is the best one?

**Comment by lenhoanglnh** [comment]
Let's go with the simplest solution (disabling closing the form by clicking outside of it). 
I think that the whole interface should be optimized later on (and Chris is probably working on it).

@lfaucon do you know how to do this. It'd be best for @sergeivolodin to focus on the backend (and especially the learning algorithm 😋).

**Comment by lfaucon** [comment]
Yes I could do it!
