### ISSUE TITLE
[front] the component `<ComparisonSeries>` is unmounted during a state update

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1519]
- see on `main` at https://github.com/tournesol-app/tournesol/commit/ba3d8f03cfc141218233cb57926c5d30179bd082
- this doesn't seem to impact the user experience.

---

### How to reproduce

- start the `dev-env`
- open the front end home page
- open the browser JavaScript console
- click on the button Compare the videos in the Contribute section
- see the following message in the console

```
Warning: Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application.
To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

**expected**

No error in the console.

### Details

This may be caused by the component `<ComparisonSeries>`, which is instantly unmounted for users having more than 4 comparisons or having skipped the tutorial.

```javascript
      const alts = await getAlts();
      if (alts.length > 0) {
        setAlternatives(alts);
        return alts;
      }
```

**Comment by abhiram11** [comment]
Looking into this
