### ISSUE TITLE
[ext] feat: allow the users to explicitly select their favourite recommendation languages

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#1560]
### Context

Currently there is no friendly and documented way for the users to change their preferred languages for the recommendations they get in the browser extension. The only available way is tricky and requires the users to change the value of the Languages search filter in the Tournesol website's recommendations page.

We want the users to be able to explicitly configure the recommendations languages directly in browser extension.

### Technical specifications

The extension should provide a way, like a page, to update the non-authenticated users' preferences. Those preferences will be saved in the extension storage. 

**(a)** A layout should be proposed and agreed by the core team. 

**(b)** For authenticated users, the extension should use directly the user settings returned by the back end's API.

Expected scenarios:

**(c)** A non-authenticated user with preferences defined in the extension logs in. In this case only the preferences returned by the back end's API should be used.

**(d)** An authenticated user with preferences defined in the back end's API logs out. In this case only the preferences retrieved from the extension storage, if any, should be used.

**(e)** When no preference has been configured, authenticated and anonymous users should get recommendations matching their browser's languages.

**Comment by lfaucon** [comment]
Suggestions: This settings page could be accessible with (1) a button on the top-right extension action menu and (2) top right of the recommendation panels on home & search page, a very discreet link "change languages" that also opens the same page

Other comments:
- The same styled iframe as the embedded comparison or login could look good, or opening the settings page in a separate tab would also work. How/Where do we plan to implement this interface?
- Should the search on/off be moved to this same place?

**Comment by GresilleSiffle** [comment]
> Suggestions: This settings page could be accessible with (1) a button on the top-right extension action menu and (2) top right of the recommendation panels on home & search page, a very discreet link "change languages" that also opens the same page

+1

**Comment by GresilleSiffle** [comment]
Here is how the preferences will look like with the `option_ui` mechanism of browser extensions.

(I didn't work in the fields style yet.)

![capture](https://github.com/tournesol-app/tournesol/assets/39056254/83be4cd6-4119-43bf-9a2a-290a403c81eb)

We can open this UI either in a new tab, or directly in the extension manager. I like the extension manager option because it allows the users to fully manage the extension from one tab, they don't need to open a new tab for their preferences.

Regardless of our choice, the method `browser.runtime.openOptionsPage()` provides a direct access to the user preferences.
