### ISSUE TITLE
Preview image from Tournesol is ignoring the uploader

### ISSUE THREAD

**Issue by sintaz1992** [tournesol-app/tournesol#1586]

**Comment by sintaz1992** [comment]
Thanks @GresilleSiffle. it is related to recommendation preview. When you click on [this link](https://api.tournesol.app/preview/_recommendations/?uploader=MinuteEarth&unsafe=true) it should show the videos from MinuteEarth uploader, however on the preview it shows all the videos (ignoring the provider).  Here is the screenshot:
![image](https://github.com/tournesol-app/tournesol/assets/44063058/e1cb039e-9cc2-4107-9a73-17ba41626423)

**Comment by GresilleSiffle** [comment]
That's clear, thank you very much :+1:
