### ISSUE TITLE
The Firefox add-on replaces the "Save" button on the YouTube interface

### ISSUE THREAD

**Issue by Mutusen** [tournesol-app/tournesol#1587]
Hi, I'm using the add-on (version 3.0.2) in Firefox 113.0.2 on Linux Mint. The buttons "Rate later" and "Rate now" that appear under the video on YouTube replace the "Sample", "Save" and "…" buttons of the default YouTube interface.

Without the add-on:

![image](https://github.com/tournesol-app/tournesol/assets/47037331/53fdd561-42a7-466c-8d77-e28d03907ead)

With the add-on:

![image](https://github.com/tournesol-app/tournesol/assets/47037331/70e3af7d-9d77-4c49-8de3-fa47e842f3ce)

**Comment by GresilleSiffle** [comment]
Thanks for the report @Mutusen 

We are going to fix this bug soon, thanks for your patience.

**Comment by GresilleSiffle** [comment]
@Mutusen we are going to deploy a fix for Firefox and Chrome.

The update should be automatically available in a couple of hours. In case your Firefox browser is configured to not automatically update the add-ons, you'll need to update the Tournesol extension manually by clicking on Check for Updates in the extensions settings page (accessible at the address `about:addons`).

![cap](https://github.com/tournesol-app/tournesol/assets/39056254/bd583833-d48c-41f7-a07e-83c731022444)
