### ISSUE TITLE
Fix details page generating too many requests

### ISSUE THREAD

**Issue by sergia-ch** [tournesol-app/tournesol#159]
If a non-existent video is entered in the details field, the page generates requests indefinitely to get the statistics

Example:
1. Go to https://tournesol.app/details/I0GImBIkA7Y
2. Open developer tools, see many requests to /api/v2/video_ratings/video_rating_statistics/?limit=100&video__video_id=I0GImBIkA7Y
![image](https://user-images.githubusercontent.com/1012270/119737328-620bda00-be7f-11eb-82a2-8568b1e1e796.png)

This makes the server CPU usage go to >100%
![image](https://user-images.githubusercontent.com/1012270/119737229-3ab50d00-be7f-11eb-887b-4242bd4b8675.png)

Related: #137

**Comment by sergeivolodin** [comment]
I blocked the IP from which it was coming from @lenhoanglnh @lfaucon
