### ISSUE TITLE
"video contents from Youtube"  display a misleading number of videos

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#16]
The number of "video contents from Youtube" that is displayed on the home page is misleading, it correspond to all the videos added to Tournesol (2896), but most of them are probably only in people "rate later" list. The real number of video that have been rated at least once, seems to be 1033 for now.

**Comment by sergeivolodin** [comment]
Added API

```json
GET /api/v2/statistics/view/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "certified_experts": 406,
    "total_experts": 1704,
    "pairwise_comparisons": 5276,
    "videos": 3390,
    "min_score": -0.157348558306694,
    "max_score": 3.1103892326355,
    "weekly_active_ratings": 784,
    "n_rated_videos": 2197
}
```

**Comment by aidanjungo** [comment]
Thanks, looks perfect!  
To solve this issue, do I need to just replace in "tournesol/frontend/src/components/Home.js ":

<h1 className={classes.statistic}>{getStatistic('videos')}</h1>

by:
<h1 className={classes.statistic}>{getStatistic('n_rated_videos')}</h1>

If yes I can do it, if it is more complicated I let @lfaucon  do it.  :)

**Comment by lfaucon** [comment]
Correct @aidanjungo

**Comment by lfaucon** [comment]
This is Done. Thanks @aidanjungo
