### ISSUE TITLE
[front] feat: Add options to share on social media from video cards/analysis page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1606]

**Comment by amatissart** [comment]
@ShinseiNova It looks good to me :+1: 
As the "Compare" button is no longer present in the video card, I think it would make sense to remove all actions buttons from the video card on this page, and move the "Rate Later" action on the line of blue buttons.

**Comment by lfaucon** [comment]
Looks good!

Some thoughts:
(A) are there easy integrations with other social media than Twitter?
(B) can we have both a "copy link" and a "copy social media message"?
(C) I think I would prefer keeping the action buttons on the card, even if they would be duplicated. I think this helps users learn about them and use them well

**Comment by lfaucon** [comment]
My opinion:
- LinkedIn: Yes.
- Facebook: Yes.
- Instagram: Maybe. I guess that sharing on Instagram requires an image? Is it feasible to re-use the video preview image for this? 
- Tiktok: No. Because of the negative aspects of Tiktok.

Only doing the integration if the corresponding social network has a simple API for it.

I think the team would agree, please raise this as a discussion point in one of our next weekly.

**Comment by GresilleSiffle** [comment]
Facebook and LinkedIn would be nice. I have the same feeling about Instagram and TikTok.

**Comment by lfaucon** [comment]
Closing, future work on this will be done on #1800  and #1801
