### ISSUE TITLE
3: [back] feat: automatic reminder after account creation

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1677]
Add automatic reminder mechanism for user who create an account and did 0 comparisons (or less than 2?) after 10 days.
Ensure also that analytics measure how many users are brought in from these automatic reminders

**Comment by GresilleSiffle** [comment]
I see several options to make this feature fit in our Terms of Service, some of them would require an update. We can discuss about it during the next meeting.

I propose to not deploy anything until we all agree.

**Comment by lfaucon** [comment]
(based on team discussion)
to-do:
- [ ] update T&C to say that there will be one email sent as reminder 10 days after account creation (we consider that this is a minor change, so we do not need to notify everyone about hte T&C change, because only new users are impacted)
- [ ] implement daily service that selects accounts created 10 days ago and send the emails
