### ISSUE TITLE
[front] refactor: rework tutorial

### ISSUE THREAD

**Issue by ShinseiNova** [tournesol-app/tournesol#1682]
Remove the `DialogBox` display from the current tutorial.
Trigger the tutorial only when nb comparisons < tuto length.
 
Design a `Tips` component to replace the `DialogBox` behaviour. We want to display it in place of the collective goal.
It should have a `step` value to increment after each comparison.
We can switch to a previous tip but not to one we haven't "unlocked" yet.

Before the last comparison we want a `DialogBox` to thank the user and announce the end of the tutorial.
The tutorial should then be folded and we can bring back the collective goal.

template : 
![image](https://github.com/tournesol-app/tournesol/assets/89401728/626f6451-64ae-49f8-a4c7-c36e44a7196d)

**Comment by GresilleSiffle** [comment]
> Before the last comparison we want a DialogBox to thank the user and announce the end of the tutorial.
The Tips should then be folded and we can bring back the collective goal.

We keep nearly the same mechanism as the one we have today to display the dialog box. If there is a dialog box matching the current step, we display it, else we don't display anything. This will allow us to display a dialog box at any time in the comparison series. For the tutorial it will be at the final step.

**Comment by GresilleSiffle** [comment]
I updated the title to show that we are only refactoring the tutorial, not the whole onboarding process from the sign up to the end of the tutorial.

**Comment by GresilleSiffle** [comment]
> Trigger the tutorial only when nb comparisons < tuto length.

Instead of checking the `series` query parameter.

**Comment by GresilleSiffle** [comment]
> Design a Tips component to replace the DialogBox behaviour. 

They contain a paragraph but can be expanded to see the full content (which should match the content of the old dialog boxes).
