### ISSUE TITLE
[front] feat: Add tabs "they cite us" and "in the media" next to "Our Publication" and "Student Works" on home page.

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1704]
## They cite us

Volition Learning: What Would You Prefer to Prefer?
Mohamed Lechiakh, Alexandre Maurer (2023). Artificial Intelligence in Human-Computer Interaction.
https://link.springer.com/chapter/10.1007/978-3-031-35891-3_35

Algocratie : Vivre libre à l'heure des algorithmes
Arthur Grimonpont (2022). Actes Sud.
https://www.actes-sud.fr/catalogue/sciences-humaines-et-sociales-sciences/algocratie

The human cost of ethical artificial intelligence
James Ruffle, Chris Foulon, Parashkev Nachev (2023). Brain Structure and Function.
https://link.springer.com/article/10.1007/s00429-023-02662-7

Model reports, a supervision tool for Machine Learning engineers and users
Amine Saboni, Mohamed Ouamane, Ouafae Bennis, Frédéric Krat (2021). European Conference on Electrical Engineering & COmputer Science.
https://hal.science/hal-03410903/

Identify ambiguous tasks combining crowdsourced labels by weighting Areas Under the Margin. 
Tanguy Lefort, Benjamin Charlier, Alexis Joly, Joseph Salmon (2022). ArXiV.
https://arxiv.org/abs/2209.15380

## In the media

Les grands modèles de langage : quels risques ? Échange avec Lê Nguyên Hoang.
Paroles de (2023). Conseil national du numérique
https://cnnumerique.fr/paroles-de/les-grands-modeles-de-langage-quels-risques-echange-avec-le-nguyen-hoang

Researchers turn to crowdsourcing for better YouTube recommendations
Kyle Wiggers (2022). VentureBeat.
https://venturebeat.com/ai/researchers-turn-to-crowdsourcing-for-better-youtube-recommendations/

AIs are out of (democratic) control
Lê Nguyên Hoang (2023). SwissInfo.
https://www.swissinfo.ch/eng/ais-are-out-of--democratic--control/48427358

Podcast - Comment dompter un algorithme ?
Andreia Glanville, Huma Khamis (2023). RTS Micro-sciences.
https://www.rts.ch/info/sciences-tech/14000339-podcast-comment-dompter-un-algorithme.html

L’intelligence artificielle : outil de domination ou d’émancipation ?
Julien Hernandez (2023). Polytechnique Insights.
https://www.polytechnique-insights.com/tribunes/digital/lintelligence-artificielle-outil-de-domination-ou-demancipation/

L'AI contre la désinformation
Adrien Zerbini (2022). RTS Ça n'a pas de science !
https://www.rts.ch/la-1ere/programmes/cqfd/11969483-ca-n-a-pas-de-science-.html

Les Lumières à l'ère du numérique.
Rapport de la Commission (2022).
https://www.elysee.fr/emmanuel-macron/2022/01/11/remise-du-rapport-de-la-commission-bronner

AI thinkers grapple with modern war 
Kate Kaye (2022). Protocol Enterprise. 
https://www.protocol.com/newsletters/protocol-enterprise/ai-russia-ukraine-zendesk-momentive

«L’industrie de l'information est probablement la plus dangereuse pour la société»
Grégoire Barbey (2022). Heidi.News.
https://www.heidi.news/cyber/l-industrie-de-l-information-est-probablement-la-plus-dangereuse-pour-la-societe

Tournesol : l'algorithme d'utilité publique qui a besoin de vous ! 
Julien Hernandez (2021). Futura Sciences.
https://www.futura-sciences.com/tech/actualites/intelligence-artificielle-tournesol-algorithme-utilite-publique-besoin-vous-87301/

## Additional task

Add the AI-Stat paper in our own publications: https://proceedings.mlr.press/v206/el-mhamdi23a.html

**Comment by amatissart** [comment]
Done in #1698 and #1705
