### ISSUE TITLE
Nanzan University as a trusted email domain

### ISSUE THREAD

**Issue by sunoc** [tournesol-app/tournesol#1766]
Hi,

A student at Nanzan University, Japan, I would appreciate if the email domain of my institution was recognized as trustworthy.

Here are the concerned domains:
@m.nanzan-u.ac.jp
@nanzan-u.ac.jp

The email addresses are either in the form of [familyname][initial]@domain or [studentnumber]@domain.
Each address is managed by the school directly and linked to either an individual student or staff member in the university, so the mass creation of fake ID seems unlikely.

Many thanks for the great work on Tournesol!

Cheers,
Vincent

**Comment by aidanjungo** [comment]
Hello,

I just checked and there is no user using this email domain for now in the database.
We check new email domain when a user use it for the first time and then it is in the list.

**Comment by GresilleSiffle** [comment]
Thanks for you words @sunoc 

As Aidan said, the email domains will automatically become candidate when they are used by at least one user. Remember that at any time you can update your email address if you have a Tournesol account: https://tournesol.app/settings/account

Thank you!
