### ISSUE TITLE
Opening a link without being logged in should redirect to login page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#18]
If I open `https://tournesol.app/rate/zKNlPrEQwPY/SorIEgajNd0` without being looged in it gets stuck at "Loading ...". Instead the optimal behaviour would be to redirect to a page like `home`or `login` but keeping arguments `?next=/rate/zKNlPrEQwPY/SorIEgajNd0` so that the user can be brought back where he/she wanted to go once logged in

**Comment by lenhoanglnh** [comment]
Maybe the optimal behavior would rather be to let the contributor rate the video, but when they click on "submit", we open a new tab telling them to login/signup?

**Comment by lfaucon** [comment]
I agree @lenhoanglnh. 

In terms of implementation these can be complementary:
- From *any* url that requires login. Redirect to login, then redirect to desired url
- For a small set of specific urls implement an improved behaviour as described in Lê's comment

**Comment by lenhoanglnh** [comment]
Let's do point (1) in general, and point (2) for the rate page.
