### ISSUE TITLE
Login failed.

### ISSUE THREAD

**Issue by kyrios123** [tournesol-app/tournesol#1849]
Hello,

I just created & activated an account on tournesol.app but then when I try to log in, I keep on getting the below error. I did also reset my password but it didn't help.
So I tried to create another account using a different e-mail address (I know it's bad), and I got exactly the same problem.

![image](https://github.com/tournesol-app/tournesol/assets/7815316/e99773ec-0221-4bf2-b20c-b9348154f92b)

Is there a problem with the account activation or something ?

Thank you !

**Comment by GresilleSiffle** [comment]
Hello @kyrios123 

Sorry for the issue. I checked the sign-up and activation process and I haven't find any problem for now.

If you have a Discord account, you can join us here https://discord.com/invite/WvcSG55Bf3 and ask for help in the bug-report channel. I'll be there to help.

**Comment by GresilleSiffle** [comment]
I see that your account is correctly activated. It could be a problem with the password, or with your client configuration.

**Comment by kyrios123** [comment]
Thanks @GresilleSiffle 

I tried in private browsing mode to make sure no add-on interfere with the site.
I did copy paste the password from a notepad to make sure there is no typo and since I did this for 2 different accounts, I don't see what else I could try. :(

**Comment by GresilleSiffle** [comment]
I see. Do you confirm that filling the reset password form doesn't change anything?

https://tournesol.app/forgot

**Comment by kyrios123** [comment]
> Do you confirm that filling the reset password form doesn't change anything?

Yes I do. I tried quite a few times now to reset the password (it seems to work but then when I try to log in I still keep on getting the "_Login failed._" message).

**Comment by GresilleSiffle** [comment]
Ok, do not hesitate to join Discord if you can, we will fix the problem.
