### ISSUE TITLE
Create append-only database and create link to download public database

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#19]
See: https://wiki.tournesol.app/index.php/Tournesol_main_database
The link should then be given on the home page #7.

**Comment by sergeivolodin** [comment]
Export only comparisons for which two videos are public

**Comment by lenhoanglnh** [comment]
Even if 'show my profile' is false, export 'username'.
If 'show my profile' is true, export 'First name', 'Last name', 'Title', 'Bio', 'Degrees', 'Expertises'.
If 'show online presence' is true, export 'Website', 'Linkedin', 'Youtube', 'Google scholar', 'Orcid', 'Researchgate', 'Twitter'.

Do NOT share demographic data.
