### ISSUE TITLE
[front] feat: Create a page for Tournesol Live

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#1908]
Similar to the page for Tournesol Talks

**Comment by GresilleSiffle** [comment]
I was wondering, should we have a new page "events" displaying at the same time both Tournesol Talks and Live? This could be quite useful to see the calendar of all future events without having to navigate between two pages.

The pages Talks and Live can still be useful to display specific information like the Talks subscription button.

**Comment by GresilleSiffle** [comment]
Idea of possible layout on mobile devices:

![capture](https://github.com/tournesol-app/tournesol/assets/39056254/acbdcf1f-b0e9-4ee9-9ac7-3d50303f99f4)
