### ISSUE TITLE
License Tournesol's data

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#204]
Tournesol seeks to make the database partially public based on contributor choices. This is done to support research on ethical articficial intelligence and to support companies to develop responsible algorithms.

Links to previous discussions and information:
- https://github.com/tournesol-app/tournesol-backend/issues/23
- https://github.com/tournesol-app/tournesol-meta/issues/82#issuecomment-894692435
- (french) https://fr.wikipedia.org/wiki/Donn%C3%A9es_ouvertes#Licences_open_data

**Comment by amatissart** [comment]
@lfaucon Now that #360 is merged, should we add an indication about the database license on the home page, before it can be published?

**Comment by lfaucon** [comment]
Done with https://github.com/tournesol-app/tournesol/pull/364
