### ISSUE TITLE
Donation system on the platform

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#206]
I talked to Ramon Pineda, from our bank PostFinance, this morning.
We focused essentially on three points:
1. Having a credit card for the association, which will be necessary in general for online payments outside of Switzerland (github, servers, domain names...).
2. Opening an account in EUR to receive donations from across Europe without the fees of currency change.
3. Opening a [Checkout Flex](https://www.postfinance.ch/en/business/products/e-commerce/postfinance-checkout-flex.html) account, which is PostFinance's built-in solution for online payment/donation.

I think that points (1) and (2) are definitely needed.
Point (1) and (3) can be obtained using the [launch package](https://www.postfinance.ch/fr/entreprises/besoins/creation-jeune-entreprise/offre-lancement/apply.html), which comes with discounts. In particular, the license for (3) is free for 6 months. We can also test (3) and terminate it after a month, free of charge.

I have already asked for (2), and I think we should go with (1) and (3) too. WDYT?

**Comment by lfaucon** [comment]
Added Utip https://tournesol.app/about/donate
