### ISSUE TITLE
Set-up continuous deployment

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#208]
Includes main website and browser extensions

**Comment by GresilleSiffle** [comment]
Maybe we can re-discuss about how we handle packages upgrade in production.

See https://github.com/tournesol-app/tournesol/issues/398#issuecomment-1004640886

**Comment by lfaucon** [comment]
The team feels that improving the deployment process does not seem to be one of our current objectives. We like the current manual step for deploying main (e.g. we want to check some things before a deployment / delay the deployment / update settings before deploying)

However we may want to improve how we handle secret management.

Closing for now, but will keep track of the quality of our code to production process.
