### ISSUE TITLE
docs: Logs on Grafana

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#209]
Acceptance criteria:
- Provide a short documentation Grafana functionalities, including which logs are stored and available
- Ensure all logs are available on grafana, if not, document which are missing and why

**Comment by GresilleSiffle** [comment]
**to-do**
- [ ] document how to access logs in case of problem
- [ ] document how to access Grafana, explain what kind of problem it can solve

**Comment by aidanjungo** [comment]
closed by https://github.com/tournesol-app/tournesol/pull/1264
