### ISSUE TITLE
Throttling on sensitive requests

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#211]

**Comment by lfaucon** [comment]
@GresilleSiffle may recommend to use Fail2Ban https://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by lfaucon** [comment]
We may limit to 1000 request per minute

100 request per minute seems to be an intense user behaviour (note that submitting a comparison generates about 10 requests)

**Comment by amatissart** [comment]
Fail2Ban may be useful to protect the servers against attacks outside of the application itself (eg. ssh, etc.).  
To define limits on specific requests or actions in the API, I think it would be much easier to use the throttling mechanisms provided by Django Rest Framework: https://www.django-rest-framework.org/api-guide/throttling/#throttling

**Comment by GresilleSiffle** [comment]
That's true, **DRF Throttling** and **fail2ban** are two different things.

The DRF Throttling will help to limit the number of requests a client can make. If I understood correctly, once the limit is reached, the clients get HTTP errors. It works at the application level, and reduce the load without banning anyone. For me, it's the first level load smoothing we should use in the application.

fail2ban is able to any log file, ssh, auth, or even http, and determines, according to a configured threshold, if successive failures must be transofrmed into an IP ban. It works at a system level. It's goal is to limit intrusion, DDoS, by banning IP addresses for a specific duration. In my opinion, fail2ban is also a first level of protection we should use in the system.

We could create two different tasks to adress those different issues.

last note: I think with fail2ban we can create specific rules ( jails ) that scan for successive login attempts through the login form, and ban the IP addresses that don't act like humans. We can suppose a human would have used the `Forgot your password?` page after a certain amount of attempt, or won't have filled a hidden form field in the HTML.

**Comment by GresilleSiffle** [comment]
About DRF Throttling.

If we have different endpoints with different "cost", we can use different throttling configuration.

For instance, downloading the public dataset is an heavy operation, and could have its own throttling scope.

```python
class PublicDatasetThrottle(AnonRateThrottle):
    scope = 'public_dataset'
```

and in the project `SETTINGS.py`

```python
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'tournesol.throttles.PublicDatasetThrottle',
        # ...
    ],
    'DEFAULT_THROTTLE_RATES': {
        'public_dataset': '10/min',
        # ...
    }
}
```

Endpoints making calls to the YouTube API could have they own scope too.

Other endpoints could have a default global scope.

Example ( values are arbitrary )

```python
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'tournesol.throttles.PublicDatasetThrottle',
        'tournesol.throttles.YouTubeApiThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # anonymous and authenticated users are authorized to make up to 1800 requests per hour 
        # i.e. 1 per 2 seconds per user
        'anon': '1800/hour',
        'user': '1800/hour',

        # requests to the YouTube API have a cost, so are more limited ( twice less than the default )
        # i.e. 1 per 4 seconds per user
        'youtube_api': '900/hour',

        # building the public dataset has a strong cost, so a even more limited
        # i.e. 1 per 10 seconds
        'public_dataset': '10/min',
    }
}
```
