### ISSUE TITLE
Separate application code from tests

### ISSUE THREAD

**Issue by sandre35** [tournesol-app/tournesol#221]
Currently, test files are located inside the views folder.
Largely, we should separate the logic of the application from the part of the code that is not necessary for the functioning of the backend.

**Comment by lfaucon** [comment]
I am not sure what would be everyone's opinion on this.

I thought it is good practice to keep small unit tests next to the code that it is testing. In the other hand, integration and end-to-end tests would be in the root repostory.

What's your opinion @jstainer-kleis @amatissart  @GresilleSiffle  ?

**Comment by GresilleSiffle** [comment]
This is indeed a good question and I think the Django project has several answers.

**(1)** This is currently the recommended way of testing apps by the Django documentation see:
https://docs.djangoproject.com/en/4.0/intro/tutorial05/

**(2)** It also allows apps to be independent and self-contained, bringing features **and their related tests** to the project, encouraging developers to create non-couple code.

**(3)** The command `python manage.py test` provides an API to  control which tests are run (I personally use a lot this API). This is very handy to save time when we want to focus only on a specific app.

- `python manage.py test ml` -> run all the tests of the `ml` app
- `python manage.py test core` -> run all the tests of the `code` app
- etc.

For all these reasons, I think we should keep the tests in the Django apps, as they are now.

**Comment by lfaucon** [comment]
Let's keep our current structure for tests! Thanks all for the discussion and propositions
