### ISSUE TITLE
Define a public description 

### ISSUE THREAD

**Issue by sandre35** [tournesol-app/tournesol#241]
The file `index.html` in the folder public of frontend is empty. We could provide a description for people who are mentioning tournesol, and also appears in the research criterias of google

**Comment by aidanjungo** [comment]
@lfaucon Should it be a short or a long description?

I would propose:

- if short: 
`Collaborative Content Recommendations`

if long:
`Tournesol is an open source platform which aims to collaboratively identify top videos of public utility by eliciting contributors' judgements on content quality. We hope to contribute to making today's and tomorrow's large-scale algorithms robustly beneficial for all of humanity.`

**Comment by aidanjungo** [comment]
Also I would like to change that logo, but I don't know where I have to change it...

![logogoogle](https://user-images.githubusercontent.com/53896963/143683745-22c27e28-394f-443d-b47e-508184d0db37.png)

**Comment by lfaucon** [comment]
I can look for how to change the logo. I'd say long description
