### ISSUE TITLE
Investigate Tournesol extension integration with Dismoi

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#249]
Dismoi provides an extension which notifies users when content on wbesite are misinformation (https://www.dismoi.io/). They have 4000 users.

Acceptance criteria:
- Look up how Tournesol could be a provider of notifications/warnings for Dismoi
- If we choose to initiate contact with DisMoi

**Comment by aidanjungo** [comment]
We never receive an answer for our registration and from their [GitHub repo](https://github.com/dis-moi/extension) it seems is not very active anymore... Maybe we can close the issue.
