### ISSUE TITLE
Understand the source of score variance

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol#25]
Within a few days, the top videos change drastically.

Test if the total scores are optimal given the rest using gd and binary search.

**Comment by lenhoanglnh** [comment]
Note that Huber loss depends on a parameter δ. 
We have one Huber loss per video v rated at least once by contributor n on quality criteria q.
For this Huber loss, let's set δ = 1 / (number of ratings of v by n on q).

(it's probably suboptimal and I need to research how to do better, but it seems like a good first guess to smooth the loss function without harming it)

**Comment by sergeivolodin** [comment]
@lenhoanglnh what's the status on the Huber loss? is it still something we need to try? Please add to #88 if so

**Comment by lenhoanglnh** [comment]
No
