### ISSUE TITLE
Mark users contributing between 2 calls to ml algorithm

### ISSUE THREAD

**Issue by OscarVlld** [tournesol-app/tournesol#252]

**Comment by lfaucon** [comment]
Can you better describe what this is about?

- What is the current state?
- What is the desired state?
- Why is it important?

**Comment by OscarVlld** [comment]
- current state : the ml algorithm can infer which users contributed based on if they have more ratings than before, but this is not perfect (users can edit a rating, remove one and add one, ...)
- desired state : when called, the ml algorithm is provided a boolean for each user, True meaning that the user contributed after the previous call to ml
- important because : it allows to compute only what is needed, saving time and computational ressources

This is not a priority for now.
