### ISSUE TITLE
[backend] feat: Mechanism for updating Video metadata

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#277]
Displayed on Tournesol and may be outdated:

- Title
- Number of views
- Channel uploader

Missing metadata due to late implementation:

- duration

We seek to have a longterm solution that should work with our limit of 10k API calls per day, when we may assume 1k new videos added by users per day.

**Comment by aidanjungo** [comment]
also it would be good to add the duration to video which have nothing in this field

**Comment by amatissart** [comment]
As highlighted by @aidanjungo, only the metadata that are directly provided by Youtube API should be updated.  
Other data that may have been updated manually (such as "language") should remain unchanged.

**Comment by sandre35** [comment]
I also added the name of channel uploader as metadata to refresh
