### ISSUE TITLE
Improve home page UX

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#278]
- [x] Structure Home page sections. In order: Title, Description, Extension, Comparison, About, Donate
- [x] Links to ABOUT and DONATE in the footer of the side bar
- [x] Hosting service and link to the privacy policy in the footer of the side bar
- [x] Colors: Select blue from Figma's button for secondary color instead of green
- [x] Colors: ContentHeader background should be the same as sidebar
- [x] Colors: remove grey backgrounds to white

**Comment by aidanjungo** [comment]
See with recommendations from Polyconseil UX designers
