### ISSUE TITLE
(style) Display number of views as human readable

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#288]
We currently show on our interface numbers like `21520041 views`. I recommend that we use a common library to display human-readable numbers so that it looks like `21.5M views` or `21,520,041 views` (like on Youtube)

**Comment by amatissart** [comment]
An external library may not even be necessary, thanks to [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat):
```js
> new Intl.NumberFormat('en', {
  notation: "compact",
  compactDisplay: "short",
  maximumSignificantDigits: 3,
}).format(21520041);
'21.5M'
```

**Comment by glerzing** [comment]
![numbers_format](https://user-images.githubusercontent.com/47578089/142781986-75c0175e-ed9f-41d9-8727-64ac1268c7dd.png)

4 possible solutions : 
- use Number Format => '21.5M views'
- use toLocaleString('en-US') => '21,520,041 views'
- use toLocaleString('fr-FR') => '21 520 041 views'
- use toLocaleString() => dependant on the browser's language (may cause problems for tests, but adapted to each browser. See https://www.techonthenet.com/js/number_tolocalestring.php for more details.).


What do you prefer ?

**Comment by lfaucon** [comment]
I'd recommend option 1 or 4. We aim to be international to option 3 may look funny.

The first option would have the advantage that numbers are display with a approximately fixed length which would simplify the layout.

Option 4 seems more diverse and inclusive 🌻

**Comment by amatissart** [comment]
I agree that a compact format looks preferable, also because showing an exact number is not relevant as the view count stored in our database may not be up-to-date.

As far as I can see, `NumberFormat()` and `toLocaleString()` are very similar, they both accept advanced formatting `options` and an optional `locales` parameter (the current browser language is used by default). `Intl.NumberFormat` just makes easier to  build and reuse the same formatter.

**Comment by glerzing** [comment]
Sorry to be that long, I have reinstalled all my environment on a Ubuntu dual boot. My frontend is ok, and I'm currently trying to import the backend datasets.

**Comment by lfaucon** [comment]
Not to worry @glerzing Take the time you need. The worse that may happen is that tasks and priorities change. I'll let you know in this case
