### ISSUE TITLE
Reduce time spent in end-to-end workflow

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#290]
Some ideas on how to optimize:
 * Cache docker image used by "backend-dev-api" (~ 2minutes to build)
 * Optimize `yarn start` in frontend (~1min30 to start)

**Comment by samuelnihoul** [comment]
Is this for production only?

**Comment by amatissart** [comment]
Some improvements have been implemented in https://github.com/tournesol-app/tournesol/pull/1413

Feel free to reopen, if you think other optimizations should be applied.
