### ISSUE TITLE
Add logos and links to social media accounts

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#293]
I don't think it was design in the Figma but maybe it could be at the bottom of the sidebar...
I think we should have link to:

- Github
- Discord
- Twitter
- LinkedIn
- YouTube

**Comment by lfaucon** [comment]
This was mostly done already. We have a lot of links on the bottom of the sidebar.

I would recommend either:
1. Consider this task done and close it
2. We want more links, let's restructure a bit the about page and add a Useful Links" section

**Comment by GresilleSiffle** [comment]
I'm wondering if a page footer would help here.

As a user, it would be useful for me to see the social links directly on the page, without the need of unfolding the side bar. The positive effects I see:
- the links are more visible and discover-able
- we are not limited by the side bar size and we can add as many links as we want ( for instance we could have in the page footer a section social links / another about legal mentions / another containing links about the association, etc. )

As an example, here is the Django footer

![capture](https://user-images.githubusercontent.com/39056254/168560085-11551c99-011c-4b6d-b110-6b805650e763.png)

I think we could have a section Follow us:
- with the twitter account of the project
- the twitter bots
- the YouTube channel
- maybe the YouTube channel of Lê?

We could have a section Support Us:
- with all funding links available

Maybe a section Privacy:
- with a link to the privacy policy
- maybe more

We can even go fancy by adding more "cool" links, like the scientific publications related to Tournesol, etc.

**Comment by GresilleSiffle** [comment]
> How it should be displayed on mobile

The items of the grid will stack on top of each other, following the usual flex pattern. We can see an example here:

![capture](https://user-images.githubusercontent.com/39056254/168656415-cda64cd8-a18d-4f49-b559-009967cdc3a2.png)

> How it should interact with the sidebar (bellow it, next to it...)

I don't know yet. I think the footer could be considered as part of the page to ease the development, and thus should be covered by the side bar on mobile, and pushed by the side bar on desktop.

**Comment by GresilleSiffle** [comment]
Try to move all links from the side bar's footer to the footer.

Maybe remove the column Tournesol's polls

**Comment by GresilleSiffle** [comment]
Here is a draft I retrieve on my computer.

The bullet points could be removed, and more space could be added between items to "relax" the UI.

On mobile, we could force the lists to be on top of each other.

### ideas

![capture3](https://user-images.githubusercontent.com/39056254/190180311-7a414076-a24b-4681-9b56-c4686711dd22.png)

![capture](https://user-images.githubusercontent.com/39056254/190180328-f44aaaa9-2b8f-42a5-9493-eddc9f95f351.png)

**Comment by GresilleSiffle** [comment]
### preview

![screencapture-localhost-3000-faq-2022-09-21-17_21_07](https://user-images.githubusercontent.com/39056254/191544691-705d8ad5-0019-478b-80d3-097e27860ca9.png)
