### ISSUE TITLE
Search phrase improvements

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#31]
Search phrase should be a bit less rigorous. For example, when trying to find videos from a specific Youtube channel with the Search phrase, one missing letter leads to not finding any correlated results.

![searchphrase](https://user-images.githubusercontent.com/53896963/110084471-4ae1b280-7d90-11eb-87a8-dd0a55a5fc77.png)

Also, videos which match the search phrase with the channel name or video title should maybe be prioritized over videos which match it with the description or other meta data.

![shearch_order](https://user-images.githubusercontent.com/53896963/110085433-639e9800-7d91-11eb-812a-eeb70ab7be29.png)

**Comment by sergeivolodin** [comment]
Can use Google search API?

![image](https://user-images.githubusercontent.com/1012270/118803828-25027f00-b8a4-11eb-9d98-0e159d8be107.png)

**Comment by lenhoanglnh** [comment]
Yes go for it :)
