### ISSUE TITLE
Video id field can be used for search

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#32]
When a user types a word in the video id field, we run a search (like on the search page).
The first three results are proposed. If the contributor clicks on one proposed answer, then the video id of the clicked answer is entered in the video id field.
<img width="651" alt="Screen Shot 2021-03-19 at 20 30 19" src="https://user-images.githubusercontent.com/10453308/111833090-ef680680-88f1-11eb-9fbe-e94d7414d4a9.png">

**Comment by sergeivolodin** [comment]
Use search_tournesol API view
