### ISSUE TITLE
[frontend] feat: Comparisons on HomePage when not logged in.

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#327]
- Videos from the top 10 of recently rated are automatically loaded (fallback to all time if there are not enough)
- Comparison on Home page: If not logged in button "Submit" says "Login to submit"
- Comparison on Home page: If not logged in Random from last month and automatically detect browser's language

**Comment by GresilleSiffle** [comment]
- [ ] display the comparison feature on the home page, for non logged user
  - [ ] videos are from the top 10 recently rated
  - [ ] fall back to video of all time if there are less than 2 videos in the recent top 10
- [ ] display the `Login to submit` button
- [ ] save somewhere the comparison data when the button is clicked
- [ ] after the user has activated its account, send the comparison to the API

## Questions

**(a)** Do we want to also display the comparison feature in the Home page for logged users?

Display this feature will act as an invitation to rate the recent videos, to collect more judgment. Could this be a virtuous and engaging feature? I personally like it.

**(b)** What does "recently" mean? Rated last week? Rated last month?

There may be more inertia in the videos proposed if we use the month, but the risk of displaying bad quality videos is lower.

## Technical specifications

A comparison made by an anonymous user can either be saved in the browser local storage or in the back end's database in a pending state or a dedicated table. The two options have a different level complexity, let's explore what is best. Currently I think the local storage is better, because less complex ( no new database table, no new API endpoints, no concept of anonymous comparison ).

**Comment by lfaucon** [comment]
> after the user has activated its account, send the comparison to the API

Maybe "send the comparison to the API & redirect the user to the comparison page for editing the comparison if she/he feels the need"

> (a) Do we want to also display the comparison feature in the Home page for logged users?

Why not. I find your justification convincing

> (b) What does "recently" mean? Rated last week? Rated last month?

Let's have the same default as for the Recommendations page! Maybe let's implement it in a way such that when the recommendation page is changed so will the home page comparison page.

> A comparison made by an anonymous user can either be saved in the browser local storage or in the back end's database in a pending state or a dedicated table. The two options have a different level complexity, let's explore what is best. Currently I think the local storage is better, because less complex ( no new database table, no new API endpoints, no concept of anonymous comparison ).

I recommend frontend side for simplicity and also for not collecting non-logged-in user data.

> The <ComparisonPage> component will need to be refactored so that two different pages can include the comparison interface without duplicating all code related to the usage of the <VideoSelector> components.

Yes, fully agreed

**Comment by GresilleSiffle** [comment]
Thanks for all Louis.

I'll surely have more questions the more I explore the subject. Here is new ones:

**(c.1)** I've isolated the comparison UI in its own component (see the pull request #524), and as before the component dynamically updates the URL by adding the parameters `videoA` and `videoB`. Do we want those parameters in the Home page?

These parameters will always be there for logged and non-logged users, making the address of the Home page longer, and coupled with a comparison. People sharing the address will also share the comparison at the same time.

I don't have a strong opinion on this. If I was about to decide, I'll choose to not have the video parameters on the Home page. It's still possible to add a little button or link to allow users to copy the proper comparison link, leading to the comparison page, and share it.

**(c.2)** Do we want the users to be able to refresh the

**Comment by amatissart** [comment]
> **(c.1)** I've isolated the comparison UI in its own component (see the pull request #524), and as before the component dynamically updates the URL by adding the parameters `videoA` and `videoB`. Do we want those parameters in the Home page?
>
>These parameters will always be there for logged and non-logged users, making the address of the Home page longer, and >coupled with a comparison. People sharing the address will also share the comparison at the same time.

IMHO the comparison component should not be the primary component on the home page, and I would not add these parameters in the URL. 
Nevertheless, it could be useful to allow access to the comparison page (e.g from a link shared outside of Tournesol) even if the user is not logged in, using the same "login to submit" mechanism.

> **(c.2)** Do we want the users to be able to refresh the videos on the Home page, by using the two circular refresh buttons?

I would recommend to make as few modifications as possible on the selectors (also to avoid conflicts with  #485).  
The only requirement is probably to extend the algorithm to select a random video to be selected according to different criterias even if the user is logged in.  
Or to hide this button, if this makes things simpler in the short term.

**Comment by GresilleSiffle** [comment]
### very WIP research on the Home page

Here is how the Home page looks like, by just using the new `<Comparison>` component. The comparison actually works for logged users. In fact, I start to think that it will ease the development process to first add the comparison UI only for logged users, then step by step, refactor the code to make it work with anonymous users.

It opens new UX/UI questions:
- How do we want users to be invited to compare? In the screenshot I propose to use a title.
- Where do we want to put the comparison UI? higher on the page?

![screencapture-localhost-3000-2022-02-02-11_03_50](https://user-images.githubusercontent.com/39056254/152133572-bf6018af-4507-48a3-82db-2481672472a6.png)

**Comment by lfaucon** [comment]
> The comparison actually works for logged users. In fact, I start to think that it will ease the development process to first add the comparison UI only for logged users, then step by step, refactor the code to make it work with anonymous users.

I like this option

**Comment by lfaucon** [comment]
Comments about the component on the screenshot. I imagine it could simplify the on-boarding of new users to remove many parts of the comparison interface.

May remove:
- Video ID selector
- Information about num of comparisons (which is 0 for non-logged users)
- Public/private selector (because nothing goes to db yet for non-logged users)
- Optional criterias

**Comment by lfaucon** [comment]
TODO:
- [ ] Brainstorm to agree on User Experience for the "comparison on home page"-feature now that we have implemented the "tutorial" option.

**Comment by lfaucon** [comment]
Decision on this feature is to keep the PR which became stale but to keep some of the code contributions in the branch 
 `327-comparison_on_home`. We may re-use the code written to work on this but only after having more clearly defined the user experieince on the home page. Currently, our most valuable target for the home page is to include the Tutotorial for new users.

**Comment by lfaucon** [comment]
Done
