### ISSUE TITLE
(feat) Multiple languages on the frontend

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#329]
- [x] Implement the internal mechanics required to support multiple languages
- [x] Translation to French
- [x] Language selector in top bar
- [x] Clear plan about how translation occurs when open source contributors implement a frontend feature
  #494 
- [ ] #455
- [x] Email verification and Password reset emails should be translated

**Comment by lfaucon** [comment]
Updated TODO list with translation of emails sent to users

**Comment by amatissart** [comment]
The last item will be specified in its own issue #455. I am closing.
