### ISSUE TITLE
Pagination component should say comparison instead of video on "My comparisons" page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#346]
The pagination on the comparison page shows "videos" instead of "comparisons". 

![Screenshot 2021-12-07 at 20 20 21](https://user-images.githubusercontent.com/8818081/145092658-9f89b29f-7ca1-4cd4-b6a7-8870baf31612.png)

`src/component/Pagination.tsx` component should accept a props `itemType` that has `"videos"` as default value
The component in `src/pages/comparisons/ComparisonList.tsx` should use this props with the value `"comparison"`

**Comment by YJ-Hannah** [comment]
Hi @lfaucon, we are a group of university student new to open source development. We would like to work on this issue for a course project, is this issue still open for contribution?

**Comment by FabienRoger** [comment]
Hi! I'm also a newcomer, and given that remi-bovin hasn't responded so far, I'm will tackle this one!

**Comment by lfaucon** [comment]
Thanks @FabienRoger. It's very welcome
