### ISSUE TITLE
feat: API endpoint to download public data

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#355]
The goal of this feature is to enable anyone to download Tournesol's public data.

## Backend
Implement an API endpoint `exports/comparisons/` similar to `users/me/exports/comparisons/` except that comparisons are not filtered for the users, but all comparisons that are public are returned.  
Note that a comparison is public if both videos are tagged as public by the user (i.e `is_public` is True in the `ContributorRating` objects related to each video).

## Frontend 
Add a section at the bottom of the Home page with the text:

>Contributors on Tournesol can decide to make their data public. You may download the dataset of all data publicly available. We hope this important data will prove useful for researchers on ethics of algorithms and large scale recommender systems.

and with a yellow button that downloads the csv file from the `exports/comparisons/` endpoint. You may use a similar implementation as for the component `ExportAllDataForm`

**Comment by anikeith22** [comment]
Working on the frontend component of this issue.
