### ISSUE TITLE
feat: personnal Recommendations from Tournesol's users

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#363]
A page to receive recommendations based on the public ContributorRatingsCriteriaScores of a user rather than the VideoCriteriaScores

- [x] #540
- [x] #543
- [x] #1003
- [x] #1056
- [x] safe/unsafe reco. differ between collective and public personal page
  - see issue: https://github.com/tournesol-app/tournesol/issues/1036
  - see PR: https://github.com/tournesol-app/tournesol/pull/1037
- [ ] (optional) By default this page should only show public data, but if a user is looking at the recommendation page of him/herself, then an option could appear to also show videos rated privately.

**Comment by lfaucon** [comment]
@glerzing I proposed this ticket to you, but as I see you probably have not started, @farnots will start to work on the first step #540

**Comment by glerzing** [comment]
ok, he can start to work on the first step.

**Comment by glerzing** [comment]
I don't think I would be efficient in the frontend part, I would prefer to specialize in the backend, if there is enough work in the backend.

**Comment by lfaucon** [comment]
During discussion on Friday 25 March we agreed that this page should reuse the layout of the "Compared items" page

**Comment by sigmike** [comment]
> A page in user's profile "Your public recommendations" with a link to be shared.

The user's profile looks like that:
![image](https://user-images.githubusercontent.com/28259/160675674-a241e43b-366d-417a-a933-069e4ef2a94c.png)

You want a link after the username input that leads to the user's personal recommendations page?

**Comment by lfaucon** [comment]
In our discussion last Friday we suggested that the personnal  page would instead be incorporated into the already existing "Compared Items" page

A few simple first steps may be:
- [ ] Enable sorting by personnal scores the list of compared videos
- [ ] Display the personnal scores on this page next to the VideoCards

**Comment by sigmike** [comment]
I did that in https://github.com/tournesol-app/tournesol/pull/732.

**Comment by sigmike** [comment]
The changes were made in #732 and disabled in f600f19c7 saying that it should be discussed first.
