### ISSUE TITLE
(bug) Reset pagination on search term

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#378]
We should do something similar to the following when a term is searched:

```TypeScript
    // Reset pagination if filters change
    if (key !== 'offset') {
      searchParams.delete('offset');
    }
```

**Comment by sintaz1992** [comment]
it seems the problem is fixed: I reseted the offset onSubmit() in search:
 const onSubmit = (event: React.SyntheticEvent<HTMLFormElement>) => {
    event.preventDefault();
    searchParams.delete('search');
    searchParams.append('search', search);
   ----> searchParams.delete('offset');
    history.push('/recommendations/?' + searchParams.toString());
  
  };
