### ISSUE TITLE
"Load new video" proposes lists of videos

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#38]
The list of lists of videos may include "Best fit", "Missing ratings", "Recently rated" and "Discovery".
This list of lists should be optimized.
The algorithms determining the videos of each list have yet to be designed.

<img width="769" alt="Screen Shot 2021-04-26 at 22 37 00" src="https://user-images.githubusercontent.com/10453308/116147366-ee3fab80-a6df-11eb-9196-db35acd1e34a.png">

**Comment by sergeivolodin** [comment]
@lenhoanglnh can you provide algorithms (pseudo-code) to compute "Best fit", "Missing ratings", "Recently rated" and "Discovery"?

**Comment by sergeivolodin** [comment]
@lfaucon I think it should be implemented in the backend, otherwise the mobile version would have to implement it's own sampling... And it's faster and more efficient in the backend as well

**Comment by lfaucon** [comment]
It necessarily has some frontend aspect if we want to show a list of videos to the user and giving letting the user select which video to use for comparison. -> Both some frontend and backend
