### ISSUE TITLE
Non-certified contributors also in home page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#40]
The home page should also display both the number of certified contributors and the total number of contributors.
Also, the number of ratings displayed on the home page should be the total number of ratings (both from certified and non-certified contributors).

(@sergeivolodin we probably need an API from the back end to get these statistics)

**Comment by aidanjungo** [comment]
From the API it would also be nice to have access to things like:
- Number of new users (last week, last month)
- Number of comparison per days
- Number of users from each certified mail domain

In order to be able to show some of these data on a Tournesol page.

**Comment by lenhoanglnh** [comment]
https://wiki.tournesol.app/index.php/Global_statistics

**Comment by sergeivolodin** [comment]
Added to API:

```json
GET /api/v2/statistics/view/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "certified_experts": 406,
    "total_experts": 1704,
    "pairwise_comparisons": 5276,
    "videos": 3390,
    "min_score": -0.157348558306694,
    "max_score": 3.1103892326355,
    "weekly_active_ratings": 784,
    "n_rated_videos": 2197
}
```

**Comment by lfaucon** [comment]
@sergeivolodin We are trying to move away from the wrod expert, so as a good rule of thumb, let's use "user" instead of "expert" for new feature

What is "weekly_active_ratings" ? Is it a number of ratings or a number of user?

**Comment by lenhoanglnh** [comment]
Actually, let's use "contributor" instead of "expert" :)
