### ISSUE TITLE
MUI: use `sx` prop instead of inline `style`

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#401]
After the upgrade to MUI v5, `sx` should be usable on most components:
https://mui.com/system/the-sx-prop/

**Comment by ramprakashram** [comment]
@amatissart Can I take up this issue ??

**Comment by amatissart** [comment]
@ramprakashram Ok! In addition to removing `style`, it could also be a good opportunity (optionally) to remove some of the custom CSS classes defined via `makeStyles` (now legacy in MUI) when they are not reusable.

**Comment by ramprakashram** [comment]
Sure @amatissart

**Comment by ramprakashram** [comment]
Hi @amatissart , need a clarification, for places where `makeStyles`  have been used , I should convert them into `sx` correct ??

**Comment by ramprakashram** [comment]
Sure @amatissart , Thanks.

**Comment by ramprakashram** [comment]
I have raised the PR for the changes. Please review it @amatissart
