### ISSUE TITLE
fix(extension): Don't refresh whole page when changing language options

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#404]

**Comment by glerzing** [comment]
I suggest also setting a refresh button (⟳)  to display new suggestions without changing the language.

**Comment by lfaucon** [comment]
Agreed!

A similar option we may have:
I saw recently on Youtube a line of recommendations similar to our "Tournesol's recommendations" but sharing official COVID-19 information. This banner had a extend-collapse option. I thought we could do the same: showing 4 videos recommended by Tournesol, but give the option to extend to find 12 more recommendations.

**Comment by FabienRoger** [comment]
I have applied the first two suggestions, but not the last one: I would need someone to modify the backend to ask for more than 4 videos at a time.

**Comment by FabienRoger** [comment]
Oh, thank you, I did not see that the request was processed by the extension itself!

If I'm not mistaken, my pull request hasn't been accepted yet, but you can find the branch here:
https://github.com/FabienRoger/tournesol/tree/404-refresh-recommandations
and the commits are available here:
https://github.com/tournesol-app/tournesol/pull/410/commits

**Comment by FabienRoger** [comment]
I just added the expand button!

**Comment by FabienRoger** [comment]
> Thanks for the quick fix. I am interested by your modifications, since I also work on the extension (#349), but I don't see your branch. Can you push it to origin?
> 
> Also, I think you can modify the number of requested videos in background.js, lines 58 to 62.

I think the quick and a little dirty appraoch do to #349 is to do one request per language and then use code just like line 60-62 to concatenate them. It isn't scalable if tournesol adds many languages, but the scalable solution requires modifying the backend.

**Comment by lfaucon** [comment]
@FabienRoger The backend has already been modified. You can request recommendations with multiple languages. For example: https://api.tournesol.app/video/?language=en,de for English and German

You can look at the docs for the api here: https://api.tournesol.app/docs/
