### ISSUE TITLE
Tournesol recommendations on YouTube home page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#42]
To design an appropriate algorithm, it would be useful to know what kind of data we could use.
In particular, can we obtain some information about the user's YouTube account?

**Comment by lfaucon** [comment]
We can:
- know about all their Tournesol data
- know other videos that are on their home page

WE could also update the extension to pull more data but it would require extra permissions tht don't look good

**Comment by sergeivolodin** [comment]
We can add their Google account, and then we can use APIs

**Comment by sergeivolodin** [comment]
@lenhoanglnh @lfaucon should this be in the extension repo? or, are some changes to the backend necessary as well?

**Comment by lenhoanglnh** [comment]
Yes.
