### ISSUE TITLE
Create a menu for language options

### ISSUE THREAD

**Issue by FabienRoger** [tournesol-app/tournesol#428]
Put the language options for recommendations and interface languages in a proper menu, so they are in a place where a description of what they are is put:
- you can select multiple accepted languages for recommanded videos
- you can select one language for the extension interface (although only one language is available in the extension for the moment)

**Comment by GresilleSiffle** [comment]
We created new issue with more technical details here https://github.com/tournesol-app/tournesol/issues/1560

I'm going to close this one.
