### ISSUE TITLE
[extension] feat: Search on youtube displays recommendations from Tournesol's search

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#431]
Display 1-2 results of Tournesol's search on Youtube search page similarly to recommendations added to the home page.

Youtube's search:
![Screenshot 2022-01-09 at 13 33 04](https://user-images.githubusercontent.com/8818081/148682407-78e561d5-bf52-48bd-98e3-73dcf80d0226.png)

Notes: 
- Use language preference of the user
- Example search: https://api.tournesol.app/video/?search=climate
- If no video are returned from Tournesol nothing should be displayed
- Elon 5 years ago is really not great on Climate Change
- Let's try to implement it without too much code duplication

**Comment by lfaucon** [comment]
Initial work was done in PR: #440 
But branch is stale and we wil need to extract code from it to recover the work done.

**Comment by GresilleSiffle** [comment]
After having discussed with Adrien and Aidan:
- we diplay 3 videos in a single column, the top 3 of the back end answer (all time recommendations with the search parameter)
- the title is click-able and redirects to the YT video
- the thumbnail is click-able and redirects to the YT video

Following task:
- display Recommended by Tournesol inside the yellow background on both the YT homapage and the search results
- display a button `View more` after the search results (aligned to the right) that redirects the users to the Tournesol recommendations with the same search parameter

**Comment by lfaucon** [comment]
> use English only for now

What does it mean exactly? Why is it difficult to get languages the same way as for the home page?

**Comment by OoIwazaruoO** [comment]
> 

No no, I mixed English and French in the display by mistake it was just a fix to do. I can see how it can be misinterpreted I correct it.
