### ISSUE TITLE
[frontend] bug: Login button disabled when not logged in

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#432]
Right after clicking updating Chrome which restarted the browser I was stuck with a disabled Login button (I'm not sure everything was working right before).

I was not seeing anything in the network tab. 

I got unstuck by clearing the localStorage (forgot to look at what was inside...).

My guess is that the login state was persisted while waiting from an answer from the server but restart happened before login completed. I was stuck when re-opening the tab probably because of this intermediary state when no response would come.

Chrome Version 97.0.4692.71 (Official Build) (arm64)

![Screenshot 2022-01-09 at 13 31 00](https://user-images.githubusercontent.com/8818081/148691193-84bea244-1645-454e-8225-1d17f0786911.png)

**Comment by amatissart** [comment]
Fixed by #505
