### ISSUE TITLE
[back] make the `GET /users/me/comparisons/` view answer with video metadata

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#436]
to be reviewed by @amatissart and @lfaucon 

---

**context**

The front end `/comparisons/` page is able to make up to 21 requests to the back end, and up to 21 more when the buttons previous and next are pressed. 

This is currently not a problem, but as we have defined throttle rates in the back end it currently forces us to configure a relatively high  number of maximum requests allowed per minute (1200) just to comply with the current comparison views of the back end.

**proposition**

Make the `ComparisonListApi` and `ComparisonListFilteredApi` view answer with the metadata of each video returned (this is mainly a serializer refactor)

**Comment by lfaucon** [comment]
Sounds good to me
