### ISSUE TITLE
[back] upgrade `pylint` to the latest 2.x version

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#448]
... and upgrade the configuration file `.pylintrc`

An up-to-date configuration file can be generated with the command:
```shell
pylint --generate-rcfile > .new_pylintrc
```

It must then be configured with the settings of the old `.pylintrc`.

See: https://pylint.pycqa.org/en/latest/whatsnew/index.html

**Comment by glerzing** [comment]
I am undecided in particular about `missing-class-docstring`: do you think it should be ignored by PyLint if a class has no docstring? I have started adding some of the docstrings, but there are also classes for which it doesn't really look useful (for module docstrings, I just deactivated the warning).
