### ISSUE TITLE
[front] Default for language of videos based on the selected language for video recommendations

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#455]
Probably, select by default the list of language available in the user's `navigator.languages`.

Persist modifications to the language filter by the user in localStorage

Open questions:
- How to handle URL sharing?
- Include language option when requesting video for reco

**Comment by amatissart** [comment]
* when recommendation is displayed: the "language" filter is added in the URL dynamically if it's not already present
* to select this language dynamically:
  * use the value stored in localStorage
  * or select a list of languages derived from `navigator.languages` 
* when user clicks on the language filter: the filter value is persisted in localStorage
