### ISSUE TITLE
The language button should be on the landing page

### ISSUE THREAD

**Issue by FabienRoger** [tournesol-app/tournesol#463]
Currently, the language icon is not in the collapsed navigation bar
![image](https://user-images.githubusercontent.com/15524303/149633595-b6a8e504-acd8-44aa-a638-26c27c5971ef.png)

If find it weird that it is hidden inside the navigation bar.

The "language icon" could at least be visible in the collapsed bar, like that

![image](https://user-images.githubusercontent.com/15524303/149633648-1089add3-2ed1-4c4a-86fc-cede343fb058.png)

Or be added on the top left of the page.

**Comment by ramprakashram** [comment]
Can i take up this issue ??

**Comment by amatissart** [comment]
> Can i take up this issue ??

Sure. Ideally we would probably expect that clicking on the collapse button would display the language selector (without opening the menu).

I am not sure about the amount of changes it will require though, as the `<Footer>` component is currently not rendered at all when the drawer is closed. A good start could be to move the `<LanguageSelector/>` outside of the Footer component. 

Don't hesitate to ask, if questions arise during the implementation.

**Comment by ramprakashram** [comment]
Sure @amatissart thanks.
