### ISSUE TITLE
[all] add a general `LICENSE` or `COPYING` file at the root of the repository

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#479]
I'd like to request a review from @lfaucon @amatissart 

---

**context**

We currently use a mono-repository architecture, and each sub-project potentially have its own license.

If someone discovers our mono-repository there is no indication of the licenses, neither in a dedicated file at the root, nor in the `README.md`.

The only way for someone to get information about our software is to browse each sub-project one by one.

**proposition**

**(1)**

Use a non-standard* disclaimer, but a disclaimer still, in a file called `LICENSE` at the root of the repository:

```
# Licenses

In order to share knowledge and creativity efficiently, the Tournesol project has chosen
to distribute its software under the terms of different licenses.

## GNU Affero General Public License

- [backend][backend/LICENSE]
- [frontend][frontend/LICENSE]

## CC0 1.0 Universal

[docs/architecture-decision-log][docs/architecture-decision-log/LICENSE.md]
```

* GitHub doesn't seem to be able to handle several license files in the same project, but it doesn't seem to be a problem.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**(2)**

Mention the newly created file at the end of the main `README.md`.

**Comment by lfaucon** [comment]
I fully aggree with propositions (1) and (2)
