### ISSUE TITLE
Analyze theoretically and explain pedagogically our current learning algorithm

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#48]
This can be a research paper. Feel free to reach out if you want to help 😊

**Comment by sergeivolodin** [comment]
Maybe apart from theory we should add some experimental analysis?

- It's much easier to model the 51% attacks we fear than theoretically prove stuff I think... We just compute the gradient of the total score w.r.t. the new rating, for example, and go in the direction that damages the score the most
- We can add noise to the ratings and see at which point the algorithm starts to output wrong videos
- We can vary the number of ratings we train on, and see how the results change

This would give us some sense of what to expect theoreticaly

For the pedagogical explanation, I think a Javascript demo with the crawfishes and pebbles is the best option...
