### ISSUE TITLE
[extension] refactor: usage of deprecated `addListener` instead of `addEventListener`

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#480]
**context**

These is three lines where the extension uses the deprecated `MediaQueryList.addListener` instead of `EventTarget.addEventListener`.

If this is not a choice, and if we do not want to support older browsers, we can refactor the code.

Here are the two functions, and the compatibility tables:
- https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

https://github.com/tournesol-app/tournesol/blob/3521ec43bc30c2faf8039c287ccc8f5ecb0e6dde/browser-extension/background.js#L20

https://github.com/tournesol-app/tournesol/blob/3521ec43bc30c2faf8039c287ccc8f5ecb0e6dde/browser-extension/background.js#L44

https://github.com/tournesol-app/tournesol/blob/3521ec43bc30c2faf8039c287ccc8f5ecb0e6dde/browser-extension/background.js#L127

**Comment by amatissart** [comment]
These examples are not using `MediaQueryList.addListener` but methods specific to web extensions:

* `menus.onClicked`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onClicked
* `runtime.onMessage`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage
* `webNavigation.onHistoryStateUpdated` : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onHistoryStateUpdated

So `.addListener()` seems to be correct here.

**Comment by GresilleSiffle** [comment]
Oh I see!

My editor was not able to resolve `chrome.contextMenus.onClicked` and supposed that `onClicked` was a `MediaQueryList.addListener`.

Sorry, " unreliable & misleading "
