### ISSUE TITLE
[front] Add something to indicate the a filter is active

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#484]
On the recommendation page, the user should able to see when a filter is active (especially now that "monthly filter is active by default). A small blue dot next to "Filter" could be a visual solution.

**Comment by amatissart** [comment]
After discussion with @GresilleSiffle, a possible implementation would be to wrap the button content with a   
[`<Badge color="secondary" variant="dot">`](https://mui.com/components/badges/#dot-badge)

And this badge would be visible when at least 1 of the filter parameters is present in the URL query (`date`, `language`, `uploader`, or one of the criterias).
