### ISSUE TITLE
[meta] discuss and plan the Tournesol models refactor

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#509]
In order to make Tournesol able to work with different kinds of content, and not only YouTube videos, we would like with @amatissart to submit to discussion the following technical specifications.

## new database design

We propose three new models to replace the current `Video` model.

**(1) tournesol.models.Entity**

> other names we have thought of: candidate, alternative, content, scorable, comparable, ratable...

(I personally like `Candidate` more than `Entity` and more than the rest.)

This model will represent an entity that can be compared with other ones, using a specific set of criteria.

We forecast this new model will have the following attributes:
- `id` a unique identifier managed by the database
- `uid` a unique identifier that will be used by the API to reference the entity
- `type` a foreign key to `EntityType`
- `metadata` a JSONB PostgreSQL field holding all metadata related to the entity

The new `uid` field will replace the current `video_id` field of the `Video` model. It could contain a YouTube video ID, or any similar relevant string identifying the entity. To avoid collision between id coming from different sources (YouTube, Wikidata, etc.), we could use namespaces.

Examples:
- `youtube:videoid1abc` or `ytu:videoid1abc` could be the `uid` of the YT video `videoid1abc`
- `wikidata:Q0000000` or `wda:Q0000000` could be the `uid` of the Wikidata resource `Q0000000`

Such namespaces also allow to easily filter the entities by their source. The `type` will only indicate if the document is a video, a document, etc. and won't make the difference between videos coming from different sources.

As PostgreSQL don't perform validation for JSONB fields, we will need to validate the incoming JSON at the serializer level, before the entity is saved in the database, to avoid having incoherent JSON structure for entities of the same type.

**(2) tournesol.models.EntityType**

A type identifying an entity. It could be a video, a document, a podcast, etc.

**(3) tournesol.models.Scrutin**

> other possible names: Ballot, Election, ...

This new model will have a **n to n** relationship with the `Entity` model. A "scrutin" will make entities available for comparisons within its own scope.

For instance, the current tournesol.app application contains only one scrutin, allowing to compare YT videos. If we want Tournesol to not mix in the same ranking videos and presidents, we will be able to create two scrutins, that will make any API consumer able to know that a video can't be compared with a president.

It's still possible to mix entities with different `type` inside the same scrutin.  With this design we will cover all use cases:
- comparisons between a subset of YT videos
- comparisons between YT videos + PeerTube videos
- comparisons between PeerTube videos + Wikipedia page + something else

Each entity will have a rating related to a specific scrutin. This way a president could be the winner of an election in 2022 but the looser of the next election.

## other database changes

The `Comparison` object will have a foreign key to `Scrutin`.

The criteria will be stored inside the database, and will have a relationship with `Scrutin`.

## new API design

**(4) Unchanged routes**

* `/accounts`
* `/domains`
* `/schema`
* `/users/me/video_rate_later`

**(5) comparisons are identified with `(scrutin_name, uid_a, uid_b)`**
instead of `(video_id_a, video_id_b)`.

New routes would be:
* `GET /users/me/comparisons`
* `GET /users/me/comparisons/{scrutin_name}`  
(or possibly `/users/me/comparisons?scrutin=` )
* `POST /users/me/comparisons/{scrutin_name}` to submit a comparison
* `GET|PUT /users/me/comparisons/{scrutin_name}/{uid_a}/{uid_b}`

> NB: a same pair `(uid_a, uid_b)` can be compared in different scrutins

**(6) similarly, contributor_ratings are identified with `(scrutin_name, uid)`**
 * `GET /users/me/contributor_ratings/{scrutin_name}`
 * `POST /users/me/contributor_ratings/{scrutin_name}` (e.g to initialize a rating as public/private)
 * `GET|PUT|PATCH /users/me/contributor_ratings/{scrutin_name}/{uid}`
 * `PATCH /users/me/contributor_ratings/{scrutin_name}/_all` to update all ratings in a scrutin

**(7) new routes related to scrutins**
* `GET /scrutins/{scrutin_name}` to fetch the list of criterias, etc.
* `GET /scrutins/{scrutin_name}/criteria` (maybe not necessary)
* `GET /scrutins/{scrutin_name}/recommendations` to fetch recommendations, statistics, etc. ( or `/results` or `/ranking`?)
* `GET /scrutins/{scrutin_name}/entities` to fetch all entities, regardless of the score, without default filter

**(8) new routes related to entities**
* `GET /entities/?type=X&filter=Y`
* `GET /entities/{uid}` to fetch metadata and results in all scrutins

**Comment by lfaucon** [comment]
# Notes on RFC: Tournesol API refactor

> (I personally like Candidate more than Entity and more than the rest.)

I would strongly go for `Content` of `Entity`


> We forecast this new model will have the following attributes:
> id a unique identifier managed by the database
> uid a unique identifier that will be used by the API to reference the entity

I fail to understand how `id` is useful (conditonal to `uid` uniques)?

> namespaces

Scrutins ? or not exactly ?

> Scrutins

We really should find a better name

> (2) tournesol.models.EntityType

Not super convinced

> The criteria will be stored inside the database, and will have a relationship with Scrutin

Do I understand that it is a new db table ?

> (4) Unchanged routes
> /users/me/video_rate_later

Maybe it should change later on, not a priority

> /users/me/comparisons/{scrutin_name}

I would propose `/users/me/scrutin/{scrutin_name}/comparisons/`

> GET /scrutins/{scrutin_name}/criteria (maybe not necessary)

Not necessary short term but useful so that frontend/clients don't need to configure the lists of criterias

> (8) new routes related to entities
> GET /entities/?type=X&filter=Y
> GET /entities/{uid} to fetch metadata and results in all scrutins

Not entities in a a Scrutin ?

**Comment by GresilleSiffle** [comment]
### questions

Should we have a **1-n** or a **n-n** relationship between `Entity` and `EntityType`?

**Comment by GresilleSiffle** [comment]
possible names for entities:
- item
- option
- alternative
- content

**Comment by GresilleSiffle** [comment]
possible names for scrutins:
- ballot
- election
- poll -
- selection
- comparison configuration -
- recommender
- slate
- tally

**winner:**
