### ISSUE TITLE
[back] feat: Include aggregated scores in API response containing criteria scores

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#519]
Context:

Currently the frontend and the extensions both compute an aggregated score. It makes more sense for this score to be computed only in one place on the backend. 

Acceptance:
- [ ] Update necessary backend api routes to include the Tournesol's scores
- [ ] Update the frontend to use the score provided by the backend
- [ ] Update the extension to use the code provided by the backend

**Comment by GresilleSiffle** [comment]
Here is the list of endpoints that must be updated to complete the acceptance criterion 1 

- /entities/
- /entities/{uid}
- /polls/{name}/recommendations
- /video/
- /video/{video_id}

**Comment by GresilleSiffle** [comment]
The back end computes the `tournesol_score` and the front end uses it directly (see #614).

We just need to update the browser extension now.
