### ISSUE TITLE
feat: remove viewed videos from recommendations

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#520]
Context from discord discussion

> Louis — Today at 10:45 PM
It's true that Tournesol doesn't know which videos a user has watched and will possibly recommend videos that have already been watched
Thanks for raising this point, I had never thought about this ^^
Currently recommendations are not personnalized and Tournesol display the same recommendations to everyone (except for some languages choices)
Personnalization is quite difficult and we definitely want to work a lot on it in the future.
>
> dorsan — Today at 10:48 PM
Is Tournesol able to know if we've chose a video that it recommands? in this case it could be useful to delete these videos of the reco
>
> jst's Matrix bridge — Today at 10:49 PM
it would require deciding what "choose" mean, it's probably not a good idea that a random click on a reco makes it disappear forever from your reco
and guessing if you watched it or just misclicked / followed the link to get an overview is not trivial 
>
> Louis — Today at 10:51 PM
We don't yet collect this data. We could collect it to provide this feature (while being respectful to user's privacy) 
>
> jst's Matrix bridge — Today at 10:52 PM
having a list of videos that a given user doesn't want to be in her recommendations anymore and filtering them out is probably not too hard though
it could include those she compared and some that she would have explicitly rejected
>
> dorsan — Today at 10:53 PM
hmm, in the first place just ad a button "viewed" to the right of "rate later" can be easier to developed (i suppose), it's not perfect because it needs an action by the user but it can still be usefull for the quality of the recommandations by tournesol for an individue

**Comment by aidanjungo** [comment]
I don't think it should be something by default because the recommendation would be a bit misleading.

However, it could be an option in recommendations filters "Remove video I already rated". 

Another option would be to have another page (e.g. "Video for me" or "Personalized videos") where we show videos filtered by some option including "Videos I have never seen".

**Comment by lfaucon** [comment]
> Another option would be to have another page (e.g. "Video for me" or "Personalized videos")

I also prefer this, but it is slightly misleading if we only have non-watched as a personnalization criteria

**Comment by lfaucon** [comment]
Duplicate of #1023
