### ISSUE TITLE
refactor: comparisons API now handles `Poll`

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#527]
**requires** #526 

also see the issue #509

---

Refactor the comparisons API to handles `Poll`.

### back end

**to-do**

- use uid instead of video_id in JSON payload of all comparisons endpoints
- update the front end accordingly

**done**

Create a migration to set the value of the comparison poll FK to the previously created Poll with name `videos`.

Create a migration to remove the NULLABLE constraint on this FK.

`GET /users/me/comparisons/{pollname}/` - get all my comparisons made in this poll

`POST /users/me/comparisons/{pollname}/` create a new comparison in this poll
 
`GET|PUT /users/me/comparisons/{pollname}/{uid_a}/{uid_b}/` get or partial update of a comparison in this poll 

`GET /users/me/comparisons/{pollname}/{uid_a}/` get all comparisons that include the entity with `uid_a` in this poll 

Add a validation ensuring the submitted criteria name match those in the requested poll ( a match in the name will be sufficient for now ).

Replace `video_id_a` & `video_id_b` in URLs by `uid_a` & `uid_b`

Replace `video_a` & `video_b` in JSON representation of comparisons by `entity_a` & `entity_b`

Adapt the tests.

### front end

**done**

Update the API schema and re-generate the services.

Update the components to use the new endpoints.

Hardcode the new `pollname` in the front end ( as a constant ).

**Comment by lfaucon** [comment]
How do we handle the current calls to `GET /users/me/comparisons/`. Will this be a breaking change? Or do we maintain complete backward compatibility? In case of breaking change, it should just be a matter of refreshing the frontend web page for users, so not too bad, but better to avoid.
