### ISSUE TITLE
Define priorities and strategies for Tournesol Wiki

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#557]
This issue arise during the last retrospective. The role of [wiki.tournesol.app](https://wiki.tournesol.app) is unclear.

- Some of the content present on the Wiki would be more useful in the frontend (e.g to guide first-time users).
- The Wiki stayed mostly unchanged in the last few months.
- Is there a specific need to provide "advanced" documentation in the Wiki (e.g for researchers)?
- Need for internationalization? Or english only ?
- How should the Wiki be integrated with the Tournesol platform?

--- 
List of all pages on the current Wiki:
https://wiki.tournesol.app/wiki/Special:AllPages

**Comment by amatissart** [comment]
@lenhoanglnh During the discussion, it appeared that you are probably the person with the best view of how useful the wiki could be. It would be nice to discuss about this at some point.

**Comment by amatissart** [comment]
The decision has been made to remove the wiki, currently unmaintained.

- [ ] Export wiki dump in a more flexible format.
**Wiki pages in Markdown format:** [wiki_pages_markdown.zip](https://github.com/tournesol-app/tournesol/files/10834913/wiki_pages_markdown.zip)

- [ ] Move relevant content to the frontend:  
#1388 
- [ ] Remove references to the wiki
- [ ] Remove and disable wiki deployment

**Comment by GresilleSiffle** [comment]
We can also remove the corresponding oauth applications created in the back end admin.

**Comment by lfaucon** [comment]
Last step to close this ticket:

- [ ] Clean-up infrastructure code to remove everything needed for the wiki
