### ISSUE TITLE
[front] Display statistics on Home page and About page

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#571]
We recently developped a `stats` endpoint that we can now use in the frontend.

Acceptance Criteria:
- [ ] Create a new component to be displayed at the bottom that displays the three metrics (see @aidanjungo 's comment below). Ensure responsiveness: 3 metrics on one line for large screen but in column for mobile.
- [ ] Clean-up the paragraph on the About page to not contain hardcoded outdated numbers.

Notes:
- Stats api: https://api.tournesol.app/stats/ 
- Should use `StatsService.statsRetrieve` to fetch the data

**Comment by aidanjungo** [comment]
Could be something like that:
![image](https://user-images.githubusercontent.com/53896963/153641466-1ffed889-3d36-48db-8980-ff293703f695.png)

**Comment by iamnkc** [comment]
Hello, can I work on this feature ?

**Comment by lfaucon** [comment]
Yes, that would be very welcome.
