### ISSUE TITLE
Making README in backend more clear for new developers

### ISSUE THREAD

**Issue by sintaz1992** [tournesol-app/tournesol#573]
When I was going through the README In backend [README](https://github.com/tournesol-app/tournesol/blob/main/backend/README.md) , I found it confusing why should I add a google API key. it would be nice to explain when it useful to do so.

**Comment by GresilleSiffle** [comment]
That's true!

I think the `Setup Google Api Key` section should go under the **Install** section, as it is part of the installation process. The key point is to identify if its required by both the automatic and manual installation procedures, or just one of them.
