### ISSUE TITLE
deselecting the last filter procudes a shake effect

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#579]
found
- on main at https://github.com/tournesol-app/tournesol/commit/533fadfaf8bfa9373e65feecffad7a979248e616
- on staging at https://github.com/tournesol-app/tournesol/commit/33a6a1d8b12a6cb1605159cc447d9324fc20df4c

not present on production at https://github.com/tournesol-app/tournesol/commit/29c8f9c939f045d30d83e256948df77c0d9505e4

seems to be a regression introduced by https://github.com/tournesol-app/tournesol/commit/33a6a1d8b12a6cb1605159cc447d9324fc20df4c

---

On the Tournesol recommendations page, deselecting the last filter changes the width of a `<div>`, producing a little shake effect. 

### reproduce

- checkout main at https://github.com/tournesol-app/tournesol/commit/533fadfaf8bfa9373e65feecffad7a979248e616
- or go directly to staging
- click on the `Recommendation` item in the left menu
- open the filters
- deselect the filter `This Month`

### expected

The width of the container doesn't change when the last checked filter is deselected.

**Comment by amatissart** [comment]
@GresilleSiffle Is that not due to how the scroll bar appears when the list of video was empty, and the unfiltered list is longer?  
That's also visible on production, for example when switching from "This Month" + "German" to "This Month" only.

**Comment by GresilleSiffle** [comment]
Indeed!
