### ISSUE TITLE
Adding more data to My Profile page

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#58]
My profile page should have more things to show to the user, for example:
- rating history
- some badge/trophy  (e.g to show how many videos they rated last week/last month/all time)
- some data analysis about user rating (correlation between criteria, ratings evolution)

Here an example of how it could be displayed:
![My_profile_idea](https://user-images.githubusercontent.com/53896963/116790573-2ca8e200-aab5-11eb-8b08-0ef7629bb42d.gif)

**Comment by sergeivolodin** [comment]
Need to add api as well
