### ISSUE TITLE
max_score, min_score required or not?

### ISSUE THREAD

**Issue by sintaz1992** [tournesol-app/tournesol#592]
https://github.com/tournesol-app/tournesol/blob/b538ff31ad8f007543cbc441a2426f818fe74533/frontend/src/features/videos/VideoCard.tsx#L241

max_score and min_score are defined here but it seems never used. Is there a usage somewhere else or predicted otherwise should be removed?

**Comment by amatissart** [comment]
Hi @sintaz1992 
`min_score` and `max_score` are not visible on the card. They are just temporary variables to find the criterias with the lowest/highest score:

https://github.com/tournesol-app/tournesol/blob/b538ff31ad8f007543cbc441a2426f818fe74533/frontend/src/features/videos/VideoCard.tsx#L236-L240

https://github.com/tournesol-app/tournesol/blob/b538ff31ad8f007543cbc441a2426f818fe74533/frontend/src/features/videos/VideoCard.tsx#L244-L248
