### ISSUE TITLE
Only display accepted domains. Also, the list is incomplete.

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#6]
1. I fear that rejected and pending domains may be regarded as revealing personal information.
https://tournesol.app/email_domains

2. Also, the list is incomplete. The domain @alumni.epfl.ch was accepted but does not appear on [the page](https://tournesol.app/email_domains).
<img width="525" alt="Screen Shot 2021-04-29 at 11 13 39" src="https://user-images.githubusercontent.com/10453308/116528302-f6643a80-a8db-11eb-9a56-2963456ad466.png">

3. For each accepted domain, we should list the number of Tournesol accounts with an email from this domain, and the number of ratings provided by these accounts. Hopefully, this can create some competition spirit to motivate people to contribute 😋

**Comment by lenhoanglnh** [comment]
Also, for each accepted domain, we should list the number of Tournesol accounts with an email from this domain, and the number of ratings provided by these accounts.

Hopefully, this can create some competition spirit to motivate people to contribute 😋

**Comment by sergeivolodin** [comment]
Added API:

- removed rejected and pending domains
- showing count of verified emails
- sorting by count
- can set offset=... to get the second page

```json
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 289,
    "next": "https://tournesol.app/api/v2/email_domain/?limit=30&offset=30",
    "previous": null,
    "results": [
        {
            "domain": "@epfl.ch",
            "status": "ACK",
            "n_verified_emails": 39
        },
        {
            "domain": "@orange.fr",
            "status": "ACK",
            "n_verified_emails": 15
        },
        {
            "domain": "@ens-lyon.fr",
            "status": "ACK",
            "n_verified_emails": 9
        },
...
```

**Comment by sergeivolodin** [comment]
@lfaucon can you add pages to e-mail domains and add the statistic (`n_verified_emails`)?

**Comment by lfaucon** [comment]
Ok, I'll work on this :)
