### ISSUE TITLE
Reorganize Discord channels

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#603]
Should we have better organization of the Discord channels, more interaction with people?

Idea: We could maybe use the Github Discussion for the tech part and keep Discord more "social"...

**Comment by GresilleSiffle** [comment]
**suggestion**

I'd like to propose a first read-only `INFO` section for our Discord server.

```
[INFO]
+- welcome
+- rules
+- announcements
+- papers
+- FAQ
```

The channel `welcome` could contain:
- very small presentation of the platform and the extension, with links to join tournesol.app and download the extension
- an invitation to check the source code
- an invitation to check the Discord rules

The `rules` could contain:
- the code of conduct everyone accept to follow by joining the Discord
- how to contact an administrator in case of need
- maybe the sanction we could take in case of need ( temporary ban, permanent ban )
- we can take inspiration of existing codes of conduct
  - https://www.python.org/psf/conduct/
  - https://www.contributor-covenant.org/version/2/1/code_of_conduct/

The `announcements` could contain (it's my favorite section):
- new front end features
- new API features
- new extension releases
- new paper submitted / reviewed
- anything worth pinging the community

...

**Comment by aidanjungo** [comment]
From Tournesol association general assembly, an idea came up:

- having a channel where we propose some well defined task to accomplish so people could get involved easily

**Comment by lfaucon** [comment]
We did some re-organization already. It's in a better state. Let's re-open a more precise ticket to propose more changes.
