### ISSUE TITLE
[back, front] refactor: Harmonize all API and Serializers (then:feat: Rate later list display information about the number of comparisons)

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#606]
As a user I want to see how many times I have compared the videos when I look at my rate later list so that I can easily chose which videos to remove from my rate later list.

Display the information similarly as in the card used on the comparison page.

This probably will be best implemented by updating the backend endpoint to include the extra info

**Comment by GresilleSiffle** [comment]
Here is the JSON the API could return.

The new `poll_metadata` key contains all data related to the poll, like the total number of comparisons by all contributors.

The `user_metadata` key contains all data related to the logged user. Having different keys for collective and and personal data will allow the front end to: (1) know what kind of data are displayed ; (2) display both collective and personal data at the same time.

```json
{
  "entity": {
    "uid": "string",
    "type": "video",
    "metadata": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    }
  },
  "poll_metadata": {
    "n_comparisons": "number",
    "n_contributors": "number"
  },
  "user_metadata": {
    "n_comparisons": "number",
    "n_contributors": "number"
  }
}
```

**Comment by lfaucon** [comment]
User metadata is also poll specific. The distinction is rather at the level or global/community/aggregated vs. user/personal ? Not poll vs. user.

**Comment by lfaucon** [comment]
Apart from this, I really like the proposal to simplify the keys at the root of the entity JSON representations and allowing API routes to include the root entries or not depending on what is requested. 

I would even go further and impose fixed types for each of the root entries. For example by having one entry `global_metadata` and one `global_criteria_scores` to avoid changing the type of the global_metadata entry

**Comment by lfaucon** [comment]
You have `n_contributors` in entry `user_metadata`. Is it a typo or something that I don't understand correctly?

**Comment by amatissart** [comment]
Thanks @GresilleSiffle for the details, I think it's a step in the good direction.

> User metadata is also poll specific. The distinction is rather at the level or global/community/aggregated vs. user/personal ? Not poll vs. user.

I agree. "poll_metadata" and "user_metadata" could bring more confusion. For example, a "tournesol_score" (contrary to "name") is not a property of a `Poll`, it's part of an `EntityPollRating`. And keeping this distinction clear will also make the implementation of the serializers easier.

Also, about naming, I would not use "_metadata" as a suffix for keys. It does not seem like to good description to me. Either "user_metadata" represents the user and could be named "user", or its name should be more explicit.

So based on the first suggestion, I would suggest something like:
```js
{
  "entity": {
    "uid": "string",
    "type": "video",
    "metadata": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    }
  },
  "poll": {
  // represents an instance of `Poll`
    "name": "string",
  },
  "global": { // or "global_rating", or  "poll_rating" ?
  // represents an instance of `EntityPollRating`, could be extended with `"criteria_scores"` in some contexts
    "tournesol_score": 0,
    "n_comparisons": 0,
    "n_contributors": 0
  },
  "individual": { // or "contributor_rating" ?
   // represents an instance of `ContributorRating`, could be extended with `"criteria_scores"` in some contexts
    "n_comparisons": 0,
  },
  "rate_later_metadata": {
    "created_at": "2022-11-08T13:47:39.480Z"
  }
}
```

**Comment by GresilleSiffle** [comment]
Thank you!

You're right, using the suffix `_metadata` is not that good.

I like `collective_rating` instead of `global` / `global_rating` / `poll_rating`. The `_rating` might disappear the day we will save more information than just ratings, but keeping it right now make it more explicit tha simply `collective` or `global`.

If `individual` represents the contributor rating, maybe we can use the name `contributor_rating` directly. We can try to re-use  the existing `ContributorRatingSerializer` or a similar read-only oriented serializer. 

Based on the last suggestion, what do you think of this?

```json
{
  "entity": {
    "uid": "string",
    "type": "video",
    "metadata": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    }
  },
  "poll": {
    "name": "string",
  },
  "contributor_rating": {
    "is_public": true,
    "n_comparisons": 0
  },
  "collective_rating": {
    "tournesol_score": 0,
    "n_comparisons": 0,
    "n_contributors": 0
  },
  "rate_later_metadata": {
    "created_at": "2022-11-08T13:47:39.480Z"
  }
}
```

**Comment by lfaucon** [comment]
Left to-do

- [ ] Adapt the `ratings` API
- [ ] Adapt the `recommendations` (and `entities`?) API
- [ ] Adapt front rate-later page video cards to display the number of comparisons
