### ISSUE TITLE
Create model to store score and stats related to (entity, poll)

### ISSUE THREAD

**Issue by amatissart** [tournesol-app/tournesol#631]
Model `Entity` currently contains fields `rating_n_contributors`, `rating_n_ratings`, as well as `tournesol_score` introduced in #614.

These fields are actually specific to a given poll, and should be moved to a new model, with foreign keys to `Entity` and `Poll`.
Potential name: `EntityPollScore`

**Comment by lfaucon** [comment]
My understanding of this issue is that it is not high priority because we only need this when we will have multiple Polls using the same entities. Please correct me if I understand this wrongly.

**Comment by GresilleSiffle** [comment]
- [x] create the new model
- [ ] test the new model
- [ ] create the data migration / update the comparisons view to create or refresh the model after each comparison / update the serializers / update the API tests

**Comment by lfaucon** [comment]
@bbosson can look at the PR #1149
