### ISSUE TITLE
Search interface design

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#64]
Here is the current proposal by @TheDuckWhisperer: 
https://www.figma.com/file/3uI7FiBhXp0hhgdTdHBSkj/Tournesol?node-id=46%3A0

<img width="992" alt="Screen Shot 2021-05-02 at 07 42 25" src="https://user-images.githubusercontent.com/10453308/116803642-f2bdf700-ab19-11eb-9050-12aca378e389.png">

<img width="990" alt="Screen Shot 2021-05-02 at 07 44 31" src="https://user-images.githubusercontent.com/10453308/116803692-3dd80a00-ab1a-11eb-9812-a2b1bb7c06c5.png">

Important features: 
- Search bar always appearing on top of Tournesol.
- Search options must be opened by clicking on "Filters".
- The quality criteria appear as "rated high" and "rated low".
- The quality criteria bar chart is hidden by default. Users can click on "details" to make it appear.

Edits needed:
- The search feature "Language" should be added.
- The new quality criterion "Entertaining and relaxing" should be added.

Next step. We need to finalize the design before moving to front-end implementation:
- Show visually what happens when the bar charts are shown (coordinate with #45).
- Finalizing color / logo choices (@TheDuckWhisperer, create an issue for each?).
- Should search also return associated contributors and Tournesol comments? (I think yes, but this can be developed later on).

**Comment by lenhoanglnh** [comment]
Maybe add option to allow/prevent Tournesol from recording the parameters of the search?

**Comment by TheDuckWhisperer** [comment]
@lenhoanglnh I'm not sure about adding the language filter. My preference would be to add this as a user setting since most people will not use it to filter their search. Additionally, isn't the problem gonna solve itself once we have a more varied usergroup and more varied content on Tournesol?

**Comment by TheDuckWhisperer** [comment]
Created issues for Color & Logo (although I don't think they are a necessity to start this issue). #78 #79
