### ISSUE TITLE
Determine and show which contributors are pushing/pulling a video's scores

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#65]
Combine this with #57 and #64.

**Comment by sergeivolodin** [comment]
It's also important for online updates -- we can select the correct minibatch

**Comment by sergeivolodin** [comment]
Isn't this just the first+second derivatives of the score w.r.t. the rating?

**Comment by lenhoanglnh** [comment]
Actually, just the first derivative of the independent loss with respect to the individual score at optimum is needed.

If global_score(video) > score(video, contributor) + .0001:
   return -2
If global_score(video) < score(video, contributor) - 0.001:
   return +2
return - sign ( partial_derivative ( independent_loss (contributor) ) ).
