### ISSUE TITLE
A video appeared on the website as "null views - no date"

### ISSUE THREAD

**Issue by mbourand** [tournesol-app/tournesol#66]
## Context

While listening to music, i noticed the video had an id starting with "-", so i tried to rate it on tournesol and the video appeared like this on the page, also the "Remove from Rate Later" button wasn't working on this video

![image](https://user-images.githubusercontent.com/54736052/116252008-791bb700-a76f-11eb-8462-a92554d51e42.png)

After adding a new random video, the previous one appeared quite correctly except for the thumbnail and at this time the new video was broken. I still wasn't able to remove the music video from the list

![image](https://user-images.githubusercontent.com/54736052/116252434-db74b780-a76f-11eb-9e0b-d20119f6452a.png)

## What's special on this video ?
The only things i noticed on the video thats rare on youtube was that the video id started with a "-" and that the video playing is diabled on other sites than youtube is disabled.

## How to fix it
@lfaucon said that one of the problem might be due to reaching the rate limit for youtube API on the backend, causing delay to get information for new videos

**Comment by sergeivolodin** [comment]
It's likely because the video either wasn't downloaded yet, or it's not available in the country of our server (netherlands)

**Comment by lfaucon** [comment]
So what should the user interface show here, in order to convey that our server is still downloading the information fo the video? @lenhoanglnh @TheDuckWhisperer @sergeivolodin

**Comment by TheDuckWhisperer** [comment]
It depends wether the video will show up at some point or not, and how long this would take. If we're talking about anything between 1-10 seconds an animated loader should suffice I would say. If we also have the scenario a video might not show up at all we can show a message stating this, assuming we can detect it.
