### ISSUE TITLE
[front] feat: add a duration filter in the videos recommendations

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#669]
A filter on the maximum (and potentially minimum) duration of videos could be added to the recommendations filters. This would be useful for users that don't want to watch long videos.

(if this would overload too much the filters interface, you can reject this issue )

**Comment by lfaucon** [comment]
- [ ] Refactor the recommendation endpoint to enable all current filtering that exist on the route `video`
- [ ] Adapt frontend to use `poll/{name}/recommendations`
- [ ] Adapt extension to use `poll/{name}/recommendations`
- [ ] Deprecate all three `video/` endpoints
- [ ] Implement duration filter on `poll/{name}/recommendations` :)

**Comment by GresilleSiffle** [comment]
I think we have space for an additional filter on nearly all kind of screen size (see the captures below).

What do we think is the best for the users?

- being able to filter by max duration?
- being able to filter by min duration?
- both but exclusive?

In order of usefulness, from the most useful to the less useful for me it would be:
1. be able to filter by max duration (with a textual input where I can set the number of minutes, it's precise and take a small space)
2. be able to filter by min duration

May I propose to create a filter, with a text field, working only with positive integer, able to interact with the API parameter `metadata[duration:lte:int]`?

**mobile**

Below the language filter.

![capture3](https://user-images.githubusercontent.com/39056254/172848622-d319ed9d-9282-4730-a16e-52982ebc9f06.png)

**tablet**

Below the language filter.

![capture2](https://user-images.githubusercontent.com/39056254/172848750-8f62b057-392e-4909-af6b-3d4e5d016828.png)

**desktop**

Between language and criteria or just below language.

![capture](https://user-images.githubusercontent.com/39056254/172848798-0fa293b5-fcc6-4d95-9ad9-8d9ca6e7bdb0.png)

**Comment by glerzing** [comment]
I like the sliders that give an interval, like the range slider or the minimum distance slider (https://mui.com/material-ui/react-slider/). 
But ideally, you would want a slider where the minutes 0 to 5 take more place than the minutes 55 to 60. So, maybe something like the "minimum distance" slider but with discrete values (e.g. 0, 5, 10, 30, 60, ∞) could be cool.

**Comment by lfaucon** [comment]
I agree that filtering by max duration is the most important. Whether a number field (as in https://mui.com/material-ui/react-text-field/#inputs) or the choice options <5min / <20min / unlimited (with unlimited as the default) would be great. 

I have a slight preference for the three choices.

**Comment by GresilleSiffle** [comment]
> I agree that filtering by max duration is the most important.

Great. The PR https://github.com/tournesol-app/tournesol/pull/976 adds a maximum duration filter.

> I have a slight preference for the three choices.

Oops, I created a PR with a Material `TextField` last Thursday, before receiving your message :sweat_smile:

I think the choice field is more user friendly, as it requires only one click to filter the results. On the other hand the input field can handle any number of duration, takes less space, but requires a focus and typing.
