### ISSUE TITLE
Add a button to easily display the criteria scores of a video

### ISSUE THREAD

**Issue by glerzing** [tournesol-app/tournesol#670]
There currently isn't a practical way to see a video's analysis detailed by criterion (except the extension's "analysis" button). There could be a 3rd button (e.g. with the icon @material-ui/icons/Poll) at the right of videos to display this information. For example, it could link to the tournesol.app/video/{video_id} page. Or it could display the radar chart in a popover when the mouse hovers over it, which would feel more lightweight.

![Capture d’écran de 2022-03-13 13-20-28](https://user-images.githubusercontent.com/47578089/158063586-7a8744a1-ea61-4357-bf79-0bdafa8c2f55.png)

**Comment by lfaucon** [comment]
Done by c40b52f0121d0dea379391d06d63f5edc576ebd9
