### ISSUE TITLE
Extract candidate citations per criteria for helping judgements of contributors

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#690]
In order to help contributors compare candidates we propose to show propositions or 1 to 3 quotes from candidates on each of the 7 themes:

- Énergie & environnement
- Éducation, culture & information
- Santé & bien-être
- Institutions & démocratie
- Travail & économie
- Solidarité & inclusion
- Politique internationale

**Comment by Plok64** [comment]
Début de travail pour LePen


Nucléaire / renouvelable :
- Rendre aux ménages les 5 milliards de subventions versées notamment aux éoliennes.
- Arrêter les projets éoliens et démanteler progressivement les parcs existants.
- Relancer la filière nucléaire, hydroélectrique et investir dans la filière hydrogène.

Environnement (autre) :

Changement climatique : 

Agriculture :
- Garantir aux paysans des prix respectueux de leur travail et mettre un terme aux marges abusives de la grande distribution.
- Interdire les importations de produits agricoles ne respectant pas les normes de production française.
- Contraindre les cantines à utiliser 80% de produits agricoles français.
- Généraliser l’étiquetage sur l’origine et la qualité des produits alimentaires.
- Mettre en place un « plan abattoirs » pour assurer des conditions dignes ??????????????????????????????

----

Emploi et Chomage :
- Conditionner les subventions à la création d’emplois au titre d’une politique d’aménagement du territoire

Les déficits publics et la dette :

Economie :
-  Protéger notre économie de la concurrence déloyale et revoir les accords de libre-échange qui ne respectent pas les intérêts de la France

Fiscalité et Pouvoir d'achat (impot salaires) :
- Baisser la TVA de 20% à 5.5% sur les produits énergétiques (carburants, fioul, gaz et électricité) en tant que biens de première nécessité.
- Exonérer d’impôt sur le revenu tous les jeunes actifs jusqu’à 30 ans pour qu’ils restent en France et fondent leur famille chez nous
- Supprimer l’impôt sur les sociétés pour les entrepreneurs de moins de 30 ans pendant les 5 premières années pour éviter leur départ à l’étranger
- Verser un complément de salaire de 200 à 300€ pour les jeunes qui travaillent durant leurs études et valident leurs examens
- Créer un chèque-formation mensuel de 200 à 300€ pour les apprentis, les alternants et leurs employeurs
- Supprimer l’IFI qui taxe l’enracinement et créer un IFF, impôt sur la fortune financière, pour taxer la spéculation.
- Créer un ministère de la lutte contre les fraudes (fiscales, aux cotisations et prestations sociales, aux importations, ententes, etc.)

Innovation entreprises :
- Permettre aux entreprises d’augmenter les salaires de 10% en les exonérant de cotisations patronales (pour les salaires allant jusqu’à 3 fois le smic).
- Supprimer la Cotisation Foncière des Entreprises (CFE) qui pénalise les PME-TPE locales et les impôts de production qui nuisent à la relocalisation.

Fonction publique :
- Renationaliser les autoroutes pour baisser de 15% les péages
- Privatiser l’audiovisuel public pour supprimer les 138€ de redevance
- Donner la priorité aux PME pour les marchés publics.

Transport : 
- Instituer la gratuité des transports aux heures creuses pour les 18-25 ans.

----

Logement :
- Construire en cinq ans 100 000 nouveaux logements étudiants.
- Construire 100 000 logements sociaux par an dont 20 000 en faveur des étudiants et jeunes travailleurs.
- Lancer un plan de réhabilitation de l’habitat ancien grâce à des aides efficaces.
- Créer un Fonds de Garantie des loyers pour protéger les propriétaires

Retraites / Vieillesse : 
- Réindexer les retraites sur l’inflation pour un pouvoir d’achat respectueux d’une vie de travail.
- Revaloriser le minimum vieillesse à 1 000 € par mois et augmenter les petites retraites.
- Refuser tout allongement de l’âge de départ à la retraite.
- Permettre à ceux qui ont commencé à travailler avant 20 ans pendant 40 annuités de prendre leur retraite à 60 ans.
- Restaurer la demi-part fiscale en faveur des veuves et veufs.
- Créer un droit opposable aux visites dans les établissements et accroître fortement la présence de personnel médical dans les EHPAD

Enjeux sociétaux :

Handicap :
- Déconjugaliser et revaloriser l’Allocation Adulte Handicapée
- Lancer un grand plan sur l’accès à la scolarité pour les enfants touchés par le handicap.
- Appliquer la loi sur l’accès à tous les lieux et transports publics.
- Revaloriser et augmenter la durée des aides destinées aux proches aidants.

Violences faites aux femmes :

Inégalités sociales :

Inégalités :

Discriminations :

Altruisme efficace :

Egalité femmes-hommes :

Famille :
- Doubler le soutien aux mères isolées élevant des enfants tout en renforçant les contrôles pour éviter les fraudes
- Instituer une part fiscale complète dès le deuxième enfant.
-  Créer un prêt à 0% pour les jeunes familles françaises transformé en subvention pour les couples qui auront un 3e enfant.
- Supprimer les impôts sur l’héritage direct pour les familles modestes et les classes moyennes.
- Exonérer les donations des parents mais aussi des grands-parents à leurs enfants et petits-enfants jusqu’à 100 000€ par enfant tous les dix ans

Condition animale :
- Interdire l’abattage sans étourdissement en abattoir.

----

Laïcité :

Défense de la République et de la laïcité :
- Éradiquer les idéologies islamistes et l’ensemble  de leurs réseaux du territoire national.

Violence policières :

Démocratie :
- Instaurer le Referendum d’Initiative Citoyenne et mettre en place la proportionnelle.

Institutions :

Répartitions des compétences entre l'Etat et les territoires :

Outre mer :
- Créer un ministère d’Etat de la Mer et de l’Outre-mer.

Territoires, collectivités :

Justice : 
- Rétablir les peines planchers pour que tout criminel et délinquant aient une sanction.
-  Supprimer toute possibilité de réduction et d’aménagements de peine, en particulier pour les violences contre les personnes.
- Accélérer les procédures judiciaires en visant le doublement du nombre de magistrats en 5 ans.
- Atteindre 85 000 places de prison en 2027.

Délinquence :
-  Inscrire au fichier des délinquants sexuels les harceleurs de rue.

Légalisation du cannabis :

----

Ethique des algorithme :

L'information et la mésinformation :

Media : 

Jeunesse :

Réseaux sociaux :

Statistiques bayésienes :

Systeme scolaire et Enseignement :
- Remettre au cœur des programmes l’enseignement du français, des mathématiques et de l’histoire.

Education :
- Revaloriser les salaires des enseignants et refonder leur formation.
- Rétablir l’autorité de l’institution scolaire par l’instauration d’un uniforme au primaire et au collège tout en sanctionnant les absences et les incivilités.
- Supprimer la bureaucratie de l’Education nationale pour libérer des moyens financiers, réduire les effectifs des classes et arrêter les fermetures d’écoles.

Culture :

----

Terrorisme :

Sécurité :
- Instituer une présomption de légitime défense pour les forces de l’ordre

Questions européennes :

International :

Défense :
- Porter le budget de la défense à 55 milliards d’euros à l’horizon 2027.
-  Garantir à nos soldats l’équipement et les moyens nécessaires pour garantir et protéger les intérêts nationaux.

Europe :

Diplomatie international :

Immigration : 
- Mettre fin à l’immigration de peuplement et au regroupement familial.
- Traiter les demandes de droit d’asile uniquement à l’étranger.
-  Réserver les aides sociales aux Français, et conditionner à 5 années de travail en France l’accès aux prestations de solidarité.
- Assurer la priorité nationale d’accès au logement social et à l’emploi.
- Renvoyer tout étranger n’ayant pas travaillé depuis un an en France.
- Expulser systématiquement clandestins, délinquants et criminels étrangers.
- Supprimer le droit du sol et limiter l’accès à la nationalité à la seule naturalisation sur des critères de mérite et d’assimilation.

----

Santé :
- Arrêter les fermetures des lits à l’hôpital public et des maternités.
- Investir dans les technologies de santé et rapatrier la fabrication des médicaments.
- Créer des urgences gériatriques dédiées à nos aînés

- Agir contre les déserts médicaux grâce à des incitations financières fortes pour les soignants et augmenter le nombre de maisons de santé.
- Donner plus de place à la prévention, notamment grâce aux visites médicales scolaires qui redeviendront systématiques

Vaccins :

Système de santé :
- Revaloriser les salaires des personnels soignants à hauteur de leur travail.
- Supprimer les ARS et réduire à 10% les postes administratifs dans les hôpitaux pour libérer des moyens pour les soignants.

Ethique, fin de vie :

Santé mentale :

Ski de rando :

Sports :

Epidémie Covid 19 :

**Comment by lfaucon** [comment]
Thanks @Plok64 . For other candidates, we can target 1-3 citations for each of the 7 large themes (so a total of 7 to 21 citations). Sources would be greatly appreciated too if available.

**Comment by Plok64** [comment]
LEPEN :

ENVIRONNEMENT / ENERGIE

    Rendre aux ménages les 5 milliards de subventions versées notamment aux éoliennes.
    Arrêter les projets éoliens et démanteler progressivement les parcs existants.
    Relancer la filière nucléaire, hydroélectrique et investir dans la filière hydrogène.
    Garantir aux paysans des prix respectueux de leur travail et mettre un terme aux marges abusives de la grande distribution.
    Interdire les importations de produits agricoles ne respectant pas les normes de production française.
    Contraindre les cantines à utiliser 80% de produits agricoles français.
    Généraliser l’étiquetage sur l’origine et la qualité des produits alimentaires.
    Mettre en place un « plan abattoirs » pour assurer des conditions dignes ??????????????????????????????

TRAVAIL ET ECONOMIE :

    Conditionner les subventions à la création d’emplois au titre d’une politique d’aménagement du territoire
    Protéger notre économie de la concurrence déloyale et revoir les accords de libre-échange qui ne respectent pas les intérêts de la France
    Baisser la TVA de 20% à 5.5% sur les produits énergétiques (carburants, fioul, gaz et électricité) en tant que biens de première nécessité.
    Exonérer d’impôt sur le revenu tous les jeunes actifs jusqu’à 30 ans pour qu’ils restent en France et fondent leur famille chez nous
    Supprimer l’impôt sur les sociétés pour les entrepreneurs de moins de 30 ans pendant les 5 premières années pour éviter leur départ à l’étranger
    Verser un complément de salaire de 200 à 300€ pour les jeunes qui travaillent durant leurs études et valident leurs examens
    Créer un chèque-formation mensuel de 200 à 300€ pour les apprentis, les alternants et leurs employeurs
    Supprimer l’IFI qui taxe l’enracinement et créer un IFF, impôt sur la fortune financière, pour taxer la spéculation.
    Créer un ministère de la lutte contre les fraudes (fiscales, aux cotisations et prestations sociales, aux importations, ententes, etc.)
    Permettre aux entreprises d’augmenter les salaires de 10% en les exonérant de cotisations patronales (pour les salaires allant jusqu’à 3 fois le smic).
    Supprimer la Cotisation Foncière des Entreprises (CFE) qui pénalise les PME-TPE locales et les impôts de production qui nuisent à la relocalisation.
    Renationaliser les autoroutes pour baisser de 15% les péages
    Privatiser l’audiovisuel public pour supprimer les 138€ de redevance
    Donner la priorité aux PME pour les marchés publics.
    Instituer la gratuité des transports aux heures creuses pour les 18-25 ans.

SOLIDARITE ET INCLUSION :

    Construire en cinq ans 100 000 nouveaux logements étudiants.
    Construire 100 000 logements sociaux par an dont 20 000 en faveur des étudiants et jeunes travailleurs.
    Lancer un plan de réhabilitation de l’habitat ancien grâce à des aides efficaces.
    Créer un Fonds de Garantie des loyers pour protéger les propriétaires
    Réindexer les retraites sur l’inflation pour un pouvoir d’achat respectueux d’une vie de travail.
    Revaloriser le minimum vieillesse à 1 000 € par mois et augmenter les petites retraites.
    Refuser tout allongement de l’âge de départ à la retraite.
    Permettre à ceux qui ont commencé à travailler avant 20 ans pendant 40 annuités de prendre leur retraite à 60 ans.
    Restaurer la demi-part fiscale en faveur des veuves et veufs.
    Créer un droit opposable aux visites dans les établissements et accroître fortement la présence de personnel médical dans les EHPAD
    Déconjugaliser et revaloriser l’Allocation Adulte Handicapée
    Lancer un grand plan sur l’accès à la scolarité pour les enfants touchés par le handicap.
    Appliquer la loi sur l’accès à tous les lieux et transports publics.
    Revaloriser et augmenter la durée des aides destinées aux proches aidants.
    Doubler le soutien aux mères isolées élevant des enfants tout en renforçant les contrôles pour éviter les fraudes
    Instituer une part fiscale complète dès le deuxième enfant.
    Créer un prêt à 0% pour les jeunes familles françaises transformé en subvention pour les couples qui auront un 3e enfant.
    Supprimer les impôts sur l’héritage direct pour les familles modestes et les classes moyennes.
    Exonérer les donations des parents mais aussi des grands-parents à leurs enfants et petits-enfants jusqu’à 100 000€ par enfant tous les dix ans
    Interdire l’abattage sans étourdissement en abattoir.

INSTITUTIONS ET DEMOCRATIE :

    Éradiquer les idéologies islamistes et l’ensemble de leurs réseaux du territoire national.
    Instaurer le Referendum d’Initiative Citoyenne et mettre en place la proportionnelle.
    Créer un ministère d’Etat de la Mer et de l’Outre-mer.
    Rétablir les peines planchers pour que tout criminel et délinquant aient une sanction.
    Supprimer toute possibilité de réduction et d’aménagements de peine, en particulier pour les violences contre les personnes.
    Accélérer les procédures judiciaires en visant le doublement du nombre de magistrats en 5 ans.
    Atteindre 85 000 places de prison en 2027.
    Inscrire au fichier des délinquants sexuels les harceleurs de rue.

EDUCATION, CULTURE ET INFORMATION :

    Remettre au cœur des programmes l’enseignement du français, des mathématiques et de l’histoire.
    Revaloriser les salaires des enseignants et refonder leur formation.
    Rétablir l’autorité de l’institution scolaire par l’instauration d’un uniforme au primaire et au collège tout en sanctionnant les absences et les incivilités.
    Supprimer la bureaucratie de l’Education nationale pour libérer des moyens financiers, réduire les effectifs des classes et arrêter les fermetures d’écoles.

GEOPOLITIQUE INTERNATIONALE

    Instituer une présomption de légitime défense pour les forces de l’ordre
    Porter le budget de la défense à 55 milliards d’euros à l’horizon 2027.
    Garantir à nos soldats l’équipement et les moyens nécessaires pour garantir et protéger les intérêts nationaux.
    Mettre fin à l’immigration de peuplement et au regroupement familial.
    Traiter les demandes de droit d’asile uniquement à l’étranger.
    Réserver les aides sociales aux Français, et conditionner à 5 années de travail en France l’accès aux prestations de solidarité.
    Assurer la priorité nationale d’accès au logement social et à l’emploi.
    Renvoyer tout étranger n’ayant pas travaillé depuis un an en France.
    Expulser systématiquement clandestins, délinquants et criminels étrangers.
    Supprimer le droit du sol et limiter l’accès à la nationalité à la seule naturalisation sur des critères de mérite et d’assimilation.

SANTE ET BIEN-ETRE

    Arrêter les fermetures des lits à l’hôpital public et des maternités.
    Investir dans les technologies de santé et rapatrier la fabrication des médicaments.
    Créer des urgences gériatriques dédiées à nos aînés
    Agir contre les déserts médicaux grâce à des incitations financières fortes pour les soignants et augmenter le nombre de maisons de santé.
    Donner plus de place à la prévention, notamment grâce aux visites médicales scolaires qui redeviendront systématiques
    Revaloriser les salaires des personnels soignants à hauteur de leur travail.
    Supprimer les ARS et réduire à 10% les postes administratifs dans les hôpitaux pour libérer des moyens pour les soignants.

I reflect on the main measures

**Comment by Plok64** [comment]
[Politique](https://www.midilibre.fr/actu/politique/)
Publié le 21/10/2021 à 05:05

Le pouvoir d’achat prend de plus en plus d’importance, montre un sondage Elabe-BFMTV.

Le sondage prend tout son sens, au moment où l’exécutif s’apprête à annoncer des mesures pour atténuer la flambée des prix à la pompe. Le pouvoir d’achat est érigé en priorité par les Français, confirme une enquête Elabe-BFMTV, publiée mercredi.

Ce thème est celui "qui comptera le plus dans le choix des électeurs à l’élection présidentielle de 2022", conclut l’institut. Pour 45 % des Français, ce sera l’un des trois sujets qui compteront le plus au moment de glisser leur bulletin dans l’urne. Pour 23 % des sondés, c’est même le premier critère pris en compte.

Alors que des candidats, comme Éric Zemmour, concentrent leurs discours sur l’insécurité et l’immigration, ces deux thématiques arrivent loin derrière. 30 % des sondés placent la sécurité parmi leurs trois sujets importants (10 % la citent en premier), contre 27 % pour l’immigration (9 %). Suivent la santé (26 %), l’environnement (25 %), les retraites (22 %), l’emploi (21 %) et les injustices sociales (18 %). Sont jugées, actuellement, un peu moins importantes les questions liées à l’éducation (17 %), la menace terroriste (16 %), la fiscalité (13 %) et la protection sociale (11 %). La dette publique (8 %), les inégalités hommes-femmes (6 %), la place de la France dans le monde (5 %) et le logement (4 %) sont eux, parmi les thèmes les moins cités.
Les thèmes jugés moins importants

La question du pouvoir d’achat semble, elle, préoccuper de plus en plus la population. Au moment où la hausse des prix de l’énergie affecte le budget des ménages et tourne en boucle dans les médias, près d’un Français sur deux (45 %) en fait donc désormais l’une de ses trois priorités, soit quatre points de plus que la précédente enquête sur le sujet réalisée il y a un mois.

Elabe note d’ailleurs que l’intérêt pour cette thématique a progressé "fortement" ces quatre derniers mois dans une partie de la population. Il a fait un bond de 22 points dans les communes rurales (55 %), a grimpé de 5 points dans les grandes agglomérations (39 %), et légèrement évolué dans l’agglomération parisienne (30 %, +1).

**Comment by Plok64** [comment]
FABIEN ROUSSEL (IN PROGRESS) :

ENVIRONNEMENT / ENERGIE



TRAVAIL ET ECONOMIE :

- SMIC à 1500 euros net et salaires de la fonction publique seront augmentés de 30 %
- La semaine passe à 32 heures sans diminution de salaires et la retraite à sera à 60 ans à taux plein
- Les aides publiques aux entreprises seront suivies et démocratiquement contrôlées


SOLIDARITE ET INCLUSION :

- Aucune pension ne pourra être inférieure à 1 200 euros net, et la demi-part des veuves et des veufs sera rétablie.
- Par la loi, l’égalité salariale femmes-hommes sera réalisée en un an (proposition 76). Des négociations tripartites (État, organisations patronales, organisations syndicales des salariés) seront organisées pour une hausse généralisée de la grille des salaires.


INSTITUTIONS ET DEMOCRATIE :



EDUCATION, CULTURE ET INFORMATION :



GEOPOLITIQUE INTERNATIONALE


SANTE ET BIEN-ETRE

- Un plan de développement de l’hôpital public sera mis en place (100.000 emplois créés, arret de privatisation des hopitaux, construction d'etablissements de santés, nouveaux lits...)
- La Sécurité sociale deviendra le bien de ses cotisants, par le biais de l’élection de leurs représentants
- Des mesures urgentes seront prises pour rendre les soins accessibles à tous (franchises médicales et participations forfaitaires supprimées, tiers payant généralisé, 4000 places d'etudiants en medecine supplémentaire ouverte).

**Comment by Plok64** [comment]
YANNICK JADOT : (IN PROGRESS)

ENVIRONNEMENT / ENERGIE :
- Sortie de l'élevage industriel
- Sortie du nucléaire

TRAVAIL ET ECONOMIE :
- Mise en place d'un ISF climatique : impot modulé en fonction de l'impact environnemental par les plus riches
- SMIC à 1400 euros net par mois. La semaine de travail passe à 32 heures par semaine
- Mise en place d'un revenu citoyen. Personne en france ne pourra toucher en dessous de 920 euros par mois

SOLIDARITE ET INCLUSION :
- Investissement de 1 milliard d'euros contre les violence faites aux femmes
- Inscrire le droit à l'IVG dans la constitution
- Création de 700.000 nouveaux logements sociaux

INSTITUTIONS ET DEMOCRATIE :
- Supprimer le renouvellement d'un mandat pour le président
- Donner plus de pouvoir au parlement, l'assemblée sera entièrement paritaire
- Le mandat du président passe à 7 années

EDUCATION, CULTURE ET INFORMATION :
- recrutement de 65.000 enseignants en augmentant leurs salaires de 20%
- Appel au boycott des marques dont les produits proviennent de la région ou sont persécuté les Ouigours

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- Etre plus ferme face au gouvernement chinois
- fusionner l'IGPN et l'IGGN dans la police pour en faire un organisme indépendant du ministère de l'intérieur

SANTE ET BIEN-ETRE :
- recrutement de 100.000 infirmiers en augmentant leurs salaires de 10%
- reconnaitre le burn out et la depression comme des maladies professionnelles

**Comment by Plok64** [comment]
### JEAN LASSALLE : (IN PROGRESS)

ENVIRONNEMENT / ENERGIE :
- 3 milliars d'euros dans le domaine de la ruralité
- Developpement des energies renouvelables et des nouveaux réacteur nucléaire 
- les communes peuvent décider la construction ou non construction des éoliennes sur leurs territoire. 

TRAVAIL ET ECONOMIE :
- Retablir l'ISF
- Nationaliser des entreprises dans les secteurs clés de l'économie (agriculture, insdustrie, energies nouvelles, automobile, aeronotique, EDF, les autoroutes de frances et toutes entreprise liées à la défense nationale) 
- SMIC à 1400 euros net par mois

SOLIDARITE ET INCLUSION :
- Elargir le RSA aux jeunes à partir de 18 ans
- Assurer un logement pour tout les sans abris en proposant un accompagnement pour aux services de santé, en mettant en place des logements sociaux à bas loyer et en encourageant le bénévolat
- Rendre l'allocation adulte handicapé indépendante des revenus du conjoint

INSTITUTIONS ET DEMOCRATIE :
- Mise en place du référendum d'initiative citoyenne à partir de 700.000 signatures
- Référendum pour proposer un mandat présidentiel de 7 années 
- Reconnaissance du vote blanc.


EDUCATION, CULTURE ET INFORMATION :
- les étudiants peuvent bénéficier d'un pret de 20.000 euros à taux 0 pour financer leurs études
- Rétablissement d'un service civil ou militaire obligatoire à 18 ans pendant 9 mois. Ils seront rémunéré à 500 euros par mois pour cela.
- Suivi psychologique plus important pour les élèves victime de harcelement

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- Sortie de l'OTAN
- Renforcer la cyberdéfense et la recherche spaciale, recrutement de 6000 gendarmes et policiers
- Retrait des troupes millitaires à l'étranger par référendum ou par vote au parlement

SANTE ET BIEN-ETRE :
- Ouvrir 20.000 lits d'hopitaux et recruter 100.000 soignants
- Mettre fin au brevet pharmaceutique sur les médicaments jugés importants

**Comment by lfaucon** [comment]
Starting to look great! 👍

**Comment by Plok64** [comment]
Philippe Poutou :

ENVIRONNEMENT / ENERGIE :
- Plan 100% energie renouvelable pour 2050 / Isolation thermique de tous les logements
- 100% agriculture bio sur 10 ans / developpement des circuits court 
- Nationnalisation des forêts de plus de 20 ha

TRAVAIL / ECONOMIE :
- smic à 1800 euros / semaine de travail de 4 jours : 32h vers les 28h / +400 euros sur tous les salaires
- Chomage, AAH et minimum vieillesse à 1800 euros
- Retraite à 60 ans, 55 ans pour les travaux pénibles

SOLIDARITE / INCLUSION :
- Développement des moyens pour acceuillir les femmes victimes de violence (logement d'urgence, formation de personnel...)
- Changement d'Etat civil pour les personnes trans sur demande / procreation médicalement assistée
- Abrogation des lois discriminant les musulmans

INSTITUTION / DEMOCRATIE :
- Suppression de la présidence de la république et du Sénat
- Mise en place du RIC
- Proportionnelle intégrale à toute les élections

EDUCATION / CULTURE / INFORMATION :
- fin de la vidéosurveillance et des vigiles à l'université
- pas plus de 20 élèves par classe dans les lycées
- fin de la présence des patrons dans les conseils d'administration des universités

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- Désarmement de la police et suppression de la BAC et BRAV-M
- Sortie de l'OTAN
- Désarmement unilatéral et général, ce qui implique la destruction des armes nucléaires française

SANTE / BIEN ETRE :
- Arret de fermeture des lits, réouverture et extension des hopitaux
- Pas de dépassements d'honoraires / suppression des franchises et des forfaits hospitaliers
- expropriation des grand groupe de l'industrie pharmaceutique / levée des brevets

**Comment by Plok64** [comment]
Anne Hidalgo :

ENVIRONNEMENT / ENERGIE :
- Energie 100 % renouvelable le plus rapidement possible
- Retour de l'ISF pour financer la transition energitique 
- lutte contre le changement climatique dans la constitution
- Voiture electrique en location moins cher qu'un vehicule à essence


TRAVAIL / ECONOMIE :
- Augmentation du SMIC de 15%
- Limiter l'écart de salaire à 1 à 20 entre le plus haut et le plus bas en entreprise.
- verser 5000 euros à tous les jeunes à 18 ans / 564 euros par mois de minimum jeunesse


SOLIDARITE / INCLUSION :
- création d'un ministere dédié au droit des femmes
- construction de 150.000 logements sociaux par an
- congés paternité à 16 semaines

INSTITUTION / DEMOCRATIE :
- droit de vote à 16 ans / droit de vote pour les etrangers pour les elections locales
- Instaurer le référendum d'initiative citoyenne


EDUCATION / CULTURE / INFORMATION :
- suppression parcoursup


GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- Union Européenne au coeurs de toute chose


SANTE / BIEN ETRE :
- Legaliser l'euthanasie

**Comment by Plok64** [comment]
Nicolas Dupont-Aignan :

ENVIRONNEMENT / ENERGIE :
- maintenir le nucléaire à 70% dans la production d'energie
- supprimer toutes les éoliennes
- developper les transports en commun propres


TRAVAIL / ECONOMIE :
- augmentation de 8% de tout les salaires en dessous de 3 fois le SMIC en réduisant les cotisations salariales
- Rétablissement de l'ISF
- travaux d'interet général pour les chomeurs de longue durée en échange d'une somme d'argent

SOLIDARITE / INCLUSION :
- expulser les délinquants étrangers à l'issue de leur peine / si possible les mettre en prison dans leurs propres pays
- renvoyer les mineurs isols étrangers
- supression du droit du sol

INSTITUTION / DEMOCRATIE :
- changer l'union européenne / empécher de nouveaux pays d'y entrer
- instaurer le RIC 
-mandat présidentiel à 7 années non renouvelable avec referendum pour destituer le president à mi-mandat
- reconnaitre le vote blanc

EDUCATION / CULTURE / INFORMATION :
- service civique de 3 mois obligatoire prolongeable par un service millitaire
- Rétablir le BAC avant la réforme de Jean-Michel Blanquere
- supprimer la prise en compte du controle continu / passer de 9h à 15h par semaine le temps consacré au francais et aux maths


GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- supression de la loi qui aménage les peines de prison courtes
- abaissement de la majorité pénale à 16 ans
- + 40.000 places en prison
- +40.000 soldats en plus

SANTE / BIEN ETRE :
- mettre fin à toutes les restrictions sanitaire comme le pass vaccinale
- reouvrir un hopital dans chaque departement
- recruter du personnel de santé et des assistants sociales et augmenter leur salaire de +5% brut
-80.000 postes supplémentaires dans les epads / 250.000 place en plus dans les creche

**Comment by Plok64** [comment]
Valérie Pecresse :

ENVIRONNEMENT / ENERGIE :
- développer le nucléaire au maximum
- s'opposer à l'écologie punitive
-developper des transports en commun plus propre et interdire les ventes de voitures neuves à partir de 2035


TRAVAIL / ECONOMIE :
- réduire les dépenses de l'état en supprimant 200.000 postes de fonctionnaires
- augmentation des salaires de 3% des salaires net pour les postes dans les secteurs privés, les secteurs publique à voir
- passer de 35h de travail par semaine à 39h


SOLIDARITE / INCLUSION :
- retraite à 65 ans au lieu de 62 ans
- mettre en place un quota maximum d'immigrés en france qui sera voté chaque années par le parlement
- mettre fin au droit du sol

INSTITUTION / DEMOCRATIE :
- renforcer nos liens avec les USA
- simplification de l'administration française


EDUCATION / CULTURE / INFORMATION :
- donner 500 à 670 euros par mois au jeunes suivant une formation pour apprendre un métier
- 2h de francais et 1h de maths en plus par semaine
- examen pour passer du CM2 à la 6eme

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- investir 5 milliard d'euros pour les équipements des policiers / armer la police municipale
- ouvrir 20.000 place de prison supplémentaires


SANTE / BIEN ETRE :
- recruter 25.000 personnes dans le domaine de la santé
- Confinement obligatoire des non vaccinés et pass vaccinal en cas d'épidémie

**Comment by Plok64** [comment]
Nathalie Arthaud :

ENVIRONNEMENT / ENERGIE :



TRAVAIL / ECONOMIE :
- supprimer la TVA
- SMIC à 2000 euros par mois / diminuer le temps de travail à 15 heures par semaine
- Interdire le licenciement pour les patron : ce sont les salariés qui votent le licenciement en cas de faute


SOLIDARITE / INCLUSION :
- retraite à 60 ans à taux plein
- acceuillir tous les immigrés sur le territoire sans conditions
- aligner le congé paternité au congé maternité

INSTITUTION / DEMOCRATIE :
- possibilité au peuple de révoquer n'importe quel élus à tout moment par RIC ou manifestation
- prendre en compte le vote blanc

EDUCATION / CULTURE / INFORMATION :
- supprimer les frais d'inscription à l'université 
- augmenter la bourse étudiante
- suppression des jeux olympiques en france

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- fin des opérations militaires française
- ouverture de toutes les frontière de l'europe

SANTE / BIEN ETRE :
- gratuité totale des soins
- interdire la chasse à courre et l'élevage intensif

**Comment by Plok64** [comment]
Eric Zemmour :

ENVIRONNEMENT / ENERGIE :
- developper le nucléaire au maximum par les EPR
- Interdire les éoliennes


TRAVAIL / ECONOMIE :
- supprimer toutes les aides sociales aux étranger
- réduire les impots sur la production et les importations
- supprimer les droits de succession et de donnations 
- supprimer la contribution sociale généralisé pour ceux gagnant moins de 2000 euros par mois
- enlever les charges sur les primes des entreprises

SOLIDARITE / INCLUSION :
- réduire l'immigration à
- supprimer le droit du sol
- mettre fin au regroupement familiale pour les etranger
- réduire les demandeurs d'asiles et les étudiants étrangers
- Interdiction de la procréation médicalement assistée

INSTITUTION / DEMOCRATIE :
- etre vigilant pour faire respecter la laïcité
- sortie de l'OTAN

EDUCATION / CULTURE / INFORMATION :
- instaurer des classes de niveaux
- rétablir l'uniforme
- interdire aux parents de donner un prénom étranger à leurs enfants

GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- expulser tout les délinquants étranger
- retirer la nationnalité francaise au délinquant ayant une double nationnalité et les expulser
- majorité pénale à 16 ans


SANTE / BIEN ETRE :
- supprimer l'aide médicale d'état aux étrangers

**Comment by Plok64** [comment]
Jean-Luc Mélenchon :

ENVIRONNEMENT / ENERGIE :
- passer au 100% renouvelable le plus vite possible
- règle verte : ne pas prélever plus à la nature que ce que la nature peut reconstituer
- interdire tous les OGM et pesticides

TRAVAIL / ECONOMIE :
- SMIC à 1400 euros net par mois / 32 heures par semaine
- Bloquer les prix des produits de première nécessité
- Nationaliser les aéroports, les autoroutes et la FDJ

SOLIDARITE / INCLUSION :
- retraite à taux plein à 60 ans
- 1 milliard d'euros pour lutter contre le sexisme et les violences faites aux femmes
- AAH indépendante des revenus du conjoint

INSTITUTION / DEMOCRATIE :
- mettre en place une 6eme république et faire réécrire la constitution aux citoyens et le faire adopter par référendum
- service citoyen obligatoire de 9 mois pour tous les jeunes de moins de 25 ans payés au salaire minimum
- Mise en place du RIC

EDUCATION / CULTURE / INFORMATION :
- Investir dans le domaine de l'espace et créer une université de l'espace


GEOPOLITIQUE INTERNATIONALE / SECURITE INTERIEUR :
- démenteler la BAC et la remplacer par une police de proximitée
- sortie de l'OTAN
- Réformer les traités européen pour que le programme soit applicable. Si la négociation échoue => désobéissance des traités quitte à payer des amendes


SANTE / BIEN ETRE :
- Fin du pass vaccinal
- légaliser le cannabis

**Comment by Plok64** [comment]
Je vais me coucher, je complète les petits trous dès que je me lève.

Il ne manque plus que Macron à traité, si une ame charitable veut s'en occuper, je veux bien, je ne sais pas si j'aurais le temps

**Comment by GresilleSiffle** [comment]
Thanks @Plok64 for all your work.

Take some rest if you need, if only E. Macron is missing we will handle it.
