### ISSUE TITLE
[back] feat: API endpoint for distribution of ContributorRatingCriteriaScores

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#691]
# Context
We want to be able to see the distribution of votes on a content. This would help contributors to know whether the judgements of a content are very polarized or not.

# Expected changes
Create a new API endpoint that returns the distribution of the ContributorRatingCriteriaScores for each criteria:
`/entities/{uid}/criteria_scores_distributions/{poll_name}` or
`/poll/{poll_name}/criteria_scores_distributions/{entity_uid}` (the developper can choose).

Output payload may look like this (exact format can be discussed as part of the implementation)
```JSON
{
      "uid": "string",
      "type": "video",
      "metadata": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      },
      "tournesol_score": 0,
      "n_contributors": 0,
      "criteria_scores_distributions": [
        {
          "name": "largely_recommended",
          "distribution": [0,0,0,0,1,3,7,10,4,3,1,0,0,0],
          "bins": [-2, -1.8, -1.6, ...,  0, 0.2, 0.4, ... 2], 
        },
        ...
      ]
}
```

We need to figure out how to choose the bins well

/!\ In order to protect privacy of users the distribution should only include public contributor ratings

**Comment by farnots** [comment]
Just started this task but I seam more logical to return a list of object for the `distribution` instead of uncoupled `list`.

Ex : 

```json
"criteria_scores_distributions": [
{
    "name": "largely_recommended",
    "distribution": {
        "-2" : "0",
        "-1.8" : "1",
        "-1.6" : "7",
        "..." : "...",
        "0.2": "10" 
    }
},

```

What do you think about this suggestion @lfaucon ?

**Comment by lfaucon** [comment]
Ok for me, but I would prefer somthing that shows bins more clearly `(-2, -1.8)` not only `-2`.
