### ISSUE TITLE
Deploy TournesolBot on the server

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#717]
When #567 and #701 will be merged some operation will remain:

* [x] Add previous tweets to the database
* [x] Copy the TournesolBot's secret on the server
* [x] Test its behaviors manually during a week or two
* [x] Set cronjob to run it automatically

**Comment by lfaucon** [comment]
Blocked until we switch to Mehestan just to ensure that the new algorithm does not interfere with the video selection of the bot
