### ISSUE TITLE
Rated videos should be removed from rate-later list in the backend

### ISSUE THREAD

**Issue by tchaumeny** [tournesol-app/tournesol#74]
As [discussed on Discord](https://discord.com/channels/760540475139817472/834689634042380328/838340802728034366), we should remove the rated video from the rate-later list in the backend.

Maybe this could be implemented within the `save` method of the [ExpertRatingsSerializerV2](https://github.com/tournesol-app/tournesol/blob/master/backend/backend/api_v2/expert_ratings.py#L76):

```python
class ExpertRatingsSerializerV2(serializers.HyperlinkedModelSerializer):
    ...

    def save(self, **kwargs):
        super().save(**kwargs)
        # Remove self.validated_data['video_1'] and self.validated_data['video_2'] from rate later list
    ...
```

**Comment by lenhoanglnh** [comment]
As discussed with @aidanjungo also, we may want to remove from the rate-later list only once the video has been rated at least 3 times.

**Comment by aidanjungo** [comment]
Or even better after x times, x being chosen by the user (with default value of 3).
But with the current algorithm which select the next video to watch it will encourage ratings of all the video in the "rate later" list between them but not with vs formerly rated videos.

**Comment by sergeivolodin** [comment]
@lenhoanglnh how should it work? is it still relevant given that we switch to a list of proposed videos to rate?

**Comment by lenhoanglnh** [comment]
Probably not, no.
