### ISSUE TITLE
Add option to "vouch for a contributor" on the contributor's page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#76]
In addition to the option to "follow" (see #57), a contributor A can "vouch" for a contributor B by clicking a "vouch" button on their home page. 
The button should open a menu like the following (design to be optimized and integrated to the user page, poke @aidanjungo / @TheDuckWhisperer, see also #58).
"Proof of Personhood" should point to this [wiki page](https://wiki.tournesol.app/index.php/Proof_of_personhood).
<img width="560" alt="Screen Shot 2021-05-04 at 08 55 49" src="https://user-images.githubusercontent.com/10453308/116969428-89271f80-acb6-11eb-9213-d7bdc7d0ecdb.png">
(for the public/privacy setting, use the same icons as on the rate page about video private rating setting)

Also, I propose to implement the following Byzantine-resilient vouching rule:
- the voucher's vouching power is 1 for the first 3 vouches. Afterwards, the (3+n)-th vouch gets a power of (3/4)^n. (This is an updated to guarantee that a validated account cannot become unvalidated under normal circumstances... In total, a voucher would have a total of 7 vouching powers).
- An account is validated only if it receives at least 2 full power vouches from email-validated accounts.

**Comment by lenhoanglnh** [comment]
Maybe add as well an option to report a probably fake account?

**Comment by sergeivolodin** [comment]
@lenhoanglnh Is it the same as #89 ?

**Comment by lenhoanglnh** [comment]
No, here is about account validation, not email validation.

**Comment by sergeivolodin** [comment]
Can only vouch for someone once

**Comment by lenhoanglnh** [comment]
@sergeivolodin will this be ready by Monday evening? (at least the vouching button)
My Monday video is currently claiming that it is 😅
