### ISSUE TITLE
[back][front] refactor: statistics in the home page represent all the polls

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#776]
This could be misleading, because in the videos home page we are mixing specific stats, like the number of videos, with generic stats like the number of comparisons. Currently this number of comparisons also counts the comparisons made in the `presidentielle2022` poll, so the numbers in home page don't share the same scope.

**proposition**

Make the statictics endpoint aware of the poll (`/stats/?poll_name=`), and adapt the front end accordingly. This will allow the front end to display reliable numbers on the different home page.

I think `/stats/?poll_name=` is better here than `/stats/{poll_name}`, as it allows us to have sub path like `/stats/criteria/`, `/stats/time/ or similar that are able to return in the same response the statistics of all polls. With a URL parameter instead of a path parameter we are able to create global statistics and statistics by poll.

In the future, we could still add an endpoint that returns stats for all polls (`/stats/`).

**Comment by GresilleSiffle** [comment]
What do you think @lfaucon @aidanjungo @amatissart ?

**Comment by lfaucon** [comment]
Completely agree! I don't like that the stats and also the text at the bottom of the about page are misleading.

Comment about the endpoint. What do you think about keeping it a single endpoint which returns stats on all polls, with for example the format:

```JSON
{ 
    "all": { 
        "n_comparisons": 999999,
        "n_entities": 999    
     },
    "presidentiell2022": { 
        "n_comparisons": 555555, 
        "n_entities": 555    
     },
    "videos": { 
        "n_comparisons": 444444, 
        "n_entities": 444    
     },
} 
```

I don't think the design choice here matters a lot in anycase, so I don't mind going with any option. I find the option I propose here slightly simpler.

**Comment by amatissart** [comment]
I agree that a simple endpoint to list all polls is probably enough at this point.  

About @lfaucon's suggestion: using dynamic values (the poll names) as object keys in the response may be a bit impractical when using the generated code on the client side, and to build the documentation. These keys can't be known in advance when the OpenAPI schema is generated.

An array would be more straightforward to integrate I think:
```json
{
  "active_users": {
    "total": 123,
    "joined_last_month": 42
  },
  "polls": [
    {
      "name": "videos",
      "compared_entities": {
        "total": 1234,
        "added_last_month": 234
      },
      "comparisons": {
        "total": 12345,
        "added_last_month": 2345
      }
    }
  ]
}
```

**Comment by lfaucon** [comment]
I like the last version of the output as proposed by @amatissart . Let's do it

**Comment by GresilleSiffle** [comment]
Now that the work has been done, it now unlocks this issue:
https://github.com/tournesol-app/tournesol/issues/935
