### ISSUE TITLE
Improve logo designs

### ISSUE THREAD

**Issue by TheDuckWhisperer** [tournesol-app/tournesol#78]
Current iterations: https://www.figma.com/proto/3uI7FiBhXp0hhgdTdHBSkj/Tournesol?node-id=408%3A638&viewport=442%2C396%2C0.5036531686782837&scaling=min-zoom&page-id=0%3A1 

Feedback from Lê: 
Cool! I prefer variation 4 :slight_smile:
This is only my opinion, but I think that the logo looks nicer with longer petals and a smaller center of the flower. 
I feel that yellow and green should be the dominant colors (not the brown of the center of the flower).
I like that, in the current logo, these colors stand out.

**Comment by sergeivolodin** [comment]
@lenhoanglnh where should this logo go?
