### ISSUE TITLE
internationalization of tournesol app

### ISSUE THREAD

**Issue by Naheulf** [tournesol-app/tournesol#81]
Even if english is the main international language, a lot of users prefers front-end displayed on they native language.

The first step to do that is internationalization (or i18n in short). And form what I seen both Django and react.js support it.

**Comment by lfaucon** [comment]
That's interesting! Can you share links that you find are good explanation of the concepts. I would be happy to discuss it (for example on our discord) some day

**Comment by sergeivolodin** [comment]
Which languages should we support?

**Comment by lenhoanglnh** [comment]
French only for now.
But if it's easy, we can get people involved in more translations.

**Comment by Naheulf** [comment]
> Which languages should we support?

For now that doesn't matter. (see [Internationalization and localization](https://en.wikipedia.org/wiki/Internationalization_and_localization)). This issue is more "make Tournesol translatable / language independant".

Localization (ie: Translations in other languages than English, French for me) come after and will detect errors/missing in this first i18n step.
