### ISSUE TITLE
Volition learning

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#84]
The volition is often described as what contributors "would want to want, especially if they knew more and thought deeper", as opposed to preferences which relate to what they want without thinking much.

On Tournesol, we should expect contributors to provide ratings without sufficient thoughts and knowledge. This is fine.
But we need algorithms that account for this, and that fix contributor's systematic biases when rating.

**Status:** this is currently being investigated. Please contact me if interested in this research direction.

**Comment by sergeivolodin** [comment]
To begin with, we can compare the ratings of people with expertise v.s. those without any
