### ISSUE TITLE
Rss feed for recommended ressources not working

### ISSUE THREAD

**Issue by parisni** [tournesol-app/tournesol#842]
I tried to import the various feeds the website proposes in my reader without success

**Comment by GresilleSiffle** [comment]
Hello @parisni 

As far as I know the tournesol.app website is not providing any RSS feed, that might be why you are not able to import them.

Which URL did you try to import exactly?

**Comment by parisni** [comment]
i use a tool which auto detect rss links on a webside.

apparently it found
 https://tournesol.app/rss.xml 

which is an existing page, but with a human content  (no 404 error
provided)

**Comment by aidanjungo** [comment]
We have now two YouTube playlist (en and fr) which are updated everyday with the best videos from Tournesol, you can get the RSS feed from those playlist with the following links:

- **en**: https://www.youtube.com/feeds/videos.xml?playlist_id=PLXX93NlSmUpayYeaNvKaeftX_QwEei3fU
- **fr**: https://www.youtube.com/feeds/videos.xml?playlist_id=PLXX93NlSmUpZkR9NaBXMaPlPalESb5tDv
