### ISSUE TITLE
[front] feat: adapt the `presidentielle` tutorial to the videos poll

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#844]
We have found that it was very useful for users to understand the core functionalities of Tournesol to start with this tutorial so we want to adapt it to the videos too.

What roughly needs to be done:
- [x] Decide on how videos are proposed for comparisons. An idea would be to select good (score > 0) and short (duration < 4min) videos in the language of the user.
  - see the PR https://github.com/tournesol-app/tournesol/pull/1021
  - videos are **safe recommendations**
  - from the **top 100 of all-time** recommendation...
  - ...having a **max duration 5 minutes** 
- [x] Decide on the length of the tutorial? Maybe 7 comparisons is too much?
  - we decided a **length of 4**
- [x] The videos must use the user's language
  - see #1035 
- [x] Adapt the text of the tutorial when used in the Video Poll
- [x] Add a link to start the tutorial on the Home Page of the Video Poll
  - see: https://github.com/tournesol-app/tournesol/issues/1046

**Comment by adrausch** [comment]
> 

Selecting short duration is a good idea but I asked @GresilleSiffle and he explained me that we need to change the backend to filter the "duration" parameter in the entities metadata and that we would not have tool to filter with "inferior or equal" on this criterium.
So should we (me and @GresilleSiffle) implement this in the backend or do you think about an alternative that we wouldn't have thought of?

**Comment by lfaucon** [comment]
We have already work in progress concerning adding the ability to filter with "greater than" / "less than" operations on the duration: https://github.com/tournesol-app/tournesol/issues/669 @farnots probably has work in progress on this. Can you try reaching out on Discord?

In order to not be blocked, it is great to do a version of this tutorial without any duration filter and add it later.

**Comment by GresilleSiffle** [comment]
I think we reached this first milestone about the tutorial and more generally this first milestone about Tounesol accessibility.

Few improvements I see for the future:
- rework the Home page : reducing the amount of text, talk about the platform, not the underlying software ; add images, etc.
- sometimes videos suggested by the tutorial doesn't exist anymore on YouTube
- we could add a help button on the comparison page, display a comparison FAQ + some explanation from the tutorial inside a dialog box

**Comment by lfaucon** [comment]
Created the issue #1070 concerning your second point
