### ISSUE TITLE
Bayesian Byzantine-resilience

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#85]
Because they are fake, or because of a lack of expertise, we should expect many ratings to be misleading (= Byzantine in distributed computing jargon). This may lead to dangerous recommendations, e.g. racist videos or vaccine misinformation on top.

To protect against this, the intuitive idea is to adjust the voting rights of a contributor based on the probability of the reliability of their vote, especially for quality criteria like "reliable and not misleading" on technical topics or "layman-friendly" if rated by an expert.

This is related to [Condorcet's jury theorem](https://en.wikipedia.org/wiki/Condorcet%27s_jury_theorem), albeit significant improvements are needed.

**Status:** This research is on the verge of being tackled, but manpower is very much needed. So far, the research is entirely theoretical. Please contact me if interested to collaborate.

**Comment by sergeivolodin** [comment]
What if we compute the probability of being malicious using a similar algorithm as for tournesol?

- the current contributor trustworthiness probability is used for this algorithm
- this algorithm computes the new trustworthiness scores and they are used to compute the scores for the videos
