### ISSUE TITLE
[front] Investigate possibilities for Tournesol to be a PWA

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#861]
- [x] Learn about PWA: https://web.dev/progressive-web-apps/
- [x] Make a small presentationation to the team with the most important things to understand about PWA
- [x] If it is decided, make the necessary changes such that Tournesol can be a PWA

**Comment by adrausch** [comment]
Presentation in english?

**Comment by lfaucon** [comment]
For anytime when ready & in French should be good :)

**Comment by lfaucon** [comment]
To-do short term:
- Check what can be done easily and do it.
- Discuss with the team about what cannot be done easily and would be valuable
