### ISSUE TITLE
Decentralize email domain validation

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#89]
We should think of a way to enable a collaborative way to accept email domains (rather than centralizing this task on a single point of failure named Lê 😅).
Ideally, it would be good as well to estimate the number of expected accounts from this email domain, to detect potential suspicious behaviors.

**Comment by sergeivolodin** [comment]
@lenhoanglnh I saw this in the whitepaper -- can you describe how to implement it?

**Comment by sergeivolodin** [comment]
@lenhoanglnh  Is it the same as #76 ?

**Comment by lenhoanglnh** [comment]
No this is future work.

**Comment by sergeivolodin** [comment]
We could vote on the domains...
