### ISSUE TITLE
[front] Add a share button on the video analysis page

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#915]
from @GresilleSiffle idea in #907:
What about adding a share button next the compare button in the top right corner of the video analysis page? This will allow users to quickly copy / paste link (maybe share the page on social network), and may create a virtuous circle where people share & compare videos more easily. 🌻

**Comment by Sbyspaceopera** [comment]
If you are ok with adding a dependency I think this library ccould be a great time saver when this feature will leaves the backlogs :

https://www.npmjs.com/package/react-share

Types are includes and it seems easy to use.
