### ISSUE TITLE
Many videos have the wrong language

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#93]
For example: 
- "I-n2OU78Ck8" is French, but Tournesol thinks it is English
- "Ms153kckhkQ" is French, but tournesol thinks it is German

Would Youtube provide more reliable information here ?

**Comment by aidanjungo** [comment]
Yes same for:

- "ARAQUgkdIvQ" is French, but Tournesol thinks it is English
- "F7YlkbhYq3s" is French, but Tournesol thinks it is English

**Comment by aidanjungo** [comment]
Also the "langdetect" gives very strange and not consistent results when there is a mix of two languages:

with the code:

`from langdetect import detect,detect_langs

t = 'This is fromage, baguette et croissant and also you can imagine ça pourrait être english or french'
for i in range (6):
    print('Test ',i)
    print(detect_langs(t))
    print(detect(t))`

It gives:

`Test  0
[fr:0.5714279843168742, en:0.4285717922216604]
fr
Test  1
[en:0.7142837816924028, fr:0.28571557060660485]
en
Test  2
[fr:0.5714299506390116, en:0.42856986113627804]
fr
Test  3
[en:0.7142838481684115, fr:0.2857161439607298]
en
Test  4
[en:0.8571394586776105, fr:0.14286018540151038]
en
Test  5
[en:0.8571396261756059, fr:0.1428602973501344]
fr`

**Comment by sergeivolodin** [comment]
I'll try to get the language from ytdl
