### ISSUE TITLE
Create collapsible description (from YouTube creator) on Video Analysis page

### ISSUE THREAD

**Issue by adrausch** [tournesol-app/tournesol#930]

**Comment by GresilleSiffle** [comment]
If I understand correctly the objective is to create a new component that will display the description as it appears on YouTube?

**Comment by adrausch** [comment]
> If I understand correctly the objective is to create a new component that will display the description as it appears on YouTube?

Yes! The objective is to keep user on Tournesol when the creator say "you can see the sources and links in the description"
