### ISSUE TITLE
[front] style: Improve Distribution Histogram readability

### ISSUE THREAD

**Issue by adrausch** [tournesol-app/tournesol#932]
- [ ] Make the chart denser (smaller chart, smaller font, less space)
- [x] Show which bucket the user is in
  - see https://github.com/tournesol-app/tournesol/pull/1472 
- [x] increase histogram granularity (buckets of size 1 instead of 2, or maybe variable sizes)
  - see: https://github.com/tournesol-app/tournesol/pull/1459

**Comment by GresilleSiffle** [comment]
> increase histogram granularity (buckets of size 1 instead of 2, or maybe variable sizes)

In the back end, in the `Entity` model we can increase the numbers of bins by replacing:
```python
distribution, bins = np.histogram(np.clip(values, *range), range=range)
```
by
```python
distribution, bins = np.histogram(np.clip(values, *range), bins=20, range=range)
```

This will automatically make increase the granularity of the data displayed in the front end. One little downside we could address: it's now hard to read the horizontal axis values, even on desktop.

![capture](https://user-images.githubusercontent.com/39056254/178706435-707e6b7a-dcea-410e-9a3d-28fe28b71536.png)

**Comment by glerzing** [comment]
Les lignes verticales en pointillés sont un peu bizarres, ce serait plus logique qu'elles partent de [-80, -40, 0, 40, 80] plutôt que de [-70, -30, 10, 50, 90].

Aussi, ça me paraîtrait plus logique que les marques en bas indiquent [-80, -60, -40, -20, 0, 20, 40, 60, 80] ou bien juste [-80, -40, 0, 40, 80] plutôt que ["-80 to 60", "40 to -20", "0 to 20", "40 to 60", "> 80"]. Après je ne sais pas, c'est peut-être une contrainte de la librairie.

**Comment by aidanjungo** [comment]
I think in the same time we could also round the value we display on the barchart

![image](https://user-images.githubusercontent.com/53896963/185648789-7efc9282-362b-4781-8a6c-be6413e0c616.png)

**Comment by GresilleSiffle** [comment]
> I think in the same time we could also round the value we display on the barchart

This has been solved already in the main branch :ok_hand: 

> Aussi, ça me paraîtrait plus logique que les marques en bas indiquent [-80, -60, -40, -20, 0, 20, 40, 60, 80] ou bien juste [-80, -40, 0, 40, 80] plutôt que ["-80 to 60", "40 to -20", "0 to 20", "40 to 60", "> 80"]. Après je ne sais pas, c'est peut-être une contrainte de la librairie. Il est peut-être faisable de le faire en insérant du CSS.

Should be solved by the PR https://github.com/tournesol-app/tournesol/pull/1459
