### ISSUE TITLE
[back] feat: Tournesol Bot tweets about top contributors

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#949]
Idea: Display the nice sunflower-bar chart that shows the number of comparisons in the last month for the ten top contributors (probably restrict to public)

**Comment by aidanjungo** [comment]
Some questions link to that:

- Should we use only public comparisons?
- Do we ask people to be feature in this graph?
- Should we have this feature somewhere on Tournesol website and once a month take a "screenshot" and tweet it? or should it be only linked the the TwitterBot model?

**Comment by lfaucon** [comment]
Proposition of answers


> * Should we use only public comparisons?

Public is safer

> * Do we ask people to be feature in this graph?

No, because it's already public data

> * Should we have this feature somewhere on Tournesol website and once a month take a "screenshot" and tweet it? or should it be only linked the the TwitterBot model?

That would be nice to also see it in a page of the website.
I'd propose to have a cronjob that generates the right png in the server's static file such that it is easily accessible
I think it is easiest to start implementing this feature inside the Django twitter app for now. If we get more data-analytics close to the django app, we would later create a separate app for it.

**Comment by GresilleSiffle** [comment]
Thanks to #956 the back end is now able to compute the top n contributors of any month of any year. It also prives a shortcut to get the top n contributors of the last month.

**Comment by lfaucon** [comment]
Thanks @aidanjungo !
