### ISSUE TITLE
Active learning for video selection in rate page

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#96]
#38 proposes "quick fixes", but there's a deeper more general question about what video to propose to contributors to rate.
In particular, eventually, we need to aim for algorithms that learn the contributors' rating habits to facilitate their tasks.

**Comment by sergeivolodin** [comment]
What should we do if we had unlimited compute? I think it should be something like minimizing uncertainty with some exploration as well...

**Comment by sergeivolodin** [comment]
@lenhoanglnh 

Following the idea on using Google Search, what if we use Youtube recommendations for this? :) We open the youtube page of the FIRST video, and then get the RECOMMENDED videos (on the right) as potential candidates for the SECOND video

**Comment by lenhoanglnh** [comment]
Yes we can do this :)
