### ISSUE TITLE
Update README for new contributors

### ISSUE THREAD

**Issue by sergia-ch** [tournesol-app/tournesol#97]
Currently, the README is a bit out of date:

- 'this github' -> this repository
- Make first two lines one line
- Move 'tested in Ubuntu...' into a list of tested architectures (Win, Linux, Mac, Mac arm)
- Remove api v1
- Add a diagram of all components and their interactions
- Update ML model description to match the new sparse tensor implementation
- Remove 'Where to add online updates' section
- Update Directory structure and Development workflow

**Comment by sergeivolodin** [comment]
@lenhoanglnh @lfaucon @Grim-bot @tchaumeny what do you think?

**Comment by sergeivolodin** [comment]
Docker image build (with 1gb/s link)

Time:
```
real	8m57.520s
user	0m0.431s
sys	0m0.452s
```

Downloads 1.29 GB
```
>>> (33070016015-31679552127)/(1024**3)
1.2949704080820084
```

**Comment by sergeivolodin** [comment]
- add to Dockerfile motd that tournesol repo is in `/tournesol`
- only show motd via bashrc, not via ssh (rename /etc/motd to /etc/motd.tournesol)

**Comment by lfaucon** [comment]
All the changes proposed seem good to me
