### ISSUE TITLE
[front] feat: display a weekly collective objective in the comparison page

### ISSUE THREAD

**Issue by GresilleSiffle** [tournesol-app/tournesol#974]
### context

In order to engage contributors to add comparisons, I propose to create and display a collective goal on the comparison page. A collective weekly goal could be 1000 comparisons per week. This way, contributors can collectively estimate how close / far they are from the weekly objective, can be motivated to add more comparisons, and have a direct feedback of their individual implication.

Here is how Common Voice display its daily objective after 5 contributions: 

![capture](https://user-images.githubusercontent.com/39056254/172807516-9b2c9e5f-a6dc-4311-914b-439580cb8198.png)

This feature can be part of the UX effort to make the Tournesol application more enjoyable.

(see: https://commonvoice.mozilla.org/fr)

### UX proposition

I imagine a progress bar at the top of the comparison page:

```
Thanks to everyone, Tournesol has reached 60% of its weekly objective of 1000 comparisons.
[----------------------->                    ]               4,2% comes directly from you.
```

In the progress bar, we could use the buffer feature of the MUI progress component to display in a different color the personal contribution of the logged user.

The component must display:
- a sentence explaining what the progress bar represents
- a progress bar representing the collective progress, with a buffer representing the logged user progress
- a little message displaying the percentage "added" by the logged user 

### technical specification

The developers must be able to display this component anywhere in the application. 

When seen by anonymous users, the UI can be:

```
Thanks to everyone, Tournesol has reached 60% of its weekly objective of 1000 comparisons.
[----------------------->                    ]                    Help us reach this goal!
```

Where `Help us reach this goal!` is a light grey link to the sign-up page.

### technical specifications

**back end**
- [ ] **(a)** identify and develop a way to retrieve the comparisons made since the last Monday and today (could be part of the current stats API)
- [ ] **(b)** identify and develop a way to retrieve the comparisons made by the logged user since the last Monday and today (could be part of the current `/users/me/comparisons/` API, an additional GET parameter could be enough)
- [ ] add new API tests

Regarding the point **(a)**, it's important to choose a good name for the new metric, to avoid confusion with the existing one. We already have `added_last_month`, we could use `added_this_week` to create a difference between sliding and non-sliding metrics (last VS. this).

Example:
- added **last** month: number of comparisons made during the last 30 days
- added **this** month: number of comparisons made since the first day of the current month

In our case, we need the weekly metric. We can update the `ComparisonsStatisticsSerializer` to add the new `added_this_week` field.

```python
class ComparisonsStatisticsSerializer(Serializer):
    total = IntegerField()
    # last means during the last 30 days
    added_last_month = IntegerField()
    # this means since the first day of the current week
    added_this_week = IntegerField()
```

**front end**

- [ ] develop the component described above

**Comment by abhiram11** [comment]
Hi, I was working on this and found out that I do not have sufficient permissions for file `tournesol/frontend/src/services/openapi/models/ComparisonsStatistics.ts` and I cannot add the following changes into it:

```/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type ComparisonsStatistics = {
    added_last_week: any; // this line specifically
    total: number;
    added_last_month: number;
};

```

I have also added a few lines of code in multiple files including the backend and frontend. Would you like me to open a PR and work on it?

**Comment by aidanjungo** [comment]
Hello,

Thank you for your help, this ticket is tagged as "backlog/idea" because it lacks some specifications and should be adresses in a more general context (documented specs are a bit outdated). 

To get a new issue the best is to chose one from the "selected" column of the [kanban](https://github.com/tournesol-app/tournesol/projects/9) and ask for assignation. 
Even better you could discuss about it on our [Discord server](https://discord.com/invite/TvsFB8RNBV) so we could find what is the best for you and align with the current development of the platform.

Thank you again for your help.

**Comment by abhiram11** [comment]
I understand, thanks for explaining the scenario. I had a chat with @lfaucon and we had a discussion on whether I could look into this issue, so I did some research on it and thought that I could add this feature to some extent. :smile:

**Comment by abhiram11** [comment]
Working on it! 🚀 Thank you for assigning me
