### ISSUE TITLE
Non-validated contributor's scores

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol#98]
From what I understand, right now, non-validated contributor's scores are not computed.
https://tournesol.app/user/Trichodrome%20%C3%A9chelette

To compute scores, we first run our current algorithm to derive the global scores s*.
Then, we optimize the loss for non-validated contributor with the fixed global scores s*.
<img width="1074" alt="Screen Shot 2021-05-12 at 19 14 35" src="https://user-images.githubusercontent.com/10453308/118016941-4c15f980-b356-11eb-81d1-58362968ed88.png">

**Comment by sergeivolodin** [comment]
It feels a bit like a dictatorship of the global scores w.r.t. the invidividual scores, maybe they should have no leader?

**Comment by sergeivolodin** [comment]
it's like "everyone can contribute to this, and everyone is equal in this score"

**Comment by sergeivolodin** [comment]
[or we can implement all three :)]

**Comment by lenhoanglnh** [comment]
This should be viewed rather as "leveraging the community" to learn individual scores with fewer data.
If the contributor provides sufficiently many ratings, then their scores will no longer depend on the global scores :)

**Comment by lenhoanglnh** [comment]
In any case, we should first solve #88, which will enable to calibrate lambda (it should be of the order of 1 / spread of the scores, and could be different for different videos, see [writeup](https://www.overleaf.com/project/5f44dd8e84c8540001bf1552)).
